from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.audit_stamp import AuditStamp
from openapi_server import util

from openapi_server.models.audit_stamp import AuditStamp  # noqa: E501

class AuditFields(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, created=None, modified=None, deleted=None, soft_delete=False):  # noqa: E501
        """AuditFields - a model defined in OpenAPI

        :param created: The created of this AuditFields.  # noqa: E501
        :type created: AuditStamp
        :param modified: The modified of this AuditFields.  # noqa: E501
        :type modified: AuditStamp
        :param deleted: The deleted of this AuditFields.  # noqa: E501
        :type deleted: AuditStamp
        :param soft_delete: The soft_delete of this AuditFields.  # noqa: E501
        :type soft_delete: bool
        """
        self.openapi_types = {
            'created': AuditStamp,
            'modified': AuditStamp,
            'deleted': AuditStamp,
            'soft_delete': bool
        }

        self.attribute_map = {
            'created': 'created',
            'modified': 'modified',
            'deleted': 'deleted',
            'soft_delete': 'softDelete'
        }

        self._created = created
        self._modified = modified
        self._deleted = deleted
        self._soft_delete = soft_delete

    @classmethod
    def from_dict(cls, dikt) -> 'AuditFields':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AuditFields of this AuditFields.  # noqa: E501
        :rtype: AuditFields
        """
        return util.deserialize_model(dikt, cls)

    @property
    def created(self) -> AuditStamp:
        """Gets the created of this AuditFields.


        :return: The created of this AuditFields.
        :rtype: AuditStamp
        """
        return self._created

    @created.setter
    def created(self, created: AuditStamp):
        """Sets the created of this AuditFields.


        :param created: The created of this AuditFields.
        :type created: AuditStamp
        """

        self._created = created

    @property
    def modified(self) -> AuditStamp:
        """Gets the modified of this AuditFields.


        :return: The modified of this AuditFields.
        :rtype: AuditStamp
        """
        return self._modified

    @modified.setter
    def modified(self, modified: AuditStamp):
        """Sets the modified of this AuditFields.


        :param modified: The modified of this AuditFields.
        :type modified: AuditStamp
        """

        self._modified = modified

    @property
    def deleted(self) -> AuditStamp:
        """Gets the deleted of this AuditFields.


        :return: The deleted of this AuditFields.
        :rtype: AuditStamp
        """
        return self._deleted

    @deleted.setter
    def deleted(self, deleted: AuditStamp):
        """Sets the deleted of this AuditFields.


        :param deleted: The deleted of this AuditFields.
        :type deleted: AuditStamp
        """

        self._deleted = deleted

    @property
    def soft_delete(self) -> bool:
        """Gets the soft_delete of this AuditFields.


        :return: The soft_delete of this AuditFields.
        :rtype: bool
        """
        return self._soft_delete

    @soft_delete.setter
    def soft_delete(self, soft_delete: bool):
        """Sets the soft_delete of this AuditFields.


        :param soft_delete: The soft_delete of this AuditFields.
        :type soft_delete: bool
        """

        self._soft_delete = soft_delete
