from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class KnowledgeCreate(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, title=None, body=None, tags=None, visibility=None, animalid=None):  # noqa: E501
        """KnowledgeCreate - a model defined in OpenAPI

        :param title: The title of this KnowledgeCreate.  # noqa: E501
        :type title: str
        :param body: The body of this KnowledgeCreate.  # noqa: E501
        :type body: str
        :param tags: The tags of this KnowledgeCreate.  # noqa: E501
        :type tags: List[str]
        :param visibility: The visibility of this KnowledgeCreate.  # noqa: E501
        :type visibility: str
        :param animalid: The animalid of this KnowledgeCreate.  # noqa: E501
        :type animalid: str
        """
        self.openapi_types = {
            'title': str,
            'body': str,
            'tags': List[str],
            'visibility': str,
            'animalid': str
        }

        self.attribute_map = {
            'title': 'title',
            'body': 'body',
            'tags': 'tags',
            'visibility': 'visibility',
            'animalid': 'animalid'
        }

        self._title = title
        self._body = body
        self._tags = tags
        self._visibility = visibility
        self._animalid = animalid

    @classmethod
    def from_dict(cls, dikt) -> 'KnowledgeCreate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The KnowledgeCreate of this KnowledgeCreate.  # noqa: E501
        :rtype: KnowledgeCreate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this KnowledgeCreate.


        :return: The title of this KnowledgeCreate.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this KnowledgeCreate.


        :param title: The title of this KnowledgeCreate.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def body(self) -> str:
        """Gets the body of this KnowledgeCreate.


        :return: The body of this KnowledgeCreate.
        :rtype: str
        """
        return self._body

    @body.setter
    def body(self, body: str):
        """Sets the body of this KnowledgeCreate.


        :param body: The body of this KnowledgeCreate.
        :type body: str
        """
        if body is None:
            raise ValueError("Invalid value for `body`, must not be `None`")  # noqa: E501

        self._body = body

    @property
    def tags(self) -> List[str]:
        """Gets the tags of this KnowledgeCreate.


        :return: The tags of this KnowledgeCreate.
        :rtype: List[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags: List[str]):
        """Sets the tags of this KnowledgeCreate.


        :param tags: The tags of this KnowledgeCreate.
        :type tags: List[str]
        """

        self._tags = tags

    @property
    def visibility(self) -> str:
        """Gets the visibility of this KnowledgeCreate.


        :return: The visibility of this KnowledgeCreate.
        :rtype: str
        """
        return self._visibility

    @visibility.setter
    def visibility(self, visibility: str):
        """Sets the visibility of this KnowledgeCreate.


        :param visibility: The visibility of this KnowledgeCreate.
        :type visibility: str
        """
        allowed_values = ["public", "staff", "internal"]  # noqa: E501
        if visibility not in allowed_values:
            raise ValueError(
                "Invalid value for `visibility` ({0}), must be one of {1}"
                .format(visibility, allowed_values)
            )

        self._visibility = visibility

    @property
    def animalid(self) -> str:
        """Gets the animalid of this KnowledgeCreate.


        :return: The animalid of this KnowledgeCreate.
        :rtype: str
        """
        return self._animalid

    @animalid.setter
    def animalid(self, animalid: str):
        """Sets the animalid of this KnowledgeCreate.


        :param animalid: The animalid of this KnowledgeCreate.
        :type animalid: str
        """

        self._animalid = animalid
