# User Context API Contract
# Conversation Safety and Personalization System

openapi: 3.0.3
info:
  title: CMZ User Context API
  description: User personalization and conversation context management
  version: 1.0.0

paths:
  /api/v1/context/{userId}:
    get:
      summary: Get user conversation context
      description: |
        Retrieves personalized context for enhancing conversation responses.
        Includes user preferences, interests, and summarized conversation history.
      operationId: getUserContext
      parameters:
        - name: userId
          in: path
          required: true
          description: User identifier
          schema:
            type: string
        - name: includeHistory
          in: query
          description: Include detailed conversation history
          schema:
            type: boolean
            default: false
        - name: contextDepth
          in: query
          description: Amount of context to include
          schema:
            type: string
            enum: [minimal, standard, comprehensive]
            default: standard
      responses:
        '200':
          description: User context retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserContextProfile'
        '404':
          description: User context not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      summary: Update user conversation context
      description: |
        Updates user preferences and context based on conversation interactions.
        Typically called after each conversation to maintain current preferences.
      operationId: updateUserContext
      parameters:
        - name: userId
          in: path
          required: true
          description: User identifier
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserContextUpdate'
      responses:
        '200':
          description: Context updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserContextProfile'
        '400':
          description: Invalid update request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/context/{userId}/summarize:
    post:
      summary: Trigger conversation summarization
      description: |
        Manually triggers summarization of recent conversations to compress context.
        Typically runs automatically but can be manually invoked for immediate updates.
      operationId: summarizeUserContext
      parameters:
        - name: userId
          in: path
          required: true
          description: User identifier
          schema:
            type: string
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                conversationLimit:
                  type: number
                  description: Number of recent conversations to summarize
                  default: 10
                  minimum: 1
                  maximum: 50
                forceUpdate:
                  type: boolean
                  description: Force summarization even if recently updated
                  default: false
      responses:
        '200':
          description: Summarization completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SummarizationResult'
        '202':
          description: Summarization started asynchronously
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  jobId:
                    type: string
                  estimatedCompletion:
                    type: string
                    format: date-time

  /api/v1/context/{userId}/preferences:
    get:
      summary: Get user preferences only
      description: Lightweight endpoint for retrieving just user preferences
      operationId: getUserPreferences
      parameters:
        - name: userId
          in: path
          required: true
          description: User identifier
          schema:
            type: string
      responses:
        '200':
          description: User preferences retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPreferences'

    patch:
      summary: Update specific user preferences
      description: |
        Updates specific user preferences without affecting full context.
        Useful for preference-only updates from UI controls.
      operationId: updateUserPreferences
      parameters:
        - name: userId
          in: path
          required: true
          description: User identifier
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PreferenceUpdate'
      responses:
        '200':
          description: Preferences updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPreferences'

  /api/v1/context/{userId}/privacy:
    get:
      summary: Get user privacy settings and data summary
      description: |
        Retrieves privacy settings and summary of stored personal data.
        Used by parent dashboard for privacy management.
      operationId: getUserPrivacyData
      parameters:
        - name: userId
          in: path
          required: true
          description: User identifier
          schema:
            type: string
      responses:
        '200':
          description: Privacy data retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPrivacyData'
        '403':
          description: Insufficient permissions to access privacy data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      summary: Delete user context and conversation data
      description: |
        Permanently deletes specified types of user data for privacy compliance.
        Supports selective deletion of different data categories.
      operationId: deleteUserData
      parameters:
        - name: userId
          in: path
          required: true
          description: User identifier
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataDeletionRequest'
      responses:
        '200':
          description: Data deletion completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataDeletionResult'
        '202':
          description: Data deletion started asynchronously
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  jobId:
                    type: string
                  estimatedCompletion:
                    type: string
                    format: date-time

components:
  schemas:
    UserContextProfile:
      type: object
      required:
        - userId
        - preferences
        - conversationHistory
      properties:
        userId:
          type: string
          description: User identifier
        preferences:
          $ref: '#/components/schemas/UserPreferences'
        conversationHistory:
          type: object
          properties:
            totalConversations:
              type: number
              description: Count of total conversations
            lastActive:
              type: string
              format: date-time
              description: Last conversation timestamp
            engagementScore:
              type: number
              minimum: 0
              maximum: 100
              description: User engagement quality score
        contextSummary:
          type: object
          properties:
            recentSummary:
              type: string
              description: Summary of last 5 conversations
            historicalSummary:
              type: string
              description: Summary of older conversations
            keyQuotes:
              type: array
              items:
                type: string
              description: Memorable user statements
            lastUpdated:
              type: string
              format: date-time
        metadata:
          type: object
          properties:
            created:
              type: object
              properties:
                at:
                  type: string
                  format: date-time
                by:
                  type: string
            modified:
              type: object
              properties:
                at:
                  type: string
                  format: date-time
                by:
                  type: string
            version:
              type: number

    UserPreferences:
      type: object
      properties:
        interests:
          type: array
          items:
            type: string
          description: User interests and hobbies
          example: ["cats", "conservation", "marine biology"]
        learningLevel:
          type: string
          enum: [elementary, middle, high, adult]
          description: Educational level for content appropriateness
        favoriteAnimals:
          type: array
          items:
            type: string
          description: Preferred animal types
          example: ["lions", "dolphins", "penguins"]
        topics:
          type: array
          items:
            type: string
          description: Educational topics of interest
          example: ["habitats", "conservation", "animal behavior"]
        communicationStyle:
          type: string
          enum: [formal, casual, enthusiastic, curious]
          description: Preferred interaction style
        learningGoals:
          type: array
          items:
            type: string
          description: Educational objectives
          example: ["learn about conservation", "understand animal behavior"]

    UserContextUpdate:
      type: object
      properties:
        conversationData:
          type: object
          required:
            - conversationId
            - animalId
            - timestamp
          properties:
            conversationId:
              type: string
            animalId:
              type: string
            timestamp:
              type: string
              format: date-time
            duration:
              type: number
              description: Conversation length in minutes
            engagement:
              type: object
              properties:
                messageCount:
                  type: number
                averageResponseTime:
                  type: number
                followUpQuestions:
                  type: number
                satisfaction:
                  type: number
                  minimum: 1
                  maximum: 5
        extractedPreferences:
          type: object
          properties:
            newInterests:
              type: array
              items:
                type: string
            preferenceChanges:
              type: object
              additionalProperties:
                type: string
            learningProgress:
              type: array
              items:
                type: string
        contextTriggers:
          type: object
          properties:
            shouldSummarize:
              type: boolean
              description: Whether this update should trigger summarization
            priorityUpdate:
              type: boolean
              description: Whether this is a high-priority context change

    PreferenceUpdate:
      type: object
      properties:
        interests:
          type: array
          items:
            type: string
        learningLevel:
          type: string
          enum: [elementary, middle, high, adult]
        favoriteAnimals:
          type: array
          items:
            type: string
        topics:
          type: array
          items:
            type: string
        communicationStyle:
          type: string
          enum: [formal, casual, enthusiastic, curious]
        learningGoals:
          type: array
          items:
            type: string

    UserPrivacyData:
      type: object
      properties:
        dataSummary:
          type: object
          properties:
            conversationCount:
              type: number
            preferenceCount:
              type: number
            contextDataSize:
              type: number
              description: Approximate size in bytes
            lastActivity:
              type: string
              format: date-time
        dataCategories:
          type: array
          items:
            type: object
            properties:
              category:
                type: string
                enum: [conversations, preferences, context, analytics]
              description:
                type: string
              itemCount:
                type: number
              canDelete:
                type: boolean
              retentionPeriod:
                type: string
        privacySettings:
          type: object
          properties:
            dataRetentionPeriod:
              type: number
              description: Data retention in days
            allowAnalytics:
              type: boolean
            allowPersonalization:
              type: boolean
            parentalControls:
              type: boolean

    DataDeletionRequest:
      type: object
      required:
        - dataTypes
        - reason
      properties:
        dataTypes:
          type: array
          items:
            type: string
            enum: [conversations, preferences, context, analytics, all]
          description: Types of data to delete
        reason:
          type: string
          description: Reason for deletion (required for audit)
        dateRange:
          type: object
          properties:
            startDate:
              type: string
              format: date-time
            endDate:
              type: string
              format: date-time
          description: Optional date range for selective deletion
        parentConsent:
          type: boolean
          description: Whether parent consent has been verified

    DataDeletionResult:
      type: object
      properties:
        deletedItems:
          type: object
          additionalProperties:
            type: number
          description: Count of deleted items by category
        auditLogId:
          type: string
          description: Audit log entry for this deletion
        completedAt:
          type: string
          format: date-time
        warnings:
          type: array
          items:
            type: string
          description: Any warnings or issues during deletion

    SummarizationResult:
      type: object
      properties:
        conversationsProcessed:
          type: number
        originalTokens:
          type: number
        compressedTokens:
          type: number
        compressionRatio:
          type: number
        qualityScore:
          type: number
          minimum: 0
          maximum: 100
        newSummary:
          type: string
        processingTime:
          type: number
          description: Processing time in milliseconds

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: object
        timestamp:
          type: string
          format: date-time
        requestId:
          type: string