from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class MemberShell(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, preferences=None, alerts=None):  # noqa: E501
        """MemberShell - a model defined in OpenAPI

        :param preferences: The preferences of this MemberShell.  # noqa: E501
        :type preferences: Dict[str, object]
        :param alerts: The alerts of this MemberShell.  # noqa: E501
        :type alerts: List[str]
        """
        self.openapi_types = {
            'preferences': Dict[str, object],
            'alerts': List[str]
        }

        self.attribute_map = {
            'preferences': 'preferences',
            'alerts': 'alerts'
        }

        self._preferences = preferences
        self._alerts = alerts

    @classmethod
    def from_dict(cls, dikt) -> 'MemberShell':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MemberShell of this MemberShell.  # noqa: E501
        :rtype: MemberShell
        """
        return util.deserialize_model(dikt, cls)

    @property
    def preferences(self) -> Dict[str, object]:
        """Gets the preferences of this MemberShell.


        :return: The preferences of this MemberShell.
        :rtype: Dict[str, object]
        """
        return self._preferences

    @preferences.setter
    def preferences(self, preferences: Dict[str, object]):
        """Sets the preferences of this MemberShell.


        :param preferences: The preferences of this MemberShell.
        :type preferences: Dict[str, object]
        """

        self._preferences = preferences

    @property
    def alerts(self) -> List[str]:
        """Gets the alerts of this MemberShell.


        :return: The alerts of this MemberShell.
        :rtype: List[str]
        """
        return self._alerts

    @alerts.setter
    def alerts(self, alerts: List[str]):
        """Sets the alerts of this MemberShell.


        :param alerts: The alerts of this MemberShell.
        :type alerts: List[str]
        """

        self._alerts = alerts
