from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.audit_stamp import AuditStamp
from openapi_server import util

from openapi_server.models.audit_stamp import AuditStamp  # noqa: E501

class Summary(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, created=None, modified=None, deleted=None, soft_delete=False, session_id=None, summary=None):  # noqa: E501
        """Summary - a model defined in OpenAPI

        :param created: The created of this Summary.  # noqa: E501
        :type created: AuditStamp
        :param modified: The modified of this Summary.  # noqa: E501
        :type modified: AuditStamp
        :param deleted: The deleted of this Summary.  # noqa: E501
        :type deleted: AuditStamp
        :param soft_delete: The soft_delete of this Summary.  # noqa: E501
        :type soft_delete: bool
        :param session_id: The session_id of this Summary.  # noqa: E501
        :type session_id: str
        :param summary: The summary of this Summary.  # noqa: E501
        :type summary: str
        """
        self.openapi_types = {
            'created': AuditStamp,
            'modified': AuditStamp,
            'deleted': AuditStamp,
            'soft_delete': bool,
            'session_id': str,
            'summary': str
        }

        self.attribute_map = {
            'created': 'created',
            'modified': 'modified',
            'deleted': 'deleted',
            'soft_delete': 'softDelete',
            'session_id': 'sessionId',
            'summary': 'summary'
        }

        self._created = created
        self._modified = modified
        self._deleted = deleted
        self._soft_delete = soft_delete
        self._session_id = session_id
        self._summary = summary

    @classmethod
    def from_dict(cls, dikt) -> 'Summary':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Summary of this Summary.  # noqa: E501
        :rtype: Summary
        """
        return util.deserialize_model(dikt, cls)

    @property
    def created(self) -> AuditStamp:
        """Gets the created of this Summary.


        :return: The created of this Summary.
        :rtype: AuditStamp
        """
        return self._created

    @created.setter
    def created(self, created: AuditStamp):
        """Sets the created of this Summary.


        :param created: The created of this Summary.
        :type created: AuditStamp
        """

        self._created = created

    @property
    def modified(self) -> AuditStamp:
        """Gets the modified of this Summary.


        :return: The modified of this Summary.
        :rtype: AuditStamp
        """
        return self._modified

    @modified.setter
    def modified(self, modified: AuditStamp):
        """Sets the modified of this Summary.


        :param modified: The modified of this Summary.
        :type modified: AuditStamp
        """

        self._modified = modified

    @property
    def deleted(self) -> AuditStamp:
        """Gets the deleted of this Summary.


        :return: The deleted of this Summary.
        :rtype: AuditStamp
        """
        return self._deleted

    @deleted.setter
    def deleted(self, deleted: AuditStamp):
        """Sets the deleted of this Summary.


        :param deleted: The deleted of this Summary.
        :type deleted: AuditStamp
        """

        self._deleted = deleted

    @property
    def soft_delete(self) -> bool:
        """Gets the soft_delete of this Summary.


        :return: The soft_delete of this Summary.
        :rtype: bool
        """
        return self._soft_delete

    @soft_delete.setter
    def soft_delete(self, soft_delete: bool):
        """Sets the soft_delete of this Summary.


        :param soft_delete: The soft_delete of this Summary.
        :type soft_delete: bool
        """

        self._soft_delete = soft_delete

    @property
    def session_id(self) -> str:
        """Gets the session_id of this Summary.


        :return: The session_id of this Summary.
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id: str):
        """Sets the session_id of this Summary.


        :param session_id: The session_id of this Summary.
        :type session_id: str
        """

        self._session_id = session_id

    @property
    def summary(self) -> str:
        """Gets the summary of this Summary.


        :return: The summary of this Summary.
        :rtype: str
        """
        return self._summary

    @summary.setter
    def summary(self, summary: str):
        """Sets the summary of this Summary.


        :param summary: The summary of this Summary.
        :type summary: str
        """

        self._summary = summary
