from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class UserrolePatchRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_id=None, role=None):  # noqa: E501
        """UserrolePatchRequest - a model defined in OpenAPI

        :param user_id: The user_id of this UserrolePatchRequest.  # noqa: E501
        :type user_id: str
        :param role: The role of this UserrolePatchRequest.  # noqa: E501
        :type role: str
        """
        self.openapi_types = {
            'user_id': str,
            'role': str
        }

        self.attribute_map = {
            'user_id': 'userId',
            'role': 'role'
        }

        self._user_id = user_id
        self._role = role

    @classmethod
    def from_dict(cls, dikt) -> 'UserrolePatchRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _userrole_patch_request of this UserrolePatchRequest.  # noqa: E501
        :rtype: UserrolePatchRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> str:
        """Gets the user_id of this UserrolePatchRequest.


        :return: The user_id of this UserrolePatchRequest.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this UserrolePatchRequest.


        :param user_id: The user_id of this UserrolePatchRequest.
        :type user_id: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id

    @property
    def role(self) -> str:
        """Gets the role of this UserrolePatchRequest.


        :return: The role of this UserrolePatchRequest.
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role: str):
        """Sets the role of this UserrolePatchRequest.


        :param role: The role of this UserrolePatchRequest.
        :type role: str
        """
        allowed_values = ["visitor", "member", "editor", "admin"]  # noqa: E501
        if role not in allowed_values:
            raise ValueError(
                "Invalid value for `role` ({0}), must be one of {1}"
                .format(role, allowed_values)
            )

        self._role = role
