from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.audit_stamp import AuditStamp
from openapi_server import util

from openapi_server.models.audit_stamp import AuditStamp  # noqa: E501

class User(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, created=None, modified=None, deleted=None, soft_delete=False, id=None, email=None, display_name=None, role=None):  # noqa: E501
        """User - a model defined in OpenAPI

        :param created: The created of this User.  # noqa: E501
        :type created: AuditStamp
        :param modified: The modified of this User.  # noqa: E501
        :type modified: AuditStamp
        :param deleted: The deleted of this User.  # noqa: E501
        :type deleted: AuditStamp
        :param soft_delete: The soft_delete of this User.  # noqa: E501
        :type soft_delete: bool
        :param id: The id of this User.  # noqa: E501
        :type id: str
        :param email: The email of this User.  # noqa: E501
        :type email: str
        :param display_name: The display_name of this User.  # noqa: E501
        :type display_name: str
        :param role: The role of this User.  # noqa: E501
        :type role: str
        """
        self.openapi_types = {
            'created': AuditStamp,
            'modified': AuditStamp,
            'deleted': AuditStamp,
            'soft_delete': bool,
            'id': str,
            'email': str,
            'display_name': str,
            'role': str
        }

        self.attribute_map = {
            'created': 'created',
            'modified': 'modified',
            'deleted': 'deleted',
            'soft_delete': 'softDelete',
            'id': 'id',
            'email': 'email',
            'display_name': 'displayName',
            'role': 'role'
        }

        self._created = created
        self._modified = modified
        self._deleted = deleted
        self._soft_delete = soft_delete
        self._id = id
        self._email = email
        self._display_name = display_name
        self._role = role

    @classmethod
    def from_dict(cls, dikt) -> 'User':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The User of this User.  # noqa: E501
        :rtype: User
        """
        return util.deserialize_model(dikt, cls)

    @property
    def created(self) -> AuditStamp:
        """Gets the created of this User.


        :return: The created of this User.
        :rtype: AuditStamp
        """
        return self._created

    @created.setter
    def created(self, created: AuditStamp):
        """Sets the created of this User.


        :param created: The created of this User.
        :type created: AuditStamp
        """

        self._created = created

    @property
    def modified(self) -> AuditStamp:
        """Gets the modified of this User.


        :return: The modified of this User.
        :rtype: AuditStamp
        """
        return self._modified

    @modified.setter
    def modified(self, modified: AuditStamp):
        """Sets the modified of this User.


        :param modified: The modified of this User.
        :type modified: AuditStamp
        """

        self._modified = modified

    @property
    def deleted(self) -> AuditStamp:
        """Gets the deleted of this User.


        :return: The deleted of this User.
        :rtype: AuditStamp
        """
        return self._deleted

    @deleted.setter
    def deleted(self, deleted: AuditStamp):
        """Sets the deleted of this User.


        :param deleted: The deleted of this User.
        :type deleted: AuditStamp
        """

        self._deleted = deleted

    @property
    def soft_delete(self) -> bool:
        """Gets the soft_delete of this User.


        :return: The soft_delete of this User.
        :rtype: bool
        """
        return self._soft_delete

    @soft_delete.setter
    def soft_delete(self, soft_delete: bool):
        """Sets the soft_delete of this User.


        :param soft_delete: The soft_delete of this User.
        :type soft_delete: bool
        """

        self._soft_delete = soft_delete

    @property
    def id(self) -> str:
        """Gets the id of this User.


        :return: The id of this User.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this User.


        :param id: The id of this User.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def email(self) -> str:
        """Gets the email of this User.


        :return: The email of this User.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this User.


        :param email: The email of this User.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def display_name(self) -> str:
        """Gets the display_name of this User.


        :return: The display_name of this User.
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name: str):
        """Sets the display_name of this User.


        :param display_name: The display_name of this User.
        :type display_name: str
        """

        self._display_name = display_name

    @property
    def role(self) -> str:
        """Gets the role of this User.


        :return: The role of this User.
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role: str):
        """Sets the role of this User.


        :param role: The role of this User.
        :type role: str
        """
        allowed_values = ["visitor", "member", "editor", "admin"]  # noqa: E501
        if role not in allowed_values:
            raise ValueError(
                "Invalid value for `role` ({0}), must be one of {1}"
                .format(role, allowed_values)
            )

        self._role = role
