# coding: utf-8

"""
    CMZ API

    API for the Cougar Mountain Zoo digital ambassador platform

    The version of the OpenAPI document: 1.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.admin_api import router as AdminApiRouter
from openapi_server.apis.analytics_api import router as AnalyticsApiRouter
from openapi_server.apis.animals_api import router as AnimalsApiRouter
from openapi_server.apis.auth_api import router as AuthApiRouter
from openapi_server.apis.conversation_api import router as ConversationApiRouter
from openapi_server.apis.knowledge_api import router as KnowledgeApiRouter
from openapi_server.apis.later_api import router as LaterApiRouter
from openapi_server.apis.media_api import router as MediaApiRouter
from openapi_server.apis.system_api import router as SystemApiRouter
from openapi_server.apis.ui_api import router as UIApiRouter
from openapi_server.apis.users_api import router as UsersApiRouter

app = FastAPI(
    title="CMZ API",
    description="API for the Cougar Mountain Zoo digital ambassador platform",
    version="1.0.2",
)

app.include_router(AdminApiRouter)
app.include_router(AnalyticsApiRouter)
app.include_router(AnimalsApiRouter)
app.include_router(AuthApiRouter)
app.include_router(ConversationApiRouter)
app.include_router(KnowledgeApiRouter)
app.include_router(LaterApiRouter)
app.include_router(MediaApiRouter)
app.include_router(SystemApiRouter)
app.include_router(UIApiRouter)
app.include_router(UsersApiRouter)
