from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.audit_stamp import AuditStamp
from openapi_server import util

from openapi_server.models.audit_stamp import AuditStamp  # noqa: E501

class AnimalDetails(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, animal_id=None, name=None, species=None, status=None, created=None, modified=None, deleted=None, soft_delete=False, animal_detail_id=None, description=None, habitat=None, image_url=None):  # noqa: E501
        """AnimalDetails - a model defined in OpenAPI

        :param animal_id: The animal_id of this AnimalDetails.  # noqa: E501
        :type animal_id: str
        :param name: The name of this AnimalDetails.  # noqa: E501
        :type name: str
        :param species: The species of this AnimalDetails.  # noqa: E501
        :type species: str
        :param status: The status of this AnimalDetails.  # noqa: E501
        :type status: str
        :param created: The created of this AnimalDetails.  # noqa: E501
        :type created: AuditStamp
        :param modified: The modified of this AnimalDetails.  # noqa: E501
        :type modified: AuditStamp
        :param deleted: The deleted of this AnimalDetails.  # noqa: E501
        :type deleted: AuditStamp
        :param soft_delete: The soft_delete of this AnimalDetails.  # noqa: E501
        :type soft_delete: bool
        :param animal_detail_id: The animal_detail_id of this AnimalDetails.  # noqa: E501
        :type animal_detail_id: str
        :param description: The description of this AnimalDetails.  # noqa: E501
        :type description: str
        :param habitat: The habitat of this AnimalDetails.  # noqa: E501
        :type habitat: str
        :param image_url: The image_url of this AnimalDetails.  # noqa: E501
        :type image_url: str
        """
        self.openapi_types = {
            'animal_id': str,
            'name': str,
            'species': str,
            'status': str,
            'created': AuditStamp,
            'modified': AuditStamp,
            'deleted': AuditStamp,
            'soft_delete': bool,
            'animal_detail_id': str,
            'description': str,
            'habitat': str,
            'image_url': str
        }

        self.attribute_map = {
            'animal_id': 'animalId',
            'name': 'name',
            'species': 'species',
            'status': 'status',
            'created': 'created',
            'modified': 'modified',
            'deleted': 'deleted',
            'soft_delete': 'softDelete',
            'animal_detail_id': 'animalDetailId',
            'description': 'description',
            'habitat': 'habitat',
            'image_url': 'imageUrl'
        }

        self._animal_id = animal_id
        self._name = name
        self._species = species
        self._status = status
        self._created = created
        self._modified = modified
        self._deleted = deleted
        self._soft_delete = soft_delete
        self._animal_detail_id = animal_detail_id
        self._description = description
        self._habitat = habitat
        self._image_url = image_url

    @classmethod
    def from_dict(cls, dikt) -> 'AnimalDetails':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AnimalDetails of this AnimalDetails.  # noqa: E501
        :rtype: AnimalDetails
        """
        return util.deserialize_model(dikt, cls)

    @property
    def animal_id(self) -> str:
        """Gets the animal_id of this AnimalDetails.


        :return: The animal_id of this AnimalDetails.
        :rtype: str
        """
        return self._animal_id

    @animal_id.setter
    def animal_id(self, animal_id: str):
        """Sets the animal_id of this AnimalDetails.


        :param animal_id: The animal_id of this AnimalDetails.
        :type animal_id: str
        """
        if animal_id is None:
            raise ValueError("Invalid value for `animal_id`, must not be `None`")  # noqa: E501

        self._animal_id = animal_id

    @property
    def name(self) -> str:
        """Gets the name of this AnimalDetails.


        :return: The name of this AnimalDetails.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this AnimalDetails.


        :param name: The name of this AnimalDetails.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def species(self) -> str:
        """Gets the species of this AnimalDetails.


        :return: The species of this AnimalDetails.
        :rtype: str
        """
        return self._species

    @species.setter
    def species(self, species: str):
        """Sets the species of this AnimalDetails.


        :param species: The species of this AnimalDetails.
        :type species: str
        """
        if species is None:
            raise ValueError("Invalid value for `species`, must not be `None`")  # noqa: E501

        self._species = species

    @property
    def status(self) -> str:
        """Gets the status of this AnimalDetails.


        :return: The status of this AnimalDetails.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this AnimalDetails.


        :param status: The status of this AnimalDetails.
        :type status: str
        """
        allowed_values = ["active", "hidden"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def created(self) -> AuditStamp:
        """Gets the created of this AnimalDetails.


        :return: The created of this AnimalDetails.
        :rtype: AuditStamp
        """
        return self._created

    @created.setter
    def created(self, created: AuditStamp):
        """Sets the created of this AnimalDetails.


        :param created: The created of this AnimalDetails.
        :type created: AuditStamp
        """

        self._created = created

    @property
    def modified(self) -> AuditStamp:
        """Gets the modified of this AnimalDetails.


        :return: The modified of this AnimalDetails.
        :rtype: AuditStamp
        """
        return self._modified

    @modified.setter
    def modified(self, modified: AuditStamp):
        """Sets the modified of this AnimalDetails.


        :param modified: The modified of this AnimalDetails.
        :type modified: AuditStamp
        """

        self._modified = modified

    @property
    def deleted(self) -> AuditStamp:
        """Gets the deleted of this AnimalDetails.


        :return: The deleted of this AnimalDetails.
        :rtype: AuditStamp
        """
        return self._deleted

    @deleted.setter
    def deleted(self, deleted: AuditStamp):
        """Sets the deleted of this AnimalDetails.


        :param deleted: The deleted of this AnimalDetails.
        :type deleted: AuditStamp
        """

        self._deleted = deleted

    @property
    def soft_delete(self) -> bool:
        """Gets the soft_delete of this AnimalDetails.


        :return: The soft_delete of this AnimalDetails.
        :rtype: bool
        """
        return self._soft_delete

    @soft_delete.setter
    def soft_delete(self, soft_delete: bool):
        """Sets the soft_delete of this AnimalDetails.


        :param soft_delete: The soft_delete of this AnimalDetails.
        :type soft_delete: bool
        """

        self._soft_delete = soft_delete

    @property
    def animal_detail_id(self) -> str:
        """Gets the animal_detail_id of this AnimalDetails.


        :return: The animal_detail_id of this AnimalDetails.
        :rtype: str
        """
        return self._animal_detail_id

    @animal_detail_id.setter
    def animal_detail_id(self, animal_detail_id: str):
        """Sets the animal_detail_id of this AnimalDetails.


        :param animal_detail_id: The animal_detail_id of this AnimalDetails.
        :type animal_detail_id: str
        """

        self._animal_detail_id = animal_detail_id

    @property
    def description(self) -> str:
        """Gets the description of this AnimalDetails.


        :return: The description of this AnimalDetails.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this AnimalDetails.


        :param description: The description of this AnimalDetails.
        :type description: str
        """

        self._description = description

    @property
    def habitat(self) -> str:
        """Gets the habitat of this AnimalDetails.


        :return: The habitat of this AnimalDetails.
        :rtype: str
        """
        return self._habitat

    @habitat.setter
    def habitat(self, habitat: str):
        """Sets the habitat of this AnimalDetails.


        :param habitat: The habitat of this AnimalDetails.
        :type habitat: str
        """

        self._habitat = habitat

    @property
    def image_url(self) -> str:
        """Gets the image_url of this AnimalDetails.


        :return: The image_url of this AnimalDetails.
        :rtype: str
        """
        return self._image_url

    @image_url.setter
    def image_url(self, image_url: str):
        """Sets the image_url of this AnimalDetails.


        :param image_url: The image_url of this AnimalDetails.
        :type image_url: str
        """

        self._image_url = image_url
