from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class AnimalInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, species=None, status='active'):  # noqa: E501
        """AnimalInput - a model defined in OpenAPI

        :param name: The name of this AnimalInput.  # noqa: E501
        :type name: str
        :param species: The species of this AnimalInput.  # noqa: E501
        :type species: str
        :param status: The status of this AnimalInput.  # noqa: E501
        :type status: str
        """
        self.openapi_types = {
            'name': str,
            'species': str,
            'status': str
        }

        self.attribute_map = {
            'name': 'name',
            'species': 'species',
            'status': 'status'
        }

        self._name = name
        self._species = species
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'AnimalInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AnimalInput of this AnimalInput.  # noqa: E501
        :rtype: AnimalInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this AnimalInput.


        :return: The name of this AnimalInput.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this AnimalInput.


        :param name: The name of this AnimalInput.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) > 100:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `100`")  # noqa: E501
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def species(self) -> str:
        """Gets the species of this AnimalInput.


        :return: The species of this AnimalInput.
        :rtype: str
        """
        return self._species

    @species.setter
    def species(self, species: str):
        """Sets the species of this AnimalInput.


        :param species: The species of this AnimalInput.
        :type species: str
        """
        if species is None:
            raise ValueError("Invalid value for `species`, must not be `None`")  # noqa: E501
        if species is not None and len(species) > 100:
            raise ValueError("Invalid value for `species`, length must be less than or equal to `100`")  # noqa: E501
        if species is not None and len(species) < 1:
            raise ValueError("Invalid value for `species`, length must be greater than or equal to `1`")  # noqa: E501

        self._species = species

    @property
    def status(self) -> str:
        """Gets the status of this AnimalInput.


        :return: The status of this AnimalInput.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this AnimalInput.


        :param status: The status of this AnimalInput.
        :type status: str
        """
        allowed_values = ["active", "hidden"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status
