from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.audit_stamp import AuditStamp
from openapi_server import util

from openapi_server.models.audit_stamp import AuditStamp  # noqa: E501

class AnimalConfigUpdate(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, animal_config_id=None, voice=None, personality=None, ai_model=None, temperature=0.7, top_p=1, tools_enabled=None, guardrails=None, created=None, modified=None, deleted=None, soft_delete=False):  # noqa: E501
        """AnimalConfigUpdate - a model defined in OpenAPI

        :param animal_config_id: The animal_config_id of this AnimalConfigUpdate.  # noqa: E501
        :type animal_config_id: str
        :param voice: The voice of this AnimalConfigUpdate.  # noqa: E501
        :type voice: str
        :param personality: The personality of this AnimalConfigUpdate.  # noqa: E501
        :type personality: str
        :param ai_model: The ai_model of this AnimalConfigUpdate.  # noqa: E501
        :type ai_model: str
        :param temperature: The temperature of this AnimalConfigUpdate.  # noqa: E501
        :type temperature: float
        :param top_p: The top_p of this AnimalConfigUpdate.  # noqa: E501
        :type top_p: float
        :param tools_enabled: The tools_enabled of this AnimalConfigUpdate.  # noqa: E501
        :type tools_enabled: List[str]
        :param guardrails: The guardrails of this AnimalConfigUpdate.  # noqa: E501
        :type guardrails: Dict[str, object]
        :param created: The created of this AnimalConfigUpdate.  # noqa: E501
        :type created: AuditStamp
        :param modified: The modified of this AnimalConfigUpdate.  # noqa: E501
        :type modified: AuditStamp
        :param deleted: The deleted of this AnimalConfigUpdate.  # noqa: E501
        :type deleted: AuditStamp
        :param soft_delete: The soft_delete of this AnimalConfigUpdate.  # noqa: E501
        :type soft_delete: bool
        """
        self.openapi_types = {
            'animal_config_id': str,
            'voice': str,
            'personality': str,
            'ai_model': str,
            'temperature': float,
            'top_p': float,
            'tools_enabled': List[str],
            'guardrails': Dict[str, object],
            'created': AuditStamp,
            'modified': AuditStamp,
            'deleted': AuditStamp,
            'soft_delete': bool
        }

        self.attribute_map = {
            'animal_config_id': 'animalConfigId',
            'voice': 'voice',
            'personality': 'personality',
            'ai_model': 'aiModel',
            'temperature': 'temperature',
            'top_p': 'topP',
            'tools_enabled': 'toolsEnabled',
            'guardrails': 'guardrails',
            'created': 'created',
            'modified': 'modified',
            'deleted': 'deleted',
            'soft_delete': 'softDelete'
        }

        self._animal_config_id = animal_config_id
        self._voice = voice
        self._personality = personality
        self._ai_model = ai_model
        self._temperature = temperature
        self._top_p = top_p
        self._tools_enabled = tools_enabled
        self._guardrails = guardrails
        self._created = created
        self._modified = modified
        self._deleted = deleted
        self._soft_delete = soft_delete

    @classmethod
    def from_dict(cls, dikt) -> 'AnimalConfigUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AnimalConfigUpdate of this AnimalConfigUpdate.  # noqa: E501
        :rtype: AnimalConfigUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def animal_config_id(self) -> str:
        """Gets the animal_config_id of this AnimalConfigUpdate.


        :return: The animal_config_id of this AnimalConfigUpdate.
        :rtype: str
        """
        return self._animal_config_id

    @animal_config_id.setter
    def animal_config_id(self, animal_config_id: str):
        """Sets the animal_config_id of this AnimalConfigUpdate.


        :param animal_config_id: The animal_config_id of this AnimalConfigUpdate.
        :type animal_config_id: str
        """

        self._animal_config_id = animal_config_id

    @property
    def voice(self) -> str:
        """Gets the voice of this AnimalConfigUpdate.


        :return: The voice of this AnimalConfigUpdate.
        :rtype: str
        """
        return self._voice

    @voice.setter
    def voice(self, voice: str):
        """Sets the voice of this AnimalConfigUpdate.


        :param voice: The voice of this AnimalConfigUpdate.
        :type voice: str
        """

        self._voice = voice

    @property
    def personality(self) -> str:
        """Gets the personality of this AnimalConfigUpdate.


        :return: The personality of this AnimalConfigUpdate.
        :rtype: str
        """
        return self._personality

    @personality.setter
    def personality(self, personality: str):
        """Sets the personality of this AnimalConfigUpdate.


        :param personality: The personality of this AnimalConfigUpdate.
        :type personality: str
        """

        self._personality = personality

    @property
    def ai_model(self) -> str:
        """Gets the ai_model of this AnimalConfigUpdate.


        :return: The ai_model of this AnimalConfigUpdate.
        :rtype: str
        """
        return self._ai_model

    @ai_model.setter
    def ai_model(self, ai_model: str):
        """Sets the ai_model of this AnimalConfigUpdate.


        :param ai_model: The ai_model of this AnimalConfigUpdate.
        :type ai_model: str
        """

        self._ai_model = ai_model

    @property
    def temperature(self) -> float:
        """Gets the temperature of this AnimalConfigUpdate.


        :return: The temperature of this AnimalConfigUpdate.
        :rtype: float
        """
        return self._temperature

    @temperature.setter
    def temperature(self, temperature: float):
        """Sets the temperature of this AnimalConfigUpdate.


        :param temperature: The temperature of this AnimalConfigUpdate.
        :type temperature: float
        """
        if temperature is not None and temperature > 2:  # noqa: E501
            raise ValueError("Invalid value for `temperature`, must be a value less than or equal to `2`")  # noqa: E501
        if temperature is not None and temperature < 0:  # noqa: E501
            raise ValueError("Invalid value for `temperature`, must be a value greater than or equal to `0`")  # noqa: E501

        self._temperature = temperature

    @property
    def top_p(self) -> float:
        """Gets the top_p of this AnimalConfigUpdate.


        :return: The top_p of this AnimalConfigUpdate.
        :rtype: float
        """
        return self._top_p

    @top_p.setter
    def top_p(self, top_p: float):
        """Sets the top_p of this AnimalConfigUpdate.


        :param top_p: The top_p of this AnimalConfigUpdate.
        :type top_p: float
        """
        if top_p is not None and top_p > 1:  # noqa: E501
            raise ValueError("Invalid value for `top_p`, must be a value less than or equal to `1`")  # noqa: E501
        if top_p is not None and top_p < 0:  # noqa: E501
            raise ValueError("Invalid value for `top_p`, must be a value greater than or equal to `0`")  # noqa: E501

        self._top_p = top_p

    @property
    def tools_enabled(self) -> List[str]:
        """Gets the tools_enabled of this AnimalConfigUpdate.


        :return: The tools_enabled of this AnimalConfigUpdate.
        :rtype: List[str]
        """
        return self._tools_enabled

    @tools_enabled.setter
    def tools_enabled(self, tools_enabled: List[str]):
        """Sets the tools_enabled of this AnimalConfigUpdate.


        :param tools_enabled: The tools_enabled of this AnimalConfigUpdate.
        :type tools_enabled: List[str]
        """

        self._tools_enabled = tools_enabled

    @property
    def guardrails(self) -> Dict[str, object]:
        """Gets the guardrails of this AnimalConfigUpdate.


        :return: The guardrails of this AnimalConfigUpdate.
        :rtype: Dict[str, object]
        """
        return self._guardrails

    @guardrails.setter
    def guardrails(self, guardrails: Dict[str, object]):
        """Sets the guardrails of this AnimalConfigUpdate.


        :param guardrails: The guardrails of this AnimalConfigUpdate.
        :type guardrails: Dict[str, object]
        """

        self._guardrails = guardrails

    @property
    def created(self) -> AuditStamp:
        """Gets the created of this AnimalConfigUpdate.


        :return: The created of this AnimalConfigUpdate.
        :rtype: AuditStamp
        """
        return self._created

    @created.setter
    def created(self, created: AuditStamp):
        """Sets the created of this AnimalConfigUpdate.


        :param created: The created of this AnimalConfigUpdate.
        :type created: AuditStamp
        """

        self._created = created

    @property
    def modified(self) -> AuditStamp:
        """Gets the modified of this AnimalConfigUpdate.


        :return: The modified of this AnimalConfigUpdate.
        :rtype: AuditStamp
        """
        return self._modified

    @modified.setter
    def modified(self, modified: AuditStamp):
        """Sets the modified of this AnimalConfigUpdate.


        :param modified: The modified of this AnimalConfigUpdate.
        :type modified: AuditStamp
        """

        self._modified = modified

    @property
    def deleted(self) -> AuditStamp:
        """Gets the deleted of this AnimalConfigUpdate.


        :return: The deleted of this AnimalConfigUpdate.
        :rtype: AuditStamp
        """
        return self._deleted

    @deleted.setter
    def deleted(self, deleted: AuditStamp):
        """Sets the deleted of this AnimalConfigUpdate.


        :param deleted: The deleted of this AnimalConfigUpdate.
        :type deleted: AuditStamp
        """

        self._deleted = deleted

    @property
    def soft_delete(self) -> bool:
        """Gets the soft_delete of this AnimalConfigUpdate.


        :return: The soft_delete of this AnimalConfigUpdate.
        :rtype: bool
        """
        return self._soft_delete

    @soft_delete.setter
    def soft_delete(self, soft_delete: bool):
        """Sets the soft_delete of this AnimalConfigUpdate.


        :param soft_delete: The soft_delete of this AnimalConfigUpdate.
        :type soft_delete: bool
        """

        self._soft_delete = soft_delete
