from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.animal_config_update_guardrails import AnimalConfigUpdateGuardrails
import re
from openapi_server import util

from openapi_server.models.animal_config_update_guardrails import AnimalConfigUpdateGuardrails  # noqa: E501
import re  # noqa: E501

class AnimalConfigUpdate(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, voice=None, personality=None, ai_model=None, temperature=None, top_p=None, max_tokens=None, tools_enabled=None, response_format='text', guardrails=None):  # noqa: E501
        """AnimalConfigUpdate - a model defined in OpenAPI

        :param voice: The voice of this AnimalConfigUpdate.  # noqa: E501
        :type voice: str
        :param personality: The personality of this AnimalConfigUpdate.  # noqa: E501
        :type personality: str
        :param ai_model: The ai_model of this AnimalConfigUpdate.  # noqa: E501
        :type ai_model: str
        :param temperature: The temperature of this AnimalConfigUpdate.  # noqa: E501
        :type temperature: float
        :param top_p: The top_p of this AnimalConfigUpdate.  # noqa: E501
        :type top_p: float
        :param max_tokens: The max_tokens of this AnimalConfigUpdate.  # noqa: E501
        :type max_tokens: int
        :param tools_enabled: The tools_enabled of this AnimalConfigUpdate.  # noqa: E501
        :type tools_enabled: list[str]
        :param response_format: The response_format of this AnimalConfigUpdate.  # noqa: E501
        :type response_format: str
        :param guardrails: The guardrails of this AnimalConfigUpdate.  # noqa: E501
        :type guardrails: AnimalConfigUpdateGuardrails
        """
        self.openapi_types = {
            'voice': str,
            'personality': str,
            'ai_model': str,
            'temperature': float,
            'top_p': float,
            'max_tokens': int,
            'tools_enabled': list[str],
            'response_format': str,
            'guardrails': AnimalConfigUpdateGuardrails
        }

        self.attribute_map = {
            'voice': 'voice',
            'personality': 'personality',
            'ai_model': 'aiModel',
            'temperature': 'temperature',
            'top_p': 'topP',
            'max_tokens': 'maxTokens',
            'tools_enabled': 'toolsEnabled',
            'response_format': 'responseFormat',
            'guardrails': 'guardrails'
        }

        self._voice = voice
        self._personality = personality
        self._ai_model = ai_model
        self._temperature = temperature
        self._top_p = top_p
        self._max_tokens = max_tokens
        self._tools_enabled = tools_enabled
        self._response_format = response_format
        self._guardrails = guardrails

    @classmethod
    def from_dict(cls, dikt) -> 'AnimalConfigUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AnimalConfigUpdate of this AnimalConfigUpdate.  # noqa: E501
        :rtype: AnimalConfigUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def voice(self) -> str:
        """Gets the voice of this AnimalConfigUpdate.

        Validated voice ID from supported TTS voices  # noqa: E501

        :return: The voice of this AnimalConfigUpdate.
        :rtype: str
        """
        return self._voice

    @voice.setter
    def voice(self, voice: str):
        """Sets the voice of this AnimalConfigUpdate.

        Validated voice ID from supported TTS voices  # noqa: E501

        :param voice: The voice of this AnimalConfigUpdate.
        :type voice: str
        """
        allowed_values = ["alloy", "echo", "fable", "onyx", "nova", "shimmer", "ruth", "joanna", "matthew", "amy"]  # noqa: E501
        if voice not in allowed_values:
            raise ValueError(
                "Invalid value for `voice` ({0}), must be one of {1}"
                .format(voice, allowed_values)
            )

        self._voice = voice

    @property
    def personality(self) -> str:
        """Gets the personality of this AnimalConfigUpdate.

        Animal personality description with character validation  # noqa: E501

        :return: The personality of this AnimalConfigUpdate.
        :rtype: str
        """
        return self._personality

    @personality.setter
    def personality(self, personality: str):
        """Sets the personality of this AnimalConfigUpdate.

        Animal personality description with character validation  # noqa: E501

        :param personality: The personality of this AnimalConfigUpdate.
        :type personality: str
        """
        if personality is not None and len(personality) > 1000:
            raise ValueError("Invalid value for `personality`, length must be less than or equal to `1000`")  # noqa: E501
        if personality is not None and len(personality) < 5:
            raise ValueError("Invalid value for `personality`, length must be greater than or equal to `5`")  # noqa: E501
        if personality is not None and not re.search(r'^[a-zA-Z0-9\s\.,!?\-():\[\]]+$', personality):  # noqa: E501
            raise ValueError(r"Invalid value for `personality`, must be a follow pattern or equal to `/^[a-zA-Z0-9\s\.,!?\-():\[\]]+$/`")  # noqa: E501

        self._personality = personality

    @property
    def ai_model(self) -> str:
        """Gets the ai_model of this AnimalConfigUpdate.


        :return: The ai_model of this AnimalConfigUpdate.
        :rtype: str
        """
        return self._ai_model

    @ai_model.setter
    def ai_model(self, ai_model: str):
        """Sets the ai_model of this AnimalConfigUpdate.


        :param ai_model: The ai_model of this AnimalConfigUpdate.
        :type ai_model: str
        """
        allowed_values = ["gpt-4o-mini", "gpt-4o", "gpt-4", "gpt-3.5-turbo", "claude-3-sonnet", "claude-3-haiku", "claude-3-opus"]  # noqa: E501
        if ai_model not in allowed_values:
            raise ValueError(
                "Invalid value for `ai_model` ({0}), must be one of {1}"
                .format(ai_model, allowed_values)
            )

        self._ai_model = ai_model

    @property
    def temperature(self) -> float:
        """Gets the temperature of this AnimalConfigUpdate.

        AI model temperature (0.0-2.0, increments of 0.1)  # noqa: E501

        :return: The temperature of this AnimalConfigUpdate.
        :rtype: float
        """
        return self._temperature

    @temperature.setter
    def temperature(self, temperature: float):
        """Sets the temperature of this AnimalConfigUpdate.

        AI model temperature (0.0-2.0, increments of 0.1)  # noqa: E501

        :param temperature: The temperature of this AnimalConfigUpdate.
        :type temperature: float
        """
        if temperature is not None and temperature > 2.0:  # noqa: E501
            raise ValueError("Invalid value for `temperature`, must be a value less than or equal to `2.0`")  # noqa: E501
        if temperature is not None and temperature < 0.0:  # noqa: E501
            raise ValueError("Invalid value for `temperature`, must be a value greater than or equal to `0.0`")  # noqa: E501

        self._temperature = temperature

    @property
    def top_p(self) -> float:
        """Gets the top_p of this AnimalConfigUpdate.

        Top-p sampling parameter (0.0-1.0, increments of 0.01)  # noqa: E501

        :return: The top_p of this AnimalConfigUpdate.
        :rtype: float
        """
        return self._top_p

    @top_p.setter
    def top_p(self, top_p: float):
        """Sets the top_p of this AnimalConfigUpdate.

        Top-p sampling parameter (0.0-1.0, increments of 0.01)  # noqa: E501

        :param top_p: The top_p of this AnimalConfigUpdate.
        :type top_p: float
        """
        if top_p is not None and top_p > 1.0:  # noqa: E501
            raise ValueError("Invalid value for `top_p`, must be a value less than or equal to `1.0`")  # noqa: E501
        if top_p is not None and top_p < 0.0:  # noqa: E501
            raise ValueError("Invalid value for `top_p`, must be a value greater than or equal to `0.0`")  # noqa: E501

        self._top_p = top_p

    @property
    def max_tokens(self) -> int:
        """Gets the max_tokens of this AnimalConfigUpdate.

        Maximum response tokens (1-4096)  # noqa: E501

        :return: The max_tokens of this AnimalConfigUpdate.
        :rtype: int
        """
        return self._max_tokens

    @max_tokens.setter
    def max_tokens(self, max_tokens: int):
        """Sets the max_tokens of this AnimalConfigUpdate.

        Maximum response tokens (1-4096)  # noqa: E501

        :param max_tokens: The max_tokens of this AnimalConfigUpdate.
        :type max_tokens: int
        """
        if max_tokens is not None and max_tokens > 4096:  # noqa: E501
            raise ValueError("Invalid value for `max_tokens`, must be a value less than or equal to `4096`")  # noqa: E501
        if max_tokens is not None and max_tokens < 1:  # noqa: E501
            raise ValueError("Invalid value for `max_tokens`, must be a value greater than or equal to `1`")  # noqa: E501

        self._max_tokens = max_tokens

    @property
    def tools_enabled(self) -> list[str]:
        """Gets the tools_enabled of this AnimalConfigUpdate.

        Enabled tools (no duplicates allowed)  # noqa: E501

        :return: The tools_enabled of this AnimalConfigUpdate.
        :rtype: list[str]
        """
        return self._tools_enabled

    @tools_enabled.setter
    def tools_enabled(self, tools_enabled: list[str]):
        """Sets the tools_enabled of this AnimalConfigUpdate.

        Enabled tools (no duplicates allowed)  # noqa: E501

        :param tools_enabled: The tools_enabled of this AnimalConfigUpdate.
        :type tools_enabled: list[str]
        """
        allowed_values = ["facts", "media_lookup", "weather", "calculator", "web_search", "image_generation"]  # noqa: E501
        if not set(tools_enabled).issubset(set(allowed_values)):
            raise ValueError(
                "Invalid values for `tools_enabled` [{0}], must be a subset of [{1}]"  # noqa: E501
                .format(", ".join(map(str, set(tools_enabled) - set(allowed_values))),  # noqa: E501
                        ", ".join(map(str, allowed_values)))
            )

        self._tools_enabled = tools_enabled

    @property
    def response_format(self) -> str:
        """Gets the response_format of this AnimalConfigUpdate.

        Preferred response format  # noqa: E501

        :return: The response_format of this AnimalConfigUpdate.
        :rtype: str
        """
        return self._response_format

    @response_format.setter
    def response_format(self, response_format: str):
        """Sets the response_format of this AnimalConfigUpdate.

        Preferred response format  # noqa: E501

        :param response_format: The response_format of this AnimalConfigUpdate.
        :type response_format: str
        """
        allowed_values = ["text", "json", "markdown"]  # noqa: E501
        if response_format not in allowed_values:
            raise ValueError(
                "Invalid value for `response_format` ({0}), must be one of {1}"
                .format(response_format, allowed_values)
            )

        self._response_format = response_format

    @property
    def guardrails(self) -> AnimalConfigUpdateGuardrails:
        """Gets the guardrails of this AnimalConfigUpdate.


        :return: The guardrails of this AnimalConfigUpdate.
        :rtype: AnimalConfigUpdateGuardrails
        """
        return self._guardrails

    @guardrails.setter
    def guardrails(self, guardrails: AnimalConfigUpdateGuardrails):
        """Sets the guardrails of this AnimalConfigUpdate.


        :param guardrails: The guardrails of this AnimalConfigUpdate.
        :type guardrails: AnimalConfigUpdateGuardrails
        """

        self._guardrails = guardrails
