from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ApplyGuardrailTemplateRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, template_id=None, animal_id=None):  # noqa: E501
        """ApplyGuardrailTemplateRequest - a model defined in OpenAPI

        :param template_id: The template_id of this ApplyGuardrailTemplateRequest.  # noqa: E501
        :type template_id: str
        :param animal_id: The animal_id of this ApplyGuardrailTemplateRequest.  # noqa: E501
        :type animal_id: str
        """
        self.openapi_types = {
            'template_id': str,
            'animal_id': str
        }

        self.attribute_map = {
            'template_id': 'templateId',
            'animal_id': 'animalId'
        }

        self._template_id = template_id
        self._animal_id = animal_id

    @classmethod
    def from_dict(cls, dikt) -> 'ApplyGuardrailTemplateRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The applyGuardrailTemplate_request of this ApplyGuardrailTemplateRequest.  # noqa: E501
        :rtype: ApplyGuardrailTemplateRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def template_id(self) -> str:
        """Gets the template_id of this ApplyGuardrailTemplateRequest.

        ID of the template to apply  # noqa: E501

        :return: The template_id of this ApplyGuardrailTemplateRequest.
        :rtype: str
        """
        return self._template_id

    @template_id.setter
    def template_id(self, template_id: str):
        """Sets the template_id of this ApplyGuardrailTemplateRequest.

        ID of the template to apply  # noqa: E501

        :param template_id: The template_id of this ApplyGuardrailTemplateRequest.
        :type template_id: str
        """
        if template_id is None:
            raise ValueError("Invalid value for `template_id`, must not be `None`")  # noqa: E501

        self._template_id = template_id

    @property
    def animal_id(self) -> str:
        """Gets the animal_id of this ApplyGuardrailTemplateRequest.

        ID of the animal to apply template to  # noqa: E501

        :return: The animal_id of this ApplyGuardrailTemplateRequest.
        :rtype: str
        """
        return self._animal_id

    @animal_id.setter
    def animal_id(self, animal_id: str):
        """Sets the animal_id of this ApplyGuardrailTemplateRequest.

        ID of the animal to apply template to  # noqa: E501

        :param animal_id: The animal_id of this ApplyGuardrailTemplateRequest.
        :type animal_id: str
        """
        if animal_id is None:
            raise ValueError("Invalid value for `animal_id`, must not be `None`")  # noqa: E501

        self._animal_id = animal_id
