from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.assistant_response_last_prompt_merge import AssistantResponseLastPromptMerge
from openapi_server.models.audit_info import AuditInfo
from openapi_server import util

from openapi_server.models.assistant_response_last_prompt_merge import AssistantResponseLastPromptMerge  # noqa: E501
from openapi_server.models.audit_info import AuditInfo  # noqa: E501

class AssistantResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, assistant_id=None, animal_id=None, personality_id=None, guardrail_id=None, merged_prompt=None, knowledge_base_file_ids=None, status=None, last_prompt_merge=None, response_time_p95=None, created=None, modified=None):  # noqa: E501
        """AssistantResponse - a model defined in OpenAPI

        :param assistant_id: The assistant_id of this AssistantResponse.  # noqa: E501
        :type assistant_id: str
        :param animal_id: The animal_id of this AssistantResponse.  # noqa: E501
        :type animal_id: str
        :param personality_id: The personality_id of this AssistantResponse.  # noqa: E501
        :type personality_id: str
        :param guardrail_id: The guardrail_id of this AssistantResponse.  # noqa: E501
        :type guardrail_id: str
        :param merged_prompt: The merged_prompt of this AssistantResponse.  # noqa: E501
        :type merged_prompt: str
        :param knowledge_base_file_ids: The knowledge_base_file_ids of this AssistantResponse.  # noqa: E501
        :type knowledge_base_file_ids: List[str]
        :param status: The status of this AssistantResponse.  # noqa: E501
        :type status: str
        :param last_prompt_merge: The last_prompt_merge of this AssistantResponse.  # noqa: E501
        :type last_prompt_merge: AssistantResponseLastPromptMerge
        :param response_time_p95: The response_time_p95 of this AssistantResponse.  # noqa: E501
        :type response_time_p95: float
        :param created: The created of this AssistantResponse.  # noqa: E501
        :type created: AuditInfo
        :param modified: The modified of this AssistantResponse.  # noqa: E501
        :type modified: AuditInfo
        """
        self.openapi_types = {
            'assistant_id': str,
            'animal_id': str,
            'personality_id': str,
            'guardrail_id': str,
            'merged_prompt': str,
            'knowledge_base_file_ids': List[str],
            'status': str,
            'last_prompt_merge': AssistantResponseLastPromptMerge,
            'response_time_p95': float,
            'created': AuditInfo,
            'modified': AuditInfo
        }

        self.attribute_map = {
            'assistant_id': 'assistantId',
            'animal_id': 'animalId',
            'personality_id': 'personalityId',
            'guardrail_id': 'guardrailId',
            'merged_prompt': 'mergedPrompt',
            'knowledge_base_file_ids': 'knowledgeBaseFileIds',
            'status': 'status',
            'last_prompt_merge': 'lastPromptMerge',
            'response_time_p95': 'responseTimeP95',
            'created': 'created',
            'modified': 'modified'
        }

        self._assistant_id = assistant_id
        self._animal_id = animal_id
        self._personality_id = personality_id
        self._guardrail_id = guardrail_id
        self._merged_prompt = merged_prompt
        self._knowledge_base_file_ids = knowledge_base_file_ids
        self._status = status
        self._last_prompt_merge = last_prompt_merge
        self._response_time_p95 = response_time_p95
        self._created = created
        self._modified = modified

    @classmethod
    def from_dict(cls, dikt) -> 'AssistantResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AssistantResponse of this AssistantResponse.  # noqa: E501
        :rtype: AssistantResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def assistant_id(self) -> str:
        """Gets the assistant_id of this AssistantResponse.


        :return: The assistant_id of this AssistantResponse.
        :rtype: str
        """
        return self._assistant_id

    @assistant_id.setter
    def assistant_id(self, assistant_id: str):
        """Sets the assistant_id of this AssistantResponse.


        :param assistant_id: The assistant_id of this AssistantResponse.
        :type assistant_id: str
        """

        self._assistant_id = assistant_id

    @property
    def animal_id(self) -> str:
        """Gets the animal_id of this AssistantResponse.


        :return: The animal_id of this AssistantResponse.
        :rtype: str
        """
        return self._animal_id

    @animal_id.setter
    def animal_id(self, animal_id: str):
        """Sets the animal_id of this AssistantResponse.


        :param animal_id: The animal_id of this AssistantResponse.
        :type animal_id: str
        """

        self._animal_id = animal_id

    @property
    def personality_id(self) -> str:
        """Gets the personality_id of this AssistantResponse.


        :return: The personality_id of this AssistantResponse.
        :rtype: str
        """
        return self._personality_id

    @personality_id.setter
    def personality_id(self, personality_id: str):
        """Sets the personality_id of this AssistantResponse.


        :param personality_id: The personality_id of this AssistantResponse.
        :type personality_id: str
        """

        self._personality_id = personality_id

    @property
    def guardrail_id(self) -> str:
        """Gets the guardrail_id of this AssistantResponse.


        :return: The guardrail_id of this AssistantResponse.
        :rtype: str
        """
        return self._guardrail_id

    @guardrail_id.setter
    def guardrail_id(self, guardrail_id: str):
        """Sets the guardrail_id of this AssistantResponse.


        :param guardrail_id: The guardrail_id of this AssistantResponse.
        :type guardrail_id: str
        """

        self._guardrail_id = guardrail_id

    @property
    def merged_prompt(self) -> str:
        """Gets the merged_prompt of this AssistantResponse.

        Combined personality and guardrail prompt  # noqa: E501

        :return: The merged_prompt of this AssistantResponse.
        :rtype: str
        """
        return self._merged_prompt

    @merged_prompt.setter
    def merged_prompt(self, merged_prompt: str):
        """Sets the merged_prompt of this AssistantResponse.

        Combined personality and guardrail prompt  # noqa: E501

        :param merged_prompt: The merged_prompt of this AssistantResponse.
        :type merged_prompt: str
        """

        self._merged_prompt = merged_prompt

    @property
    def knowledge_base_file_ids(self) -> List[str]:
        """Gets the knowledge_base_file_ids of this AssistantResponse.


        :return: The knowledge_base_file_ids of this AssistantResponse.
        :rtype: List[str]
        """
        return self._knowledge_base_file_ids

    @knowledge_base_file_ids.setter
    def knowledge_base_file_ids(self, knowledge_base_file_ids: List[str]):
        """Sets the knowledge_base_file_ids of this AssistantResponse.


        :param knowledge_base_file_ids: The knowledge_base_file_ids of this AssistantResponse.
        :type knowledge_base_file_ids: List[str]
        """

        self._knowledge_base_file_ids = knowledge_base_file_ids

    @property
    def status(self) -> str:
        """Gets the status of this AssistantResponse.


        :return: The status of this AssistantResponse.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this AssistantResponse.


        :param status: The status of this AssistantResponse.
        :type status: str
        """
        allowed_values = ["ACTIVE", "INACTIVE", "ERROR"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def last_prompt_merge(self) -> AssistantResponseLastPromptMerge:
        """Gets the last_prompt_merge of this AssistantResponse.


        :return: The last_prompt_merge of this AssistantResponse.
        :rtype: AssistantResponseLastPromptMerge
        """
        return self._last_prompt_merge

    @last_prompt_merge.setter
    def last_prompt_merge(self, last_prompt_merge: AssistantResponseLastPromptMerge):
        """Sets the last_prompt_merge of this AssistantResponse.


        :param last_prompt_merge: The last_prompt_merge of this AssistantResponse.
        :type last_prompt_merge: AssistantResponseLastPromptMerge
        """

        self._last_prompt_merge = last_prompt_merge

    @property
    def response_time_p95(self) -> float:
        """Gets the response_time_p95 of this AssistantResponse.

        95th percentile response time in milliseconds  # noqa: E501

        :return: The response_time_p95 of this AssistantResponse.
        :rtype: float
        """
        return self._response_time_p95

    @response_time_p95.setter
    def response_time_p95(self, response_time_p95: float):
        """Sets the response_time_p95 of this AssistantResponse.

        95th percentile response time in milliseconds  # noqa: E501

        :param response_time_p95: The response_time_p95 of this AssistantResponse.
        :type response_time_p95: float
        """

        self._response_time_p95 = response_time_p95

    @property
    def created(self) -> AuditInfo:
        """Gets the created of this AssistantResponse.


        :return: The created of this AssistantResponse.
        :rtype: AuditInfo
        """
        return self._created

    @created.setter
    def created(self, created: AuditInfo):
        """Sets the created of this AssistantResponse.


        :param created: The created of this AssistantResponse.
        :type created: AuditInfo
        """

        self._created = created

    @property
    def modified(self) -> AuditInfo:
        """Gets the modified of this AssistantResponse.


        :return: The modified of this AssistantResponse.
        :rtype: AuditInfo
        """
        return self._modified

    @modified.setter
    def modified(self, modified: AuditInfo):
        """Sets the modified of this AssistantResponse.


        :param modified: The modified of this AssistantResponse.
        :type modified: AuditInfo
        """

        self._modified = modified
