from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class AuditInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, at=None, by=None):  # noqa: E501
        """AuditInfo - a model defined in OpenAPI

        :param at: The at of this AuditInfo.  # noqa: E501
        :type at: datetime
        :param by: The by of this AuditInfo.  # noqa: E501
        :type by: str
        """
        self.openapi_types = {
            'at': datetime,
            'by': str
        }

        self.attribute_map = {
            'at': 'at',
            'by': 'by'
        }

        self._at = at
        self._by = by

    @classmethod
    def from_dict(cls, dikt) -> 'AuditInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AuditInfo of this AuditInfo.  # noqa: E501
        :rtype: AuditInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def at(self) -> datetime:
        """Gets the at of this AuditInfo.


        :return: The at of this AuditInfo.
        :rtype: datetime
        """
        return self._at

    @at.setter
    def at(self, at: datetime):
        """Sets the at of this AuditInfo.


        :param at: The at of this AuditInfo.
        :type at: datetime
        """

        self._at = at

    @property
    def by(self) -> str:
        """Gets the by of this AuditInfo.

        User ID who performed the action  # noqa: E501

        :return: The by of this AuditInfo.
        :rtype: str
        """
        return self._by

    @by.setter
    def by(self, by: str):
        """Sets the by of this AuditInfo.

        User ID who performed the action  # noqa: E501

        :param by: The by of this AuditInfo.
        :type by: str
        """

        self._by = by
