from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class AuthRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, username=None, password=None, register=None):  # noqa: E501
        """AuthRequest - a model defined in OpenAPI

        :param username: The username of this AuthRequest.  # noqa: E501
        :type username: str
        :param password: The password of this AuthRequest.  # noqa: E501
        :type password: str
        :param register: The register of this AuthRequest.  # noqa: E501
        :type register: bool
        """
        self.openapi_types = {
            'username': str,
            'password': str,
            'register': bool
        }

        self.attribute_map = {
            'username': 'username',
            'password': 'password',
            'register': 'register'
        }

        self._username = username
        self._password = password
        self._register = register

    @classmethod
    def from_dict(cls, dikt) -> 'AuthRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AuthRequest of this AuthRequest.  # noqa: E501
        :rtype: AuthRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self) -> str:
        """Gets the username of this AuthRequest.


        :return: The username of this AuthRequest.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this AuthRequest.


        :param username: The username of this AuthRequest.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def password(self) -> str:
        """Gets the password of this AuthRequest.


        :return: The password of this AuthRequest.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this AuthRequest.


        :param password: The password of this AuthRequest.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def register(self) -> bool:
        """Gets the register of this AuthRequest.

        If true, create account if not found  # noqa: E501

        :return: The register of this AuthRequest.
        :rtype: bool
        """
        return self._register

    @register.setter
    def register(self, register: bool):
        """Sets the register of this AuthRequest.

        If true, create account if not found  # noqa: E501

        :param register: The register of this AuthRequest.
        :type register: bool
        """

        self._register = register
