from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.user import User
from openapi_server import util

from openapi_server.models.user import User  # noqa: E501

class AuthResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, token=None, expires_in=None, user=None):  # noqa: E501
        """AuthResponse - a model defined in OpenAPI

        :param token: The token of this AuthResponse.  # noqa: E501
        :type token: str
        :param expires_in: The expires_in of this AuthResponse.  # noqa: E501
        :type expires_in: int
        :param user: The user of this AuthResponse.  # noqa: E501
        :type user: User
        """
        self.openapi_types = {
            'token': str,
            'expires_in': int,
            'user': User
        }

        self.attribute_map = {
            'token': 'token',
            'expires_in': 'expiresIn',
            'user': 'user'
        }

        self._token = token
        self._expires_in = expires_in
        self._user = user

    @classmethod
    def from_dict(cls, dikt) -> 'AuthResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AuthResponse of this AuthResponse.  # noqa: E501
        :rtype: AuthResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self) -> str:
        """Gets the token of this AuthResponse.


        :return: The token of this AuthResponse.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this AuthResponse.


        :param token: The token of this AuthResponse.
        :type token: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    @property
    def expires_in(self) -> int:
        """Gets the expires_in of this AuthResponse.

        Seconds until expiry  # noqa: E501

        :return: The expires_in of this AuthResponse.
        :rtype: int
        """
        return self._expires_in

    @expires_in.setter
    def expires_in(self, expires_in: int):
        """Sets the expires_in of this AuthResponse.

        Seconds until expiry  # noqa: E501

        :param expires_in: The expires_in of this AuthResponse.
        :type expires_in: int
        """
        if expires_in is None:
            raise ValueError("Invalid value for `expires_in`, must not be `None`")  # noqa: E501

        self._expires_in = expires_in

    @property
    def user(self) -> User:
        """Gets the user of this AuthResponse.


        :return: The user of this AuthResponse.
        :rtype: User
        """
        return self._user

    @user.setter
    def user(self, user: User):
        """Sets the user of this AuthResponse.


        :param user: The user of this AuthResponse.
        :type user: User
        """
        if user is None:
            raise ValueError("Invalid value for `user`, must not be `None`")  # noqa: E501

        self._user = user
