from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class BillingSummaryByServiceInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, service=None, usd=None):  # noqa: E501
        """BillingSummaryByServiceInner - a model defined in OpenAPI

        :param service: The service of this BillingSummaryByServiceInner.  # noqa: E501
        :type service: str
        :param usd: The usd of this BillingSummaryByServiceInner.  # noqa: E501
        :type usd: float
        """
        self.openapi_types = {
            'service': str,
            'usd': float
        }

        self.attribute_map = {
            'service': 'service',
            'usd': 'usd'
        }

        self._service = service
        self._usd = usd

    @classmethod
    def from_dict(cls, dikt) -> 'BillingSummaryByServiceInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BillingSummary_byService_inner of this BillingSummaryByServiceInner.  # noqa: E501
        :rtype: BillingSummaryByServiceInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def service(self) -> str:
        """Gets the service of this BillingSummaryByServiceInner.


        :return: The service of this BillingSummaryByServiceInner.
        :rtype: str
        """
        return self._service

    @service.setter
    def service(self, service: str):
        """Sets the service of this BillingSummaryByServiceInner.


        :param service: The service of this BillingSummaryByServiceInner.
        :type service: str
        """

        self._service = service

    @property
    def usd(self) -> float:
        """Gets the usd of this BillingSummaryByServiceInner.


        :return: The usd of this BillingSummaryByServiceInner.
        :rtype: float
        """
        return self._usd

    @usd.setter
    def usd(self, usd: float):
        """Sets the usd of this BillingSummaryByServiceInner.


        :param usd: The usd of this BillingSummaryByServiceInner.
        :type usd: float
        """

        self._usd = usd
