from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ChatRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message=None, conversation_id=None):  # noqa: E501
        """ChatRequest - a model defined in OpenAPI

        :param message: The message of this ChatRequest.  # noqa: E501
        :type message: str
        :param conversation_id: The conversation_id of this ChatRequest.  # noqa: E501
        :type conversation_id: str
        """
        self.openapi_types = {
            'message': str,
            'conversation_id': str
        }

        self.attribute_map = {
            'message': 'message',
            'conversation_id': 'conversationId'
        }

        self._message = message
        self._conversation_id = conversation_id

    @classmethod
    def from_dict(cls, dikt) -> 'ChatRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ChatRequest of this ChatRequest.  # noqa: E501
        :rtype: ChatRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this ChatRequest.

        User's chat message  # noqa: E501

        :return: The message of this ChatRequest.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ChatRequest.

        User's chat message  # noqa: E501

        :param message: The message of this ChatRequest.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501
        if message is not None and len(message) > 1000:
            raise ValueError("Invalid value for `message`, length must be less than or equal to `1000`")  # noqa: E501
        if message is not None and len(message) < 1:
            raise ValueError("Invalid value for `message`, length must be greater than or equal to `1`")  # noqa: E501

        self._message = message

    @property
    def conversation_id(self) -> str:
        """Gets the conversation_id of this ChatRequest.

        Optional conversation ID for context  # noqa: E501

        :return: The conversation_id of this ChatRequest.
        :rtype: str
        """
        return self._conversation_id

    @conversation_id.setter
    def conversation_id(self, conversation_id: str):
        """Sets the conversation_id of this ChatRequest.

        Optional conversation ID for context  # noqa: E501

        :param conversation_id: The conversation_id of this ChatRequest.
        :type conversation_id: str
        """

        self._conversation_id = conversation_id
