from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ChatResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, response=None, conversation_id=None, response_time=None, prompt_tokens=None, completion_tokens=None):  # noqa: E501
        """ChatResponse - a model defined in OpenAPI

        :param response: The response of this ChatResponse.  # noqa: E501
        :type response: str
        :param conversation_id: The conversation_id of this ChatResponse.  # noqa: E501
        :type conversation_id: str
        :param response_time: The response_time of this ChatResponse.  # noqa: E501
        :type response_time: float
        :param prompt_tokens: The prompt_tokens of this ChatResponse.  # noqa: E501
        :type prompt_tokens: int
        :param completion_tokens: The completion_tokens of this ChatResponse.  # noqa: E501
        :type completion_tokens: int
        """
        self.openapi_types = {
            'response': str,
            'conversation_id': str,
            'response_time': float,
            'prompt_tokens': int,
            'completion_tokens': int
        }

        self.attribute_map = {
            'response': 'response',
            'conversation_id': 'conversationId',
            'response_time': 'responseTime',
            'prompt_tokens': 'promptTokens',
            'completion_tokens': 'completionTokens'
        }

        self._response = response
        self._conversation_id = conversation_id
        self._response_time = response_time
        self._prompt_tokens = prompt_tokens
        self._completion_tokens = completion_tokens

    @classmethod
    def from_dict(cls, dikt) -> 'ChatResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ChatResponse of this ChatResponse.  # noqa: E501
        :rtype: ChatResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def response(self) -> str:
        """Gets the response of this ChatResponse.

        Assistant's response  # noqa: E501

        :return: The response of this ChatResponse.
        :rtype: str
        """
        return self._response

    @response.setter
    def response(self, response: str):
        """Sets the response of this ChatResponse.

        Assistant's response  # noqa: E501

        :param response: The response of this ChatResponse.
        :type response: str
        """

        self._response = response

    @property
    def conversation_id(self) -> str:
        """Gets the conversation_id of this ChatResponse.

        Conversation ID for follow-up messages  # noqa: E501

        :return: The conversation_id of this ChatResponse.
        :rtype: str
        """
        return self._conversation_id

    @conversation_id.setter
    def conversation_id(self, conversation_id: str):
        """Sets the conversation_id of this ChatResponse.

        Conversation ID for follow-up messages  # noqa: E501

        :param conversation_id: The conversation_id of this ChatResponse.
        :type conversation_id: str
        """

        self._conversation_id = conversation_id

    @property
    def response_time(self) -> float:
        """Gets the response_time of this ChatResponse.

        Response time in milliseconds  # noqa: E501

        :return: The response_time of this ChatResponse.
        :rtype: float
        """
        return self._response_time

    @response_time.setter
    def response_time(self, response_time: float):
        """Sets the response_time of this ChatResponse.

        Response time in milliseconds  # noqa: E501

        :param response_time: The response_time of this ChatResponse.
        :type response_time: float
        """

        self._response_time = response_time

    @property
    def prompt_tokens(self) -> int:
        """Gets the prompt_tokens of this ChatResponse.

        Tokens used in prompt  # noqa: E501

        :return: The prompt_tokens of this ChatResponse.
        :rtype: int
        """
        return self._prompt_tokens

    @prompt_tokens.setter
    def prompt_tokens(self, prompt_tokens: int):
        """Sets the prompt_tokens of this ChatResponse.

        Tokens used in prompt  # noqa: E501

        :param prompt_tokens: The prompt_tokens of this ChatResponse.
        :type prompt_tokens: int
        """

        self._prompt_tokens = prompt_tokens

    @property
    def completion_tokens(self) -> int:
        """Gets the completion_tokens of this ChatResponse.

        Tokens used in completion  # noqa: E501

        :return: The completion_tokens of this ChatResponse.
        :rtype: int
        """
        return self._completion_tokens

    @completion_tokens.setter
    def completion_tokens(self, completion_tokens: int):
        """Sets the completion_tokens of this ChatResponse.

        Tokens used in completion  # noqa: E501

        :param completion_tokens: The completion_tokens of this ChatResponse.
        :type completion_tokens: int
        """

        self._completion_tokens = completion_tokens
