from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ContextSummaryPostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, force_summarization=False, target_tokens=800, preserve_recent=3):  # noqa: E501
        """ContextSummaryPostRequest - a model defined in OpenAPI

        :param force_summarization: The force_summarization of this ContextSummaryPostRequest.  # noqa: E501
        :type force_summarization: bool
        :param target_tokens: The target_tokens of this ContextSummaryPostRequest.  # noqa: E501
        :type target_tokens: int
        :param preserve_recent: The preserve_recent of this ContextSummaryPostRequest.  # noqa: E501
        :type preserve_recent: int
        """
        self.openapi_types = {
            'force_summarization': bool,
            'target_tokens': int,
            'preserve_recent': int
        }

        self.attribute_map = {
            'force_summarization': 'forceSummarization',
            'target_tokens': 'targetTokens',
            'preserve_recent': 'preserveRecent'
        }

        self._force_summarization = force_summarization
        self._target_tokens = target_tokens
        self._preserve_recent = preserve_recent

    @classmethod
    def from_dict(cls, dikt) -> 'ContextSummaryPostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The context_summary_post_request of this ContextSummaryPostRequest.  # noqa: E501
        :rtype: ContextSummaryPostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def force_summarization(self) -> bool:
        """Gets the force_summarization of this ContextSummaryPostRequest.

        Force summarization even if not triggered by conversation count  # noqa: E501

        :return: The force_summarization of this ContextSummaryPostRequest.
        :rtype: bool
        """
        return self._force_summarization

    @force_summarization.setter
    def force_summarization(self, force_summarization: bool):
        """Sets the force_summarization of this ContextSummaryPostRequest.

        Force summarization even if not triggered by conversation count  # noqa: E501

        :param force_summarization: The force_summarization of this ContextSummaryPostRequest.
        :type force_summarization: bool
        """

        self._force_summarization = force_summarization

    @property
    def target_tokens(self) -> int:
        """Gets the target_tokens of this ContextSummaryPostRequest.

        Target token count for summary  # noqa: E501

        :return: The target_tokens of this ContextSummaryPostRequest.
        :rtype: int
        """
        return self._target_tokens

    @target_tokens.setter
    def target_tokens(self, target_tokens: int):
        """Sets the target_tokens of this ContextSummaryPostRequest.

        Target token count for summary  # noqa: E501

        :param target_tokens: The target_tokens of this ContextSummaryPostRequest.
        :type target_tokens: int
        """
        if target_tokens is not None and target_tokens > 2000:  # noqa: E501
            raise ValueError("Invalid value for `target_tokens`, must be a value less than or equal to `2000`")  # noqa: E501
        if target_tokens is not None and target_tokens < 100:  # noqa: E501
            raise ValueError("Invalid value for `target_tokens`, must be a value greater than or equal to `100`")  # noqa: E501

        self._target_tokens = target_tokens

    @property
    def preserve_recent(self) -> int:
        """Gets the preserve_recent of this ContextSummaryPostRequest.

        Number of recent conversations to preserve unsummarized  # noqa: E501

        :return: The preserve_recent of this ContextSummaryPostRequest.
        :rtype: int
        """
        return self._preserve_recent

    @preserve_recent.setter
    def preserve_recent(self, preserve_recent: int):
        """Sets the preserve_recent of this ContextSummaryPostRequest.

        Number of recent conversations to preserve unsummarized  # noqa: E501

        :param preserve_recent: The preserve_recent of this ContextSummaryPostRequest.
        :type preserve_recent: int
        """
        if preserve_recent is not None and preserve_recent > 10:  # noqa: E501
            raise ValueError("Invalid value for `preserve_recent`, must be a value less than or equal to `10`")  # noqa: E501
        if preserve_recent is not None and preserve_recent < 1:  # noqa: E501
            raise ValueError("Invalid value for `preserve_recent`, must be a value greater than or equal to `1`")  # noqa: E501

        self._preserve_recent = preserve_recent
