from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ContextSummaryPost200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, summary_id=None, tokens_reduced=None, quality_score=None):  # noqa: E501
        """ContextSummaryPost200Response - a model defined in OpenAPI

        :param summary_id: The summary_id of this ContextSummaryPost200Response.  # noqa: E501
        :type summary_id: str
        :param tokens_reduced: The tokens_reduced of this ContextSummaryPost200Response.  # noqa: E501
        :type tokens_reduced: int
        :param quality_score: The quality_score of this ContextSummaryPost200Response.  # noqa: E501
        :type quality_score: float
        """
        self.openapi_types = {
            'summary_id': str,
            'tokens_reduced': int,
            'quality_score': float
        }

        self.attribute_map = {
            'summary_id': 'summaryId',
            'tokens_reduced': 'tokensReduced',
            'quality_score': 'qualityScore'
        }

        self._summary_id = summary_id
        self._tokens_reduced = tokens_reduced
        self._quality_score = quality_score

    @classmethod
    def from_dict(cls, dikt) -> 'ContextSummaryPost200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The context_summary_post_200_response of this ContextSummaryPost200Response.  # noqa: E501
        :rtype: ContextSummaryPost200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def summary_id(self) -> str:
        """Gets the summary_id of this ContextSummaryPost200Response.


        :return: The summary_id of this ContextSummaryPost200Response.
        :rtype: str
        """
        return self._summary_id

    @summary_id.setter
    def summary_id(self, summary_id: str):
        """Sets the summary_id of this ContextSummaryPost200Response.


        :param summary_id: The summary_id of this ContextSummaryPost200Response.
        :type summary_id: str
        """

        self._summary_id = summary_id

    @property
    def tokens_reduced(self) -> int:
        """Gets the tokens_reduced of this ContextSummaryPost200Response.


        :return: The tokens_reduced of this ContextSummaryPost200Response.
        :rtype: int
        """
        return self._tokens_reduced

    @tokens_reduced.setter
    def tokens_reduced(self, tokens_reduced: int):
        """Sets the tokens_reduced of this ContextSummaryPost200Response.


        :param tokens_reduced: The tokens_reduced of this ContextSummaryPost200Response.
        :type tokens_reduced: int
        """

        self._tokens_reduced = tokens_reduced

    @property
    def quality_score(self) -> float:
        """Gets the quality_score of this ContextSummaryPost200Response.


        :return: The quality_score of this ContextSummaryPost200Response.
        :rtype: float
        """
        return self._quality_score

    @quality_score.setter
    def quality_score(self, quality_score: float):
        """Sets the quality_score of this ContextSummaryPost200Response.


        :param quality_score: The quality_score of this ContextSummaryPost200Response.
        :type quality_score: float
        """
        if quality_score is not None and quality_score > 1:  # noqa: E501
            raise ValueError("Invalid value for `quality_score`, must be a value less than or equal to `1`")  # noqa: E501
        if quality_score is not None and quality_score < 0:  # noqa: E501
            raise ValueError("Invalid value for `quality_score`, must be a value greater than or equal to `0`")  # noqa: E501

        self._quality_score = quality_score
