from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ConvoTurnPost200ResponseAllOfRateLimit(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, remaining=None, reset_time=None, daily_usage=None):  # noqa: E501
        """ConvoTurnPost200ResponseAllOfRateLimit - a model defined in OpenAPI

        :param remaining: The remaining of this ConvoTurnPost200ResponseAllOfRateLimit.  # noqa: E501
        :type remaining: int
        :param reset_time: The reset_time of this ConvoTurnPost200ResponseAllOfRateLimit.  # noqa: E501
        :type reset_time: datetime
        :param daily_usage: The daily_usage of this ConvoTurnPost200ResponseAllOfRateLimit.  # noqa: E501
        :type daily_usage: int
        """
        self.openapi_types = {
            'remaining': int,
            'reset_time': datetime,
            'daily_usage': int
        }

        self.attribute_map = {
            'remaining': 'remaining',
            'reset_time': 'resetTime',
            'daily_usage': 'dailyUsage'
        }

        self._remaining = remaining
        self._reset_time = reset_time
        self._daily_usage = daily_usage

    @classmethod
    def from_dict(cls, dikt) -> 'ConvoTurnPost200ResponseAllOfRateLimit':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The convo_turn_post_200_response_allOf_rateLimit of this ConvoTurnPost200ResponseAllOfRateLimit.  # noqa: E501
        :rtype: ConvoTurnPost200ResponseAllOfRateLimit
        """
        return util.deserialize_model(dikt, cls)

    @property
    def remaining(self) -> int:
        """Gets the remaining of this ConvoTurnPost200ResponseAllOfRateLimit.

        Remaining API calls in current window  # noqa: E501

        :return: The remaining of this ConvoTurnPost200ResponseAllOfRateLimit.
        :rtype: int
        """
        return self._remaining

    @remaining.setter
    def remaining(self, remaining: int):
        """Sets the remaining of this ConvoTurnPost200ResponseAllOfRateLimit.

        Remaining API calls in current window  # noqa: E501

        :param remaining: The remaining of this ConvoTurnPost200ResponseAllOfRateLimit.
        :type remaining: int
        """

        self._remaining = remaining

    @property
    def reset_time(self) -> datetime:
        """Gets the reset_time of this ConvoTurnPost200ResponseAllOfRateLimit.

        When rate limit resets  # noqa: E501

        :return: The reset_time of this ConvoTurnPost200ResponseAllOfRateLimit.
        :rtype: datetime
        """
        return self._reset_time

    @reset_time.setter
    def reset_time(self, reset_time: datetime):
        """Sets the reset_time of this ConvoTurnPost200ResponseAllOfRateLimit.

        When rate limit resets  # noqa: E501

        :param reset_time: The reset_time of this ConvoTurnPost200ResponseAllOfRateLimit.
        :type reset_time: datetime
        """

        self._reset_time = reset_time

    @property
    def daily_usage(self) -> int:
        """Gets the daily_usage of this ConvoTurnPost200ResponseAllOfRateLimit.

        Total API calls used today  # noqa: E501

        :return: The daily_usage of this ConvoTurnPost200ResponseAllOfRateLimit.
        :rtype: int
        """
        return self._daily_usage

    @daily_usage.setter
    def daily_usage(self, daily_usage: int):
        """Sets the daily_usage of this ConvoTurnPost200ResponseAllOfRateLimit.

        Total API calls used today  # noqa: E501

        :param daily_usage: The daily_usage of this ConvoTurnPost200ResponseAllOfRateLimit.
        :type daily_usage: int
        """

        self._daily_usage = daily_usage
