from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ConvoTurnRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, animal_id=None, message=None, session_id=None, context_summary=None, metadata=None):  # noqa: E501
        """ConvoTurnRequest - a model defined in OpenAPI

        :param animal_id: The animal_id of this ConvoTurnRequest.  # noqa: E501
        :type animal_id: str
        :param message: The message of this ConvoTurnRequest.  # noqa: E501
        :type message: str
        :param session_id: The session_id of this ConvoTurnRequest.  # noqa: E501
        :type session_id: str
        :param context_summary: The context_summary of this ConvoTurnRequest.  # noqa: E501
        :type context_summary: str
        :param metadata: The metadata of this ConvoTurnRequest.  # noqa: E501
        :type metadata: Dict[str, object]
        """
        self.openapi_types = {
            'animal_id': str,
            'message': str,
            'session_id': str,
            'context_summary': str,
            'metadata': Dict[str, object]
        }

        self.attribute_map = {
            'animal_id': 'animalId',
            'message': 'message',
            'session_id': 'sessionId',
            'context_summary': 'contextSummary',
            'metadata': 'metadata'
        }

        self._animal_id = animal_id
        self._message = message
        self._session_id = session_id
        self._context_summary = context_summary
        self._metadata = metadata

    @classmethod
    def from_dict(cls, dikt) -> 'ConvoTurnRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ConvoTurnRequest of this ConvoTurnRequest.  # noqa: E501
        :rtype: ConvoTurnRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def animal_id(self) -> str:
        """Gets the animal_id of this ConvoTurnRequest.


        :return: The animal_id of this ConvoTurnRequest.
        :rtype: str
        """
        return self._animal_id

    @animal_id.setter
    def animal_id(self, animal_id: str):
        """Sets the animal_id of this ConvoTurnRequest.


        :param animal_id: The animal_id of this ConvoTurnRequest.
        :type animal_id: str
        """
        if animal_id is None:
            raise ValueError("Invalid value for `animal_id`, must not be `None`")  # noqa: E501

        self._animal_id = animal_id

    @property
    def message(self) -> str:
        """Gets the message of this ConvoTurnRequest.


        :return: The message of this ConvoTurnRequest.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ConvoTurnRequest.


        :param message: The message of this ConvoTurnRequest.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def session_id(self) -> str:
        """Gets the session_id of this ConvoTurnRequest.


        :return: The session_id of this ConvoTurnRequest.
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id: str):
        """Sets the session_id of this ConvoTurnRequest.


        :param session_id: The session_id of this ConvoTurnRequest.
        :type session_id: str
        """

        self._session_id = session_id

    @property
    def context_summary(self) -> str:
        """Gets the context_summary of this ConvoTurnRequest.


        :return: The context_summary of this ConvoTurnRequest.
        :rtype: str
        """
        return self._context_summary

    @context_summary.setter
    def context_summary(self, context_summary: str):
        """Sets the context_summary of this ConvoTurnRequest.


        :param context_summary: The context_summary of this ConvoTurnRequest.
        :type context_summary: str
        """

        self._context_summary = context_summary

    @property
    def metadata(self) -> Dict[str, object]:
        """Gets the metadata of this ConvoTurnRequest.


        :return: The metadata of this ConvoTurnRequest.
        :rtype: Dict[str, object]
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: Dict[str, object]):
        """Sets the metadata of this ConvoTurnRequest.


        :param metadata: The metadata of this ConvoTurnRequest.
        :type metadata: Dict[str, object]
        """

        self._metadata = metadata
