from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class CreateGuardrailRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, description=None, guardrail_text=None, category=None, severity=None, age_appropriate=None, is_default=None):  # noqa: E501
        """CreateGuardrailRequest - a model defined in OpenAPI

        :param name: The name of this CreateGuardrailRequest.  # noqa: E501
        :type name: str
        :param description: The description of this CreateGuardrailRequest.  # noqa: E501
        :type description: str
        :param guardrail_text: The guardrail_text of this CreateGuardrailRequest.  # noqa: E501
        :type guardrail_text: str
        :param category: The category of this CreateGuardrailRequest.  # noqa: E501
        :type category: str
        :param severity: The severity of this CreateGuardrailRequest.  # noqa: E501
        :type severity: str
        :param age_appropriate: The age_appropriate of this CreateGuardrailRequest.  # noqa: E501
        :type age_appropriate: List[str]
        :param is_default: The is_default of this CreateGuardrailRequest.  # noqa: E501
        :type is_default: bool
        """
        self.openapi_types = {
            'name': str,
            'description': str,
            'guardrail_text': str,
            'category': str,
            'severity': str,
            'age_appropriate': List[str],
            'is_default': bool
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description',
            'guardrail_text': 'guardrailText',
            'category': 'category',
            'severity': 'severity',
            'age_appropriate': 'ageAppropriate',
            'is_default': 'isDefault'
        }

        self._name = name
        self._description = description
        self._guardrail_text = guardrail_text
        self._category = category
        self._severity = severity
        self._age_appropriate = age_appropriate
        self._is_default = is_default

    @classmethod
    def from_dict(cls, dikt) -> 'CreateGuardrailRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateGuardrailRequest of this CreateGuardrailRequest.  # noqa: E501
        :rtype: CreateGuardrailRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this CreateGuardrailRequest.

        Human-readable guardrail name  # noqa: E501

        :return: The name of this CreateGuardrailRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this CreateGuardrailRequest.

        Human-readable guardrail name  # noqa: E501

        :param name: The name of this CreateGuardrailRequest.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) > 100:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `100`")  # noqa: E501
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this CreateGuardrailRequest.

        Purpose and scope description  # noqa: E501

        :return: The description of this CreateGuardrailRequest.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this CreateGuardrailRequest.

        Purpose and scope description  # noqa: E501

        :param description: The description of this CreateGuardrailRequest.
        :type description: str
        """
        if description is not None and len(description) > 500:
            raise ValueError("Invalid value for `description`, length must be less than or equal to `500`")  # noqa: E501

        self._description = description

    @property
    def guardrail_text(self) -> str:
        """Gets the guardrail_text of this CreateGuardrailRequest.

        Safety rules as text prompts  # noqa: E501

        :return: The guardrail_text of this CreateGuardrailRequest.
        :rtype: str
        """
        return self._guardrail_text

    @guardrail_text.setter
    def guardrail_text(self, guardrail_text: str):
        """Sets the guardrail_text of this CreateGuardrailRequest.

        Safety rules as text prompts  # noqa: E501

        :param guardrail_text: The guardrail_text of this CreateGuardrailRequest.
        :type guardrail_text: str
        """
        if guardrail_text is None:
            raise ValueError("Invalid value for `guardrail_text`, must not be `None`")  # noqa: E501
        if guardrail_text is not None and len(guardrail_text) > 2000:
            raise ValueError("Invalid value for `guardrail_text`, length must be less than or equal to `2000`")  # noqa: E501
        if guardrail_text is not None and len(guardrail_text) < 50:
            raise ValueError("Invalid value for `guardrail_text`, length must be greater than or equal to `50`")  # noqa: E501

        self._guardrail_text = guardrail_text

    @property
    def category(self) -> str:
        """Gets the category of this CreateGuardrailRequest.

        Guardrail category  # noqa: E501

        :return: The category of this CreateGuardrailRequest.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category: str):
        """Sets the category of this CreateGuardrailRequest.

        Guardrail category  # noqa: E501

        :param category: The category of this CreateGuardrailRequest.
        :type category: str
        """
        allowed_values = ["SAFETY", "EDUCATION", "TONE", "CONTENT"]  # noqa: E501
        if category not in allowed_values:
            raise ValueError(
                "Invalid value for `category` ({0}), must be one of {1}"
                .format(category, allowed_values)
            )

        self._category = category

    @property
    def severity(self) -> str:
        """Gets the severity of this CreateGuardrailRequest.

        Enforcement level  # noqa: E501

        :return: The severity of this CreateGuardrailRequest.
        :rtype: str
        """
        return self._severity

    @severity.setter
    def severity(self, severity: str):
        """Sets the severity of this CreateGuardrailRequest.

        Enforcement level  # noqa: E501

        :param severity: The severity of this CreateGuardrailRequest.
        :type severity: str
        """
        allowed_values = ["STRICT", "MODERATE", "GUIDANCE"]  # noqa: E501
        if severity not in allowed_values:
            raise ValueError(
                "Invalid value for `severity` ({0}), must be one of {1}"
                .format(severity, allowed_values)
            )

        self._severity = severity

    @property
    def age_appropriate(self) -> List[str]:
        """Gets the age_appropriate of this CreateGuardrailRequest.

        Target age groups  # noqa: E501

        :return: The age_appropriate of this CreateGuardrailRequest.
        :rtype: List[str]
        """
        return self._age_appropriate

    @age_appropriate.setter
    def age_appropriate(self, age_appropriate: List[str]):
        """Sets the age_appropriate of this CreateGuardrailRequest.

        Target age groups  # noqa: E501

        :param age_appropriate: The age_appropriate of this CreateGuardrailRequest.
        :type age_appropriate: List[str]
        """
        allowed_values = ["PRESCHOOL", "ELEMENTARY", "FAMILY", "ALL_AGES"]  # noqa: E501
        if not set(age_appropriate).issubset(set(allowed_values)):
            raise ValueError(
                "Invalid values for `age_appropriate` [{0}], must be a subset of [{1}]"  # noqa: E501
                .format(", ".join(map(str, set(age_appropriate) - set(allowed_values))),  # noqa: E501
                        ", ".join(map(str, allowed_values)))
            )

        self._age_appropriate = age_appropriate

    @property
    def is_default(self) -> bool:
        """Gets the is_default of this CreateGuardrailRequest.

        Whether this is default for category  # noqa: E501

        :return: The is_default of this CreateGuardrailRequest.
        :rtype: bool
        """
        return self._is_default

    @is_default.setter
    def is_default(self, is_default: bool):
        """Sets the is_default of this CreateGuardrailRequest.

        Whether this is default for category  # noqa: E501

        :param is_default: The is_default of this CreateGuardrailRequest.
        :type is_default: bool
        """

        self._is_default = is_default
