from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class CreateAssistantRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, animal_id=None, personality_id=None, guardrail_id=None, knowledge_base_file_ids=None):  # noqa: E501
        """CreateAssistantRequest - a model defined in OpenAPI

        :param animal_id: The animal_id of this CreateAssistantRequest.  # noqa: E501
        :type animal_id: str
        :param personality_id: The personality_id of this CreateAssistantRequest.  # noqa: E501
        :type personality_id: str
        :param guardrail_id: The guardrail_id of this CreateAssistantRequest.  # noqa: E501
        :type guardrail_id: str
        :param knowledge_base_file_ids: The knowledge_base_file_ids of this CreateAssistantRequest.  # noqa: E501
        :type knowledge_base_file_ids: List[str]
        """
        self.openapi_types = {
            'animal_id': str,
            'personality_id': str,
            'guardrail_id': str,
            'knowledge_base_file_ids': List[str]
        }

        self.attribute_map = {
            'animal_id': 'animalId',
            'personality_id': 'personalityId',
            'guardrail_id': 'guardrailId',
            'knowledge_base_file_ids': 'knowledgeBaseFileIds'
        }

        self._animal_id = animal_id
        self._personality_id = personality_id
        self._guardrail_id = guardrail_id
        self._knowledge_base_file_ids = knowledge_base_file_ids

    @classmethod
    def from_dict(cls, dikt) -> 'CreateAssistantRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateAssistantRequest of this CreateAssistantRequest.  # noqa: E501
        :rtype: CreateAssistantRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def animal_id(self) -> str:
        """Gets the animal_id of this CreateAssistantRequest.

        ID of the animal for this assistant  # noqa: E501

        :return: The animal_id of this CreateAssistantRequest.
        :rtype: str
        """
        return self._animal_id

    @animal_id.setter
    def animal_id(self, animal_id: str):
        """Sets the animal_id of this CreateAssistantRequest.

        ID of the animal for this assistant  # noqa: E501

        :param animal_id: The animal_id of this CreateAssistantRequest.
        :type animal_id: str
        """
        if animal_id is None:
            raise ValueError("Invalid value for `animal_id`, must not be `None`")  # noqa: E501

        self._animal_id = animal_id

    @property
    def personality_id(self) -> str:
        """Gets the personality_id of this CreateAssistantRequest.

        ID of the personality configuration  # noqa: E501

        :return: The personality_id of this CreateAssistantRequest.
        :rtype: str
        """
        return self._personality_id

    @personality_id.setter
    def personality_id(self, personality_id: str):
        """Sets the personality_id of this CreateAssistantRequest.

        ID of the personality configuration  # noqa: E501

        :param personality_id: The personality_id of this CreateAssistantRequest.
        :type personality_id: str
        """
        if personality_id is None:
            raise ValueError("Invalid value for `personality_id`, must not be `None`")  # noqa: E501

        self._personality_id = personality_id

    @property
    def guardrail_id(self) -> str:
        """Gets the guardrail_id of this CreateAssistantRequest.

        ID of the guardrail configuration  # noqa: E501

        :return: The guardrail_id of this CreateAssistantRequest.
        :rtype: str
        """
        return self._guardrail_id

    @guardrail_id.setter
    def guardrail_id(self, guardrail_id: str):
        """Sets the guardrail_id of this CreateAssistantRequest.

        ID of the guardrail configuration  # noqa: E501

        :param guardrail_id: The guardrail_id of this CreateAssistantRequest.
        :type guardrail_id: str
        """
        if guardrail_id is None:
            raise ValueError("Invalid value for `guardrail_id`, must not be `None`")  # noqa: E501

        self._guardrail_id = guardrail_id

    @property
    def knowledge_base_file_ids(self) -> List[str]:
        """Gets the knowledge_base_file_ids of this CreateAssistantRequest.

        Optional array of knowledge base file IDs  # noqa: E501

        :return: The knowledge_base_file_ids of this CreateAssistantRequest.
        :rtype: List[str]
        """
        return self._knowledge_base_file_ids

    @knowledge_base_file_ids.setter
    def knowledge_base_file_ids(self, knowledge_base_file_ids: List[str]):
        """Sets the knowledge_base_file_ids of this CreateAssistantRequest.

        Optional array of knowledge base file IDs  # noqa: E501

        :param knowledge_base_file_ids: The knowledge_base_file_ids of this CreateAssistantRequest.
        :type knowledge_base_file_ids: List[str]
        """

        self._knowledge_base_file_ids = knowledge_base_file_ids
