from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.triggered_rules_summary import TriggeredRulesSummary
from openapi_server.models.validation_summary import ValidationSummary
from openapi_server import util

from openapi_server.models.triggered_rules_summary import TriggeredRulesSummary  # noqa: E501
from openapi_server.models.validation_summary import ValidationSummary  # noqa: E501

class DetailedValidationResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, valid=None, result=None, risk_score=None, requires_escalation=None, user_message=None, safe_alternative=None, validation_id=None, timestamp=None, processing_time_ms=None, triggered_rules=None, summary=None):  # noqa: E501
        """DetailedValidationResponse - a model defined in OpenAPI

        :param valid: The valid of this DetailedValidationResponse.  # noqa: E501
        :type valid: bool
        :param result: The result of this DetailedValidationResponse.  # noqa: E501
        :type result: str
        :param risk_score: The risk_score of this DetailedValidationResponse.  # noqa: E501
        :type risk_score: float
        :param requires_escalation: The requires_escalation of this DetailedValidationResponse.  # noqa: E501
        :type requires_escalation: bool
        :param user_message: The user_message of this DetailedValidationResponse.  # noqa: E501
        :type user_message: str
        :param safe_alternative: The safe_alternative of this DetailedValidationResponse.  # noqa: E501
        :type safe_alternative: str
        :param validation_id: The validation_id of this DetailedValidationResponse.  # noqa: E501
        :type validation_id: str
        :param timestamp: The timestamp of this DetailedValidationResponse.  # noqa: E501
        :type timestamp: datetime
        :param processing_time_ms: The processing_time_ms of this DetailedValidationResponse.  # noqa: E501
        :type processing_time_ms: int
        :param triggered_rules: The triggered_rules of this DetailedValidationResponse.  # noqa: E501
        :type triggered_rules: TriggeredRulesSummary
        :param summary: The summary of this DetailedValidationResponse.  # noqa: E501
        :type summary: ValidationSummary
        """
        self.openapi_types = {
            'valid': bool,
            'result': str,
            'risk_score': float,
            'requires_escalation': bool,
            'user_message': str,
            'safe_alternative': str,
            'validation_id': str,
            'timestamp': datetime,
            'processing_time_ms': int,
            'triggered_rules': TriggeredRulesSummary,
            'summary': ValidationSummary
        }

        self.attribute_map = {
            'valid': 'valid',
            'result': 'result',
            'risk_score': 'riskScore',
            'requires_escalation': 'requiresEscalation',
            'user_message': 'userMessage',
            'safe_alternative': 'safeAlternative',
            'validation_id': 'validationId',
            'timestamp': 'timestamp',
            'processing_time_ms': 'processingTimeMs',
            'triggered_rules': 'triggeredRules',
            'summary': 'summary'
        }

        self._valid = valid
        self._result = result
        self._risk_score = risk_score
        self._requires_escalation = requires_escalation
        self._user_message = user_message
        self._safe_alternative = safe_alternative
        self._validation_id = validation_id
        self._timestamp = timestamp
        self._processing_time_ms = processing_time_ms
        self._triggered_rules = triggered_rules
        self._summary = summary

    @classmethod
    def from_dict(cls, dikt) -> 'DetailedValidationResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DetailedValidationResponse of this DetailedValidationResponse.  # noqa: E501
        :rtype: DetailedValidationResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def valid(self) -> bool:
        """Gets the valid of this DetailedValidationResponse.

        Whether content passes safety validation  # noqa: E501

        :return: The valid of this DetailedValidationResponse.
        :rtype: bool
        """
        return self._valid

    @valid.setter
    def valid(self, valid: bool):
        """Sets the valid of this DetailedValidationResponse.

        Whether content passes safety validation  # noqa: E501

        :param valid: The valid of this DetailedValidationResponse.
        :type valid: bool
        """
        if valid is None:
            raise ValueError("Invalid value for `valid`, must not be `None`")  # noqa: E501

        self._valid = valid

    @property
    def result(self) -> str:
        """Gets the result of this DetailedValidationResponse.

        Validation outcome  # noqa: E501

        :return: The result of this DetailedValidationResponse.
        :rtype: str
        """
        return self._result

    @result.setter
    def result(self, result: str):
        """Sets the result of this DetailedValidationResponse.

        Validation outcome  # noqa: E501

        :param result: The result of this DetailedValidationResponse.
        :type result: str
        """
        allowed_values = ["approved", "flagged", "blocked", "escalated"]  # noqa: E501
        if result not in allowed_values:
            raise ValueError(
                "Invalid value for `result` ({0}), must be one of {1}"
                .format(result, allowed_values)
            )

        self._result = result

    @property
    def risk_score(self) -> float:
        """Gets the risk_score of this DetailedValidationResponse.

        Calculated risk score (0=safe, 100=high risk)  # noqa: E501

        :return: The risk_score of this DetailedValidationResponse.
        :rtype: float
        """
        return self._risk_score

    @risk_score.setter
    def risk_score(self, risk_score: float):
        """Sets the risk_score of this DetailedValidationResponse.

        Calculated risk score (0=safe, 100=high risk)  # noqa: E501

        :param risk_score: The risk_score of this DetailedValidationResponse.
        :type risk_score: float
        """
        if risk_score is None:
            raise ValueError("Invalid value for `risk_score`, must not be `None`")  # noqa: E501
        if risk_score is not None and risk_score > 100:  # noqa: E501
            raise ValueError("Invalid value for `risk_score`, must be a value less than or equal to `100`")  # noqa: E501
        if risk_score is not None and risk_score < 0:  # noqa: E501
            raise ValueError("Invalid value for `risk_score`, must be a value greater than or equal to `0`")  # noqa: E501

        self._risk_score = risk_score

    @property
    def requires_escalation(self) -> bool:
        """Gets the requires_escalation of this DetailedValidationResponse.

        Whether validation requires human review  # noqa: E501

        :return: The requires_escalation of this DetailedValidationResponse.
        :rtype: bool
        """
        return self._requires_escalation

    @requires_escalation.setter
    def requires_escalation(self, requires_escalation: bool):
        """Sets the requires_escalation of this DetailedValidationResponse.

        Whether validation requires human review  # noqa: E501

        :param requires_escalation: The requires_escalation of this DetailedValidationResponse.
        :type requires_escalation: bool
        """
        if requires_escalation is None:
            raise ValueError("Invalid value for `requires_escalation`, must not be `None`")  # noqa: E501

        self._requires_escalation = requires_escalation

    @property
    def user_message(self) -> str:
        """Gets the user_message of this DetailedValidationResponse.

        User-facing message about validation result  # noqa: E501

        :return: The user_message of this DetailedValidationResponse.
        :rtype: str
        """
        return self._user_message

    @user_message.setter
    def user_message(self, user_message: str):
        """Sets the user_message of this DetailedValidationResponse.

        User-facing message about validation result  # noqa: E501

        :param user_message: The user_message of this DetailedValidationResponse.
        :type user_message: str
        """
        if user_message is not None and len(user_message) > 200:
            raise ValueError("Invalid value for `user_message`, length must be less than or equal to `200`")  # noqa: E501

        self._user_message = user_message

    @property
    def safe_alternative(self) -> str:
        """Gets the safe_alternative of this DetailedValidationResponse.

        Safe alternative content if available  # noqa: E501

        :return: The safe_alternative of this DetailedValidationResponse.
        :rtype: str
        """
        return self._safe_alternative

    @safe_alternative.setter
    def safe_alternative(self, safe_alternative: str):
        """Sets the safe_alternative of this DetailedValidationResponse.

        Safe alternative content if available  # noqa: E501

        :param safe_alternative: The safe_alternative of this DetailedValidationResponse.
        :type safe_alternative: str
        """
        if safe_alternative is not None and len(safe_alternative) > 1000:
            raise ValueError("Invalid value for `safe_alternative`, length must be less than or equal to `1000`")  # noqa: E501

        self._safe_alternative = safe_alternative

    @property
    def validation_id(self) -> str:
        """Gets the validation_id of this DetailedValidationResponse.

        Unique identifier for this validation event  # noqa: E501

        :return: The validation_id of this DetailedValidationResponse.
        :rtype: str
        """
        return self._validation_id

    @validation_id.setter
    def validation_id(self, validation_id: str):
        """Sets the validation_id of this DetailedValidationResponse.

        Unique identifier for this validation event  # noqa: E501

        :param validation_id: The validation_id of this DetailedValidationResponse.
        :type validation_id: str
        """
        if validation_id is None:
            raise ValueError("Invalid value for `validation_id`, must not be `None`")  # noqa: E501

        self._validation_id = validation_id

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this DetailedValidationResponse.

        ISO8601 timestamp when validation occurred  # noqa: E501

        :return: The timestamp of this DetailedValidationResponse.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this DetailedValidationResponse.

        ISO8601 timestamp when validation occurred  # noqa: E501

        :param timestamp: The timestamp of this DetailedValidationResponse.
        :type timestamp: datetime
        """
        if timestamp is None:
            raise ValueError("Invalid value for `timestamp`, must not be `None`")  # noqa: E501

        self._timestamp = timestamp

    @property
    def processing_time_ms(self) -> int:
        """Gets the processing_time_ms of this DetailedValidationResponse.

        Processing time in milliseconds  # noqa: E501

        :return: The processing_time_ms of this DetailedValidationResponse.
        :rtype: int
        """
        return self._processing_time_ms

    @processing_time_ms.setter
    def processing_time_ms(self, processing_time_ms: int):
        """Sets the processing_time_ms of this DetailedValidationResponse.

        Processing time in milliseconds  # noqa: E501

        :param processing_time_ms: The processing_time_ms of this DetailedValidationResponse.
        :type processing_time_ms: int
        """
        if processing_time_ms is None:
            raise ValueError("Invalid value for `processing_time_ms`, must not be `None`")  # noqa: E501
        if processing_time_ms is not None and processing_time_ms > 60000:  # noqa: E501
            raise ValueError("Invalid value for `processing_time_ms`, must be a value less than or equal to `60000`")  # noqa: E501
        if processing_time_ms is not None and processing_time_ms < 0:  # noqa: E501
            raise ValueError("Invalid value for `processing_time_ms`, must be a value greater than or equal to `0`")  # noqa: E501

        self._processing_time_ms = processing_time_ms

    @property
    def triggered_rules(self) -> TriggeredRulesSummary:
        """Gets the triggered_rules of this DetailedValidationResponse.


        :return: The triggered_rules of this DetailedValidationResponse.
        :rtype: TriggeredRulesSummary
        """
        return self._triggered_rules

    @triggered_rules.setter
    def triggered_rules(self, triggered_rules: TriggeredRulesSummary):
        """Sets the triggered_rules of this DetailedValidationResponse.


        :param triggered_rules: The triggered_rules of this DetailedValidationResponse.
        :type triggered_rules: TriggeredRulesSummary
        """
        if triggered_rules is None:
            raise ValueError("Invalid value for `triggered_rules`, must not be `None`")  # noqa: E501

        self._triggered_rules = triggered_rules

    @property
    def summary(self) -> ValidationSummary:
        """Gets the summary of this DetailedValidationResponse.


        :return: The summary of this DetailedValidationResponse.
        :rtype: ValidationSummary
        """
        return self._summary

    @summary.setter
    def summary(self, summary: ValidationSummary):
        """Sets the summary of this DetailedValidationResponse.


        :param summary: The summary of this DetailedValidationResponse.
        :type summary: ValidationSummary
        """
        if summary is None:
            raise ValueError("Invalid value for `summary`, must not be `None`")  # noqa: E501

        self._summary = summary
