from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.family_input_address import FamilyInputAddress
from openapi_server import util

from openapi_server.models.family_input_address import FamilyInputAddress  # noqa: E501

class FamilyInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, family_name=None, parents=None, students=None, address=None, preferred_programs=None, status='active'):  # noqa: E501
        """FamilyInput - a model defined in OpenAPI

        :param family_name: The family_name of this FamilyInput.  # noqa: E501
        :type family_name: str
        :param parents: The parents of this FamilyInput.  # noqa: E501
        :type parents: List[str]
        :param students: The students of this FamilyInput.  # noqa: E501
        :type students: List[str]
        :param address: The address of this FamilyInput.  # noqa: E501
        :type address: FamilyInputAddress
        :param preferred_programs: The preferred_programs of this FamilyInput.  # noqa: E501
        :type preferred_programs: List[str]
        :param status: The status of this FamilyInput.  # noqa: E501
        :type status: str
        """
        self.openapi_types = {
            'family_name': str,
            'parents': List[str],
            'students': List[str],
            'address': FamilyInputAddress,
            'preferred_programs': List[str],
            'status': str
        }

        self.attribute_map = {
            'family_name': 'familyName',
            'parents': 'parents',
            'students': 'students',
            'address': 'address',
            'preferred_programs': 'preferredPrograms',
            'status': 'status'
        }

        self._family_name = family_name
        self._parents = parents
        self._students = students
        self._address = address
        self._preferred_programs = preferred_programs
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'FamilyInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FamilyInput of this FamilyInput.  # noqa: E501
        :rtype: FamilyInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def family_name(self) -> str:
        """Gets the family_name of this FamilyInput.

        Name of the family group  # noqa: E501

        :return: The family_name of this FamilyInput.
        :rtype: str
        """
        return self._family_name

    @family_name.setter
    def family_name(self, family_name: str):
        """Sets the family_name of this FamilyInput.

        Name of the family group  # noqa: E501

        :param family_name: The family_name of this FamilyInput.
        :type family_name: str
        """
        if family_name is None:
            raise ValueError("Invalid value for `family_name`, must not be `None`")  # noqa: E501
        if family_name is not None and len(family_name) > 100:
            raise ValueError("Invalid value for `family_name`, length must be less than or equal to `100`")  # noqa: E501
        if family_name is not None and len(family_name) < 1:
            raise ValueError("Invalid value for `family_name`, length must be greater than or equal to `1`")  # noqa: E501

        self._family_name = family_name

    @property
    def parents(self) -> List[str]:
        """Gets the parents of this FamilyInput.


        :return: The parents of this FamilyInput.
        :rtype: List[str]
        """
        return self._parents

    @parents.setter
    def parents(self, parents: List[str]):
        """Sets the parents of this FamilyInput.


        :param parents: The parents of this FamilyInput.
        :type parents: List[str]
        """
        if parents is None:
            raise ValueError("Invalid value for `parents`, must not be `None`")  # noqa: E501
        if parents is not None and len(parents) < 1:
            raise ValueError("Invalid value for `parents`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._parents = parents

    @property
    def students(self) -> List[str]:
        """Gets the students of this FamilyInput.


        :return: The students of this FamilyInput.
        :rtype: List[str]
        """
        return self._students

    @students.setter
    def students(self, students: List[str]):
        """Sets the students of this FamilyInput.


        :param students: The students of this FamilyInput.
        :type students: List[str]
        """
        if students is None:
            raise ValueError("Invalid value for `students`, must not be `None`")  # noqa: E501
        if students is not None and len(students) > 8:
            raise ValueError("Invalid value for `students`, number of items must be less than or equal to `8`")  # noqa: E501
        if students is not None and len(students) < 1:
            raise ValueError("Invalid value for `students`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._students = students

    @property
    def address(self) -> FamilyInputAddress:
        """Gets the address of this FamilyInput.


        :return: The address of this FamilyInput.
        :rtype: FamilyInputAddress
        """
        return self._address

    @address.setter
    def address(self, address: FamilyInputAddress):
        """Sets the address of this FamilyInput.


        :param address: The address of this FamilyInput.
        :type address: FamilyInputAddress
        """

        self._address = address

    @property
    def preferred_programs(self) -> List[str]:
        """Gets the preferred_programs of this FamilyInput.


        :return: The preferred_programs of this FamilyInput.
        :rtype: List[str]
        """
        return self._preferred_programs

    @preferred_programs.setter
    def preferred_programs(self, preferred_programs: List[str]):
        """Sets the preferred_programs of this FamilyInput.


        :param preferred_programs: The preferred_programs of this FamilyInput.
        :type preferred_programs: List[str]
        """

        self._preferred_programs = preferred_programs

    @property
    def status(self) -> str:
        """Gets the status of this FamilyInput.


        :return: The status of this FamilyInput.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this FamilyInput.


        :param status: The status of this FamilyInput.
        :type status: str
        """
        allowed_values = ["active", "inactive", "pending"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status
