from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.audit_stamp import AuditStamp
from openapi_server.models.family_address import FamilyAddress
from openapi_server import util

from openapi_server.models.audit_stamp import AuditStamp  # noqa: E501
from openapi_server.models.family_address import FamilyAddress  # noqa: E501

class Family(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, family_id=None, family_name=None, parents=None, students=None, address=None, preferred_programs=None, status='active', member_since=None, created=None, modified=None):  # noqa: E501
        """Family - a model defined in OpenAPI

        :param family_id: The family_id of this Family.  # noqa: E501
        :type family_id: str
        :param family_name: The family_name of this Family.  # noqa: E501
        :type family_name: str
        :param parents: The parents of this Family.  # noqa: E501
        :type parents: List[str]
        :param students: The students of this Family.  # noqa: E501
        :type students: List[str]
        :param address: The address of this Family.  # noqa: E501
        :type address: FamilyAddress
        :param preferred_programs: The preferred_programs of this Family.  # noqa: E501
        :type preferred_programs: List[str]
        :param status: The status of this Family.  # noqa: E501
        :type status: str
        :param member_since: The member_since of this Family.  # noqa: E501
        :type member_since: datetime
        :param created: The created of this Family.  # noqa: E501
        :type created: AuditStamp
        :param modified: The modified of this Family.  # noqa: E501
        :type modified: AuditStamp
        """
        self.openapi_types = {
            'family_id': str,
            'family_name': str,
            'parents': List[str],
            'students': List[str],
            'address': FamilyAddress,
            'preferred_programs': List[str],
            'status': str,
            'member_since': datetime,
            'created': AuditStamp,
            'modified': AuditStamp
        }

        self.attribute_map = {
            'family_id': 'familyId',
            'family_name': 'familyName',
            'parents': 'parents',
            'students': 'students',
            'address': 'address',
            'preferred_programs': 'preferredPrograms',
            'status': 'status',
            'member_since': 'memberSince',
            'created': 'created',
            'modified': 'modified'
        }

        self._family_id = family_id
        self._family_name = family_name
        self._parents = parents
        self._students = students
        self._address = address
        self._preferred_programs = preferred_programs
        self._status = status
        self._member_since = member_since
        self._created = created
        self._modified = modified

    @classmethod
    def from_dict(cls, dikt) -> 'Family':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Family of this Family.  # noqa: E501
        :rtype: Family
        """
        return util.deserialize_model(dikt, cls)

    @property
    def family_id(self) -> str:
        """Gets the family_id of this Family.

        Unique family ID  # noqa: E501

        :return: The family_id of this Family.
        :rtype: str
        """
        return self._family_id

    @family_id.setter
    def family_id(self, family_id: str):
        """Sets the family_id of this Family.

        Unique family ID  # noqa: E501

        :param family_id: The family_id of this Family.
        :type family_id: str
        """

        self._family_id = family_id

    @property
    def family_name(self) -> str:
        """Gets the family_name of this Family.

        Name of the family group  # noqa: E501

        :return: The family_name of this Family.
        :rtype: str
        """
        return self._family_name

    @family_name.setter
    def family_name(self, family_name: str):
        """Sets the family_name of this Family.

        Name of the family group  # noqa: E501

        :param family_name: The family_name of this Family.
        :type family_name: str
        """
        if family_name is None:
            raise ValueError("Invalid value for `family_name`, must not be `None`")  # noqa: E501
        if family_name is not None and len(family_name) > 100:
            raise ValueError("Invalid value for `family_name`, length must be less than or equal to `100`")  # noqa: E501
        if family_name is not None and len(family_name) < 1:
            raise ValueError("Invalid value for `family_name`, length must be greater than or equal to `1`")  # noqa: E501

        self._family_name = family_name

    @property
    def parents(self) -> List[str]:
        """Gets the parents of this Family.


        :return: The parents of this Family.
        :rtype: List[str]
        """
        return self._parents

    @parents.setter
    def parents(self, parents: List[str]):
        """Sets the parents of this Family.


        :param parents: The parents of this Family.
        :type parents: List[str]
        """
        if parents is None:
            raise ValueError("Invalid value for `parents`, must not be `None`")  # noqa: E501
        if parents is not None and len(parents) < 1:
            raise ValueError("Invalid value for `parents`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._parents = parents

    @property
    def students(self) -> List[str]:
        """Gets the students of this Family.


        :return: The students of this Family.
        :rtype: List[str]
        """
        return self._students

    @students.setter
    def students(self, students: List[str]):
        """Sets the students of this Family.


        :param students: The students of this Family.
        :type students: List[str]
        """
        if students is None:
            raise ValueError("Invalid value for `students`, must not be `None`")  # noqa: E501
        if students is not None and len(students) > 8:
            raise ValueError("Invalid value for `students`, number of items must be less than or equal to `8`")  # noqa: E501
        if students is not None and len(students) < 1:
            raise ValueError("Invalid value for `students`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._students = students

    @property
    def address(self) -> FamilyAddress:
        """Gets the address of this Family.


        :return: The address of this Family.
        :rtype: FamilyAddress
        """
        return self._address

    @address.setter
    def address(self, address: FamilyAddress):
        """Sets the address of this Family.


        :param address: The address of this Family.
        :type address: FamilyAddress
        """

        self._address = address

    @property
    def preferred_programs(self) -> List[str]:
        """Gets the preferred_programs of this Family.

        Educational programs the family is interested in  # noqa: E501

        :return: The preferred_programs of this Family.
        :rtype: List[str]
        """
        return self._preferred_programs

    @preferred_programs.setter
    def preferred_programs(self, preferred_programs: List[str]):
        """Sets the preferred_programs of this Family.

        Educational programs the family is interested in  # noqa: E501

        :param preferred_programs: The preferred_programs of this Family.
        :type preferred_programs: List[str]
        """

        self._preferred_programs = preferred_programs

    @property
    def status(self) -> str:
        """Gets the status of this Family.

        Family enrollment status  # noqa: E501

        :return: The status of this Family.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this Family.

        Family enrollment status  # noqa: E501

        :param status: The status of this Family.
        :type status: str
        """
        allowed_values = ["active", "inactive", "pending"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def member_since(self) -> datetime:
        """Gets the member_since of this Family.

        When the family joined  # noqa: E501

        :return: The member_since of this Family.
        :rtype: datetime
        """
        return self._member_since

    @member_since.setter
    def member_since(self, member_since: datetime):
        """Sets the member_since of this Family.

        When the family joined  # noqa: E501

        :param member_since: The member_since of this Family.
        :type member_since: datetime
        """

        self._member_since = member_since

    @property
    def created(self) -> AuditStamp:
        """Gets the created of this Family.


        :return: The created of this Family.
        :rtype: AuditStamp
        """
        return self._created

    @created.setter
    def created(self, created: AuditStamp):
        """Sets the created of this Family.


        :param created: The created of this Family.
        :type created: AuditStamp
        """

        self._created = created

    @property
    def modified(self) -> AuditStamp:
        """Gets the modified of this Family.


        :return: The modified of this Family.
        :rtype: AuditStamp
        """
        return self._modified

    @modified.setter
    def modified(self, modified: AuditStamp):
        """Sets the modified of this Family.


        :param modified: The modified of this Family.
        :type modified: AuditStamp
        """

        self._modified = modified
