from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Family(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, family_id=None, parents=None, students=None):  # noqa: E501
        """Family - a model defined in OpenAPI

        :param family_id: The family_id of this Family.  # noqa: E501
        :type family_id: str
        :param parents: The parents of this Family.  # noqa: E501
        :type parents: List[str]
        :param students: The students of this Family.  # noqa: E501
        :type students: List[str]
        """
        self.openapi_types = {
            'family_id': str,
            'parents': List[str],
            'students': List[str]
        }

        self.attribute_map = {
            'family_id': 'familyId',
            'parents': 'parents',
            'students': 'students'
        }

        self._family_id = family_id
        self._parents = parents
        self._students = students

    @classmethod
    def from_dict(cls, dikt) -> 'Family':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Family of this Family.  # noqa: E501
        :rtype: Family
        """
        return util.deserialize_model(dikt, cls)

    @property
    def family_id(self) -> str:
        """Gets the family_id of this Family.

        Unique family ID  # noqa: E501

        :return: The family_id of this Family.
        :rtype: str
        """
        return self._family_id

    @family_id.setter
    def family_id(self, family_id: str):
        """Sets the family_id of this Family.

        Unique family ID  # noqa: E501

        :param family_id: The family_id of this Family.
        :type family_id: str
        """

        self._family_id = family_id

    @property
    def parents(self) -> List[str]:
        """Gets the parents of this Family.


        :return: The parents of this Family.
        :rtype: List[str]
        """
        return self._parents

    @parents.setter
    def parents(self, parents: List[str]):
        """Sets the parents of this Family.


        :param parents: The parents of this Family.
        :type parents: List[str]
        """
        if parents is None:
            raise ValueError("Invalid value for `parents`, must not be `None`")  # noqa: E501

        self._parents = parents

    @property
    def students(self) -> List[str]:
        """Gets the students of this Family.


        :return: The students of this Family.
        :rtype: List[str]
        """
        return self._students

    @students.setter
    def students(self, students: List[str]):
        """Sets the students of this Family.


        :param students: The students of this Family.
        :type students: List[str]
        """
        if students is None:
            raise ValueError("Invalid value for `students`, must not be `None`")  # noqa: E501

        self._students = students
