from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.feature_flags_value import FeatureFlagsValue
from openapi_server import util

from openapi_server.models.feature_flags_value import FeatureFlagsValue  # noqa: E501

class FeatureFlagsUpdate(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, flags=None):  # noqa: E501
        """FeatureFlagsUpdate - a model defined in OpenAPI

        :param flags: The flags of this FeatureFlagsUpdate.  # noqa: E501
        :type flags: Dict[str, FeatureFlagsValue]
        """
        self.openapi_types = {
            'flags': Dict[str, FeatureFlagsValue]
        }

        self.attribute_map = {
            'flags': 'flags'
        }

        self._flags = flags

    @classmethod
    def from_dict(cls, dikt) -> 'FeatureFlagsUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FeatureFlagsUpdate of this FeatureFlagsUpdate.  # noqa: E501
        :rtype: FeatureFlagsUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def flags(self) -> Dict[str, FeatureFlagsValue]:
        """Gets the flags of this FeatureFlagsUpdate.


        :return: The flags of this FeatureFlagsUpdate.
        :rtype: Dict[str, FeatureFlagsValue]
        """
        return self._flags

    @flags.setter
    def flags(self, flags: Dict[str, FeatureFlagsValue]):
        """Sets the flags of this FeatureFlagsUpdate.


        :param flags: The flags of this FeatureFlagsUpdate.
        :type flags: Dict[str, FeatureFlagsValue]
        """

        self._flags = flags
