from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.audit_stamp import AuditStamp
from openapi_server.models.feature_flags_value import FeatureFlagsValue
from openapi_server import util

from openapi_server.models.audit_stamp import AuditStamp  # noqa: E501
from openapi_server.models.feature_flags_value import FeatureFlagsValue  # noqa: E501

class FeatureFlagsDocument(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, created=None, modified=None, deleted=None, soft_delete=False, flags=None):  # noqa: E501
        """FeatureFlagsDocument - a model defined in OpenAPI

        :param created: The created of this FeatureFlagsDocument.  # noqa: E501
        :type created: AuditStamp
        :param modified: The modified of this FeatureFlagsDocument.  # noqa: E501
        :type modified: AuditStamp
        :param deleted: The deleted of this FeatureFlagsDocument.  # noqa: E501
        :type deleted: AuditStamp
        :param soft_delete: The soft_delete of this FeatureFlagsDocument.  # noqa: E501
        :type soft_delete: bool
        :param flags: The flags of this FeatureFlagsDocument.  # noqa: E501
        :type flags: Dict[str, FeatureFlagsValue]
        """
        self.openapi_types = {
            'created': AuditStamp,
            'modified': AuditStamp,
            'deleted': AuditStamp,
            'soft_delete': bool,
            'flags': Dict[str, FeatureFlagsValue]
        }

        self.attribute_map = {
            'created': 'created',
            'modified': 'modified',
            'deleted': 'deleted',
            'soft_delete': 'softDelete',
            'flags': 'flags'
        }

        self._created = created
        self._modified = modified
        self._deleted = deleted
        self._soft_delete = soft_delete
        self._flags = flags

    @classmethod
    def from_dict(cls, dikt) -> 'FeatureFlagsDocument':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FeatureFlagsDocument of this FeatureFlagsDocument.  # noqa: E501
        :rtype: FeatureFlagsDocument
        """
        return util.deserialize_model(dikt, cls)

    @property
    def created(self) -> AuditStamp:
        """Gets the created of this FeatureFlagsDocument.


        :return: The created of this FeatureFlagsDocument.
        :rtype: AuditStamp
        """
        return self._created

    @created.setter
    def created(self, created: AuditStamp):
        """Sets the created of this FeatureFlagsDocument.


        :param created: The created of this FeatureFlagsDocument.
        :type created: AuditStamp
        """

        self._created = created

    @property
    def modified(self) -> AuditStamp:
        """Gets the modified of this FeatureFlagsDocument.


        :return: The modified of this FeatureFlagsDocument.
        :rtype: AuditStamp
        """
        return self._modified

    @modified.setter
    def modified(self, modified: AuditStamp):
        """Sets the modified of this FeatureFlagsDocument.


        :param modified: The modified of this FeatureFlagsDocument.
        :type modified: AuditStamp
        """

        self._modified = modified

    @property
    def deleted(self) -> AuditStamp:
        """Gets the deleted of this FeatureFlagsDocument.


        :return: The deleted of this FeatureFlagsDocument.
        :rtype: AuditStamp
        """
        return self._deleted

    @deleted.setter
    def deleted(self, deleted: AuditStamp):
        """Sets the deleted of this FeatureFlagsDocument.


        :param deleted: The deleted of this FeatureFlagsDocument.
        :type deleted: AuditStamp
        """

        self._deleted = deleted

    @property
    def soft_delete(self) -> bool:
        """Gets the soft_delete of this FeatureFlagsDocument.


        :return: The soft_delete of this FeatureFlagsDocument.
        :rtype: bool
        """
        return self._soft_delete

    @soft_delete.setter
    def soft_delete(self, soft_delete: bool):
        """Sets the soft_delete of this FeatureFlagsDocument.


        :param soft_delete: The soft_delete of this FeatureFlagsDocument.
        :type soft_delete: bool
        """

        self._soft_delete = soft_delete

    @property
    def flags(self) -> Dict[str, FeatureFlagsValue]:
        """Gets the flags of this FeatureFlagsDocument.


        :return: The flags of this FeatureFlagsDocument.
        :rtype: Dict[str, FeatureFlagsValue]
        """
        return self._flags

    @flags.setter
    def flags(self, flags: Dict[str, FeatureFlagsValue]):
        """Sets the flags of this FeatureFlagsDocument.


        :param flags: The flags of this FeatureFlagsDocument.
        :type flags: Dict[str, FeatureFlagsValue]
        """

        self._flags = flags
