from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class GetAnimalSystemPrompt200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, prompt=None, guardrail_count=None):  # noqa: E501
        """GetAnimalSystemPrompt200Response - a model defined in OpenAPI

        :param prompt: The prompt of this GetAnimalSystemPrompt200Response.  # noqa: E501
        :type prompt: str
        :param guardrail_count: The guardrail_count of this GetAnimalSystemPrompt200Response.  # noqa: E501
        :type guardrail_count: int
        """
        self.openapi_types = {
            'prompt': str,
            'guardrail_count': int
        }

        self.attribute_map = {
            'prompt': 'prompt',
            'guardrail_count': 'guardrailCount'
        }

        self._prompt = prompt
        self._guardrail_count = guardrail_count

    @classmethod
    def from_dict(cls, dikt) -> 'GetAnimalSystemPrompt200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The getAnimalSystemPrompt_200_response of this GetAnimalSystemPrompt200Response.  # noqa: E501
        :rtype: GetAnimalSystemPrompt200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def prompt(self) -> str:
        """Gets the prompt of this GetAnimalSystemPrompt200Response.

        Complete system prompt with guardrails  # noqa: E501

        :return: The prompt of this GetAnimalSystemPrompt200Response.
        :rtype: str
        """
        return self._prompt

    @prompt.setter
    def prompt(self, prompt: str):
        """Sets the prompt of this GetAnimalSystemPrompt200Response.

        Complete system prompt with guardrails  # noqa: E501

        :param prompt: The prompt of this GetAnimalSystemPrompt200Response.
        :type prompt: str
        """

        self._prompt = prompt

    @property
    def guardrail_count(self) -> int:
        """Gets the guardrail_count of this GetAnimalSystemPrompt200Response.

        Number of guardrails included  # noqa: E501

        :return: The guardrail_count of this GetAnimalSystemPrompt200Response.
        :rtype: int
        """
        return self._guardrail_count

    @guardrail_count.setter
    def guardrail_count(self, guardrail_count: int):
        """Sets the guardrail_count of this GetAnimalSystemPrompt200Response.

        Number of guardrails included  # noqa: E501

        :param guardrail_count: The guardrail_count of this GetAnimalSystemPrompt200Response.
        :type guardrail_count: int
        """

        self._guardrail_count = guardrail_count
