from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.guardrail_all_of_examples import GuardrailAllOfExamples
from openapi_server import util

from openapi_server.models.guardrail_all_of_examples import GuardrailAllOfExamples  # noqa: E501

class GuardrailUpdate(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, description=None, category=None, priority=None, is_active=None, keywords=None, examples=None):  # noqa: E501
        """GuardrailUpdate - a model defined in OpenAPI

        :param name: The name of this GuardrailUpdate.  # noqa: E501
        :type name: str
        :param description: The description of this GuardrailUpdate.  # noqa: E501
        :type description: str
        :param category: The category of this GuardrailUpdate.  # noqa: E501
        :type category: str
        :param priority: The priority of this GuardrailUpdate.  # noqa: E501
        :type priority: int
        :param is_active: The is_active of this GuardrailUpdate.  # noqa: E501
        :type is_active: bool
        :param keywords: The keywords of this GuardrailUpdate.  # noqa: E501
        :type keywords: List[str]
        :param examples: The examples of this GuardrailUpdate.  # noqa: E501
        :type examples: GuardrailAllOfExamples
        """
        self.openapi_types = {
            'name': str,
            'description': str,
            'category': str,
            'priority': int,
            'is_active': bool,
            'keywords': List[str],
            'examples': GuardrailAllOfExamples
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description',
            'category': 'category',
            'priority': 'priority',
            'is_active': 'isActive',
            'keywords': 'keywords',
            'examples': 'examples'
        }

        self._name = name
        self._description = description
        self._category = category
        self._priority = priority
        self._is_active = is_active
        self._keywords = keywords
        self._examples = examples

    @classmethod
    def from_dict(cls, dikt) -> 'GuardrailUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GuardrailUpdate of this GuardrailUpdate.  # noqa: E501
        :rtype: GuardrailUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this GuardrailUpdate.

        Human-readable name for the guardrail  # noqa: E501

        :return: The name of this GuardrailUpdate.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this GuardrailUpdate.

        Human-readable name for the guardrail  # noqa: E501

        :param name: The name of this GuardrailUpdate.
        :type name: str
        """
        if name is not None and len(name) > 200:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `200`")  # noqa: E501
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this GuardrailUpdate.

        Optional detailed description  # noqa: E501

        :return: The description of this GuardrailUpdate.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this GuardrailUpdate.

        Optional detailed description  # noqa: E501

        :param description: The description of this GuardrailUpdate.
        :type description: str
        """
        if description is not None and len(description) > 1000:
            raise ValueError("Invalid value for `description`, length must be less than or equal to `1000`")  # noqa: E501

        self._description = description

    @property
    def category(self) -> str:
        """Gets the category of this GuardrailUpdate.

        Guardrail category for organization  # noqa: E501

        :return: The category of this GuardrailUpdate.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category: str):
        """Sets the category of this GuardrailUpdate.

        Guardrail category for organization  # noqa: E501

        :param category: The category of this GuardrailUpdate.
        :type category: str
        """
        allowed_values = ["content_safety", "educational", "personality", "technical"]  # noqa: E501
        if category not in allowed_values:
            raise ValueError(
                "Invalid value for `category` ({0}), must be one of {1}"
                .format(category, allowed_values)
            )

        self._category = category

    @property
    def priority(self) -> int:
        """Gets the priority of this GuardrailUpdate.

        Priority level (higher = more important)  # noqa: E501

        :return: The priority of this GuardrailUpdate.
        :rtype: int
        """
        return self._priority

    @priority.setter
    def priority(self, priority: int):
        """Sets the priority of this GuardrailUpdate.

        Priority level (higher = more important)  # noqa: E501

        :param priority: The priority of this GuardrailUpdate.
        :type priority: int
        """
        if priority is not None and priority > 100:  # noqa: E501
            raise ValueError("Invalid value for `priority`, must be a value less than or equal to `100`")  # noqa: E501
        if priority is not None and priority < 0:  # noqa: E501
            raise ValueError("Invalid value for `priority`, must be a value greater than or equal to `0`")  # noqa: E501

        self._priority = priority

    @property
    def is_active(self) -> bool:
        """Gets the is_active of this GuardrailUpdate.

        Whether the guardrail is currently active  # noqa: E501

        :return: The is_active of this GuardrailUpdate.
        :rtype: bool
        """
        return self._is_active

    @is_active.setter
    def is_active(self, is_active: bool):
        """Sets the is_active of this GuardrailUpdate.

        Whether the guardrail is currently active  # noqa: E501

        :param is_active: The is_active of this GuardrailUpdate.
        :type is_active: bool
        """

        self._is_active = is_active

    @property
    def keywords(self) -> List[str]:
        """Gets the keywords of this GuardrailUpdate.

        Keywords for search and filtering  # noqa: E501

        :return: The keywords of this GuardrailUpdate.
        :rtype: List[str]
        """
        return self._keywords

    @keywords.setter
    def keywords(self, keywords: List[str]):
        """Sets the keywords of this GuardrailUpdate.

        Keywords for search and filtering  # noqa: E501

        :param keywords: The keywords of this GuardrailUpdate.
        :type keywords: List[str]
        """
        if keywords is not None and len(keywords) > 20:
            raise ValueError("Invalid value for `keywords`, number of items must be less than or equal to `20`")  # noqa: E501

        self._keywords = keywords

    @property
    def examples(self) -> GuardrailAllOfExamples:
        """Gets the examples of this GuardrailUpdate.


        :return: The examples of this GuardrailUpdate.
        :rtype: GuardrailAllOfExamples
        """
        return self._examples

    @examples.setter
    def examples(self, examples: GuardrailAllOfExamples):
        """Sets the examples of this GuardrailUpdate.


        :param examples: The examples of this GuardrailUpdate.
        :type examples: GuardrailAllOfExamples
        """

        self._examples = examples
