from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.guardrail_all_of_examples import GuardrailAllOfExamples
from openapi_server import util

from openapi_server.models.guardrail_all_of_examples import GuardrailAllOfExamples  # noqa: E501

class GuardrailInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, type=None, rule=None, description=None, category='content_safety', priority=50, is_active=True, is_global=False, keywords=None, examples=None):  # noqa: E501
        """GuardrailInput - a model defined in OpenAPI

        :param name: The name of this GuardrailInput.  # noqa: E501
        :type name: str
        :param type: The type of this GuardrailInput.  # noqa: E501
        :type type: str
        :param rule: The rule of this GuardrailInput.  # noqa: E501
        :type rule: str
        :param description: The description of this GuardrailInput.  # noqa: E501
        :type description: str
        :param category: The category of this GuardrailInput.  # noqa: E501
        :type category: str
        :param priority: The priority of this GuardrailInput.  # noqa: E501
        :type priority: int
        :param is_active: The is_active of this GuardrailInput.  # noqa: E501
        :type is_active: bool
        :param is_global: The is_global of this GuardrailInput.  # noqa: E501
        :type is_global: bool
        :param keywords: The keywords of this GuardrailInput.  # noqa: E501
        :type keywords: List[str]
        :param examples: The examples of this GuardrailInput.  # noqa: E501
        :type examples: GuardrailAllOfExamples
        """
        self.openapi_types = {
            'name': str,
            'type': str,
            'rule': str,
            'description': str,
            'category': str,
            'priority': int,
            'is_active': bool,
            'is_global': bool,
            'keywords': List[str],
            'examples': GuardrailAllOfExamples
        }

        self.attribute_map = {
            'name': 'name',
            'type': 'type',
            'rule': 'rule',
            'description': 'description',
            'category': 'category',
            'priority': 'priority',
            'is_active': 'isActive',
            'is_global': 'isGlobal',
            'keywords': 'keywords',
            'examples': 'examples'
        }

        self._name = name
        self._type = type
        self._rule = rule
        self._description = description
        self._category = category
        self._priority = priority
        self._is_active = is_active
        self._is_global = is_global
        self._keywords = keywords
        self._examples = examples

    @classmethod
    def from_dict(cls, dikt) -> 'GuardrailInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GuardrailInput of this GuardrailInput.  # noqa: E501
        :rtype: GuardrailInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this GuardrailInput.

        Human-readable name for the guardrail  # noqa: E501

        :return: The name of this GuardrailInput.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this GuardrailInput.

        Human-readable name for the guardrail  # noqa: E501

        :param name: The name of this GuardrailInput.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) > 200:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `200`")  # noqa: E501
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def type(self) -> str:
        """Gets the type of this GuardrailInput.

        Type of guardrail rule  # noqa: E501

        :return: The type of this GuardrailInput.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this GuardrailInput.

        Type of guardrail rule  # noqa: E501

        :param type: The type of this GuardrailInput.
        :type type: str
        """
        allowed_values = ["ALWAYS", "NEVER", "ENCOURAGE", "DISCOURAGE"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def rule(self) -> str:
        """Gets the rule of this GuardrailInput.

        The actual rule text  # noqa: E501

        :return: The rule of this GuardrailInput.
        :rtype: str
        """
        return self._rule

    @rule.setter
    def rule(self, rule: str):
        """Sets the rule of this GuardrailInput.

        The actual rule text  # noqa: E501

        :param rule: The rule of this GuardrailInput.
        :type rule: str
        """
        if rule is None:
            raise ValueError("Invalid value for `rule`, must not be `None`")  # noqa: E501
        if rule is not None and len(rule) > 500:
            raise ValueError("Invalid value for `rule`, length must be less than or equal to `500`")  # noqa: E501
        if rule is not None and len(rule) < 1:
            raise ValueError("Invalid value for `rule`, length must be greater than or equal to `1`")  # noqa: E501

        self._rule = rule

    @property
    def description(self) -> str:
        """Gets the description of this GuardrailInput.

        Optional detailed description  # noqa: E501

        :return: The description of this GuardrailInput.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this GuardrailInput.

        Optional detailed description  # noqa: E501

        :param description: The description of this GuardrailInput.
        :type description: str
        """
        if description is not None and len(description) > 1000:
            raise ValueError("Invalid value for `description`, length must be less than or equal to `1000`")  # noqa: E501

        self._description = description

    @property
    def category(self) -> str:
        """Gets the category of this GuardrailInput.

        Guardrail category for organization  # noqa: E501

        :return: The category of this GuardrailInput.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category: str):
        """Sets the category of this GuardrailInput.

        Guardrail category for organization  # noqa: E501

        :param category: The category of this GuardrailInput.
        :type category: str
        """
        allowed_values = ["content_safety", "educational", "personality", "technical"]  # noqa: E501
        if category not in allowed_values:
            raise ValueError(
                "Invalid value for `category` ({0}), must be one of {1}"
                .format(category, allowed_values)
            )

        self._category = category

    @property
    def priority(self) -> int:
        """Gets the priority of this GuardrailInput.

        Priority level (higher = more important)  # noqa: E501

        :return: The priority of this GuardrailInput.
        :rtype: int
        """
        return self._priority

    @priority.setter
    def priority(self, priority: int):
        """Sets the priority of this GuardrailInput.

        Priority level (higher = more important)  # noqa: E501

        :param priority: The priority of this GuardrailInput.
        :type priority: int
        """
        if priority is not None and priority > 100:  # noqa: E501
            raise ValueError("Invalid value for `priority`, must be a value less than or equal to `100`")  # noqa: E501
        if priority is not None and priority < 0:  # noqa: E501
            raise ValueError("Invalid value for `priority`, must be a value greater than or equal to `0`")  # noqa: E501

        self._priority = priority

    @property
    def is_active(self) -> bool:
        """Gets the is_active of this GuardrailInput.

        Whether the guardrail is currently active  # noqa: E501

        :return: The is_active of this GuardrailInput.
        :rtype: bool
        """
        return self._is_active

    @is_active.setter
    def is_active(self, is_active: bool):
        """Sets the is_active of this GuardrailInput.

        Whether the guardrail is currently active  # noqa: E501

        :param is_active: The is_active of this GuardrailInput.
        :type is_active: bool
        """

        self._is_active = is_active

    @property
    def is_global(self) -> bool:
        """Gets the is_global of this GuardrailInput.

        Whether the guardrail applies to all animals by default  # noqa: E501

        :return: The is_global of this GuardrailInput.
        :rtype: bool
        """
        return self._is_global

    @is_global.setter
    def is_global(self, is_global: bool):
        """Sets the is_global of this GuardrailInput.

        Whether the guardrail applies to all animals by default  # noqa: E501

        :param is_global: The is_global of this GuardrailInput.
        :type is_global: bool
        """

        self._is_global = is_global

    @property
    def keywords(self) -> List[str]:
        """Gets the keywords of this GuardrailInput.

        Keywords for search and filtering  # noqa: E501

        :return: The keywords of this GuardrailInput.
        :rtype: List[str]
        """
        return self._keywords

    @keywords.setter
    def keywords(self, keywords: List[str]):
        """Sets the keywords of this GuardrailInput.

        Keywords for search and filtering  # noqa: E501

        :param keywords: The keywords of this GuardrailInput.
        :type keywords: List[str]
        """
        if keywords is not None and len(keywords) > 20:
            raise ValueError("Invalid value for `keywords`, number of items must be less than or equal to `20`")  # noqa: E501

        self._keywords = keywords

    @property
    def examples(self) -> GuardrailAllOfExamples:
        """Gets the examples of this GuardrailInput.


        :return: The examples of this GuardrailInput.
        :rtype: GuardrailAllOfExamples
        """
        return self._examples

    @examples.setter
    def examples(self, examples: GuardrailAllOfExamples):
        """Sets the examples of this GuardrailInput.


        :param examples: The examples of this GuardrailInput.
        :type examples: GuardrailAllOfExamples
        """

        self._examples = examples
