from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class GuardrailAllOfExamples(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, good=None, bad=None):  # noqa: E501
        """GuardrailAllOfExamples - a model defined in OpenAPI

        :param good: The good of this GuardrailAllOfExamples.  # noqa: E501
        :type good: List[str]
        :param bad: The bad of this GuardrailAllOfExamples.  # noqa: E501
        :type bad: List[str]
        """
        self.openapi_types = {
            'good': List[str],
            'bad': List[str]
        }

        self.attribute_map = {
            'good': 'good',
            'bad': 'bad'
        }

        self._good = good
        self._bad = bad

    @classmethod
    def from_dict(cls, dikt) -> 'GuardrailAllOfExamples':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Guardrail_allOf_examples of this GuardrailAllOfExamples.  # noqa: E501
        :rtype: GuardrailAllOfExamples
        """
        return util.deserialize_model(dikt, cls)

    @property
    def good(self) -> List[str]:
        """Gets the good of this GuardrailAllOfExamples.

        Examples of good behavior  # noqa: E501

        :return: The good of this GuardrailAllOfExamples.
        :rtype: List[str]
        """
        return self._good

    @good.setter
    def good(self, good: List[str]):
        """Sets the good of this GuardrailAllOfExamples.

        Examples of good behavior  # noqa: E501

        :param good: The good of this GuardrailAllOfExamples.
        :type good: List[str]
        """

        self._good = good

    @property
    def bad(self) -> List[str]:
        """Gets the bad of this GuardrailAllOfExamples.

        Examples of behavior to avoid  # noqa: E501

        :return: The bad of this GuardrailAllOfExamples.
        :rtype: List[str]
        """
        return self._bad

    @bad.setter
    def bad(self, bad: List[str]):
        """Sets the bad of this GuardrailAllOfExamples.

        Examples of behavior to avoid  # noqa: E501

        :param bad: The bad of this GuardrailAllOfExamples.
        :type bad: List[str]
        """

        self._bad = bad
