from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.guardrail_response import GuardrailResponse
from openapi_server import util

from openapi_server.models.guardrail_response import GuardrailResponse  # noqa: E501

class GuardrailListResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, guardrails=None, total=None):  # noqa: E501
        """GuardrailListResponse - a model defined in OpenAPI

        :param guardrails: The guardrails of this GuardrailListResponse.  # noqa: E501
        :type guardrails: List[GuardrailResponse]
        :param total: The total of this GuardrailListResponse.  # noqa: E501
        :type total: int
        """
        self.openapi_types = {
            'guardrails': List[GuardrailResponse],
            'total': int
        }

        self.attribute_map = {
            'guardrails': 'guardrails',
            'total': 'total'
        }

        self._guardrails = guardrails
        self._total = total

    @classmethod
    def from_dict(cls, dikt) -> 'GuardrailListResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GuardrailListResponse of this GuardrailListResponse.  # noqa: E501
        :rtype: GuardrailListResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def guardrails(self) -> List[GuardrailResponse]:
        """Gets the guardrails of this GuardrailListResponse.


        :return: The guardrails of this GuardrailListResponse.
        :rtype: List[GuardrailResponse]
        """
        return self._guardrails

    @guardrails.setter
    def guardrails(self, guardrails: List[GuardrailResponse]):
        """Sets the guardrails of this GuardrailListResponse.


        :param guardrails: The guardrails of this GuardrailListResponse.
        :type guardrails: List[GuardrailResponse]
        """

        self._guardrails = guardrails

    @property
    def total(self) -> int:
        """Gets the total of this GuardrailListResponse.


        :return: The total of this GuardrailListResponse.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total: int):
        """Sets the total of this GuardrailListResponse.


        :param total: The total of this GuardrailListResponse.
        :type total: int
        """

        self._total = total
