from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class KnowledgeFileResponseContentValidation(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, safe=None, educational=None, age_appropriate=None):  # noqa: E501
        """KnowledgeFileResponseContentValidation - a model defined in OpenAPI

        :param safe: The safe of this KnowledgeFileResponseContentValidation.  # noqa: E501
        :type safe: bool
        :param educational: The educational of this KnowledgeFileResponseContentValidation.  # noqa: E501
        :type educational: bool
        :param age_appropriate: The age_appropriate of this KnowledgeFileResponseContentValidation.  # noqa: E501
        :type age_appropriate: bool
        """
        self.openapi_types = {
            'safe': bool,
            'educational': bool,
            'age_appropriate': bool
        }

        self.attribute_map = {
            'safe': 'safe',
            'educational': 'educational',
            'age_appropriate': 'ageAppropriate'
        }

        self._safe = safe
        self._educational = educational
        self._age_appropriate = age_appropriate

    @classmethod
    def from_dict(cls, dikt) -> 'KnowledgeFileResponseContentValidation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The KnowledgeFileResponse_contentValidation of this KnowledgeFileResponseContentValidation.  # noqa: E501
        :rtype: KnowledgeFileResponseContentValidation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def safe(self) -> bool:
        """Gets the safe of this KnowledgeFileResponseContentValidation.


        :return: The safe of this KnowledgeFileResponseContentValidation.
        :rtype: bool
        """
        return self._safe

    @safe.setter
    def safe(self, safe: bool):
        """Sets the safe of this KnowledgeFileResponseContentValidation.


        :param safe: The safe of this KnowledgeFileResponseContentValidation.
        :type safe: bool
        """

        self._safe = safe

    @property
    def educational(self) -> bool:
        """Gets the educational of this KnowledgeFileResponseContentValidation.


        :return: The educational of this KnowledgeFileResponseContentValidation.
        :rtype: bool
        """
        return self._educational

    @educational.setter
    def educational(self, educational: bool):
        """Sets the educational of this KnowledgeFileResponseContentValidation.


        :param educational: The educational of this KnowledgeFileResponseContentValidation.
        :type educational: bool
        """

        self._educational = educational

    @property
    def age_appropriate(self) -> bool:
        """Gets the age_appropriate of this KnowledgeFileResponseContentValidation.


        :return: The age_appropriate of this KnowledgeFileResponseContentValidation.
        :rtype: bool
        """
        return self._age_appropriate

    @age_appropriate.setter
    def age_appropriate(self, age_appropriate: bool):
        """Sets the age_appropriate of this KnowledgeFileResponseContentValidation.


        :param age_appropriate: The age_appropriate of this KnowledgeFileResponseContentValidation.
        :type age_appropriate: bool
        """

        self._age_appropriate = age_appropriate
