from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ListAnimalDocuments200ResponseDocumentsInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, document_id=None, file_id=None, file_name=None, status=None, uploaded_at=None):  # noqa: E501
        """ListAnimalDocuments200ResponseDocumentsInner - a model defined in OpenAPI

        :param document_id: The document_id of this ListAnimalDocuments200ResponseDocumentsInner.  # noqa: E501
        :type document_id: str
        :param file_id: The file_id of this ListAnimalDocuments200ResponseDocumentsInner.  # noqa: E501
        :type file_id: str
        :param file_name: The file_name of this ListAnimalDocuments200ResponseDocumentsInner.  # noqa: E501
        :type file_name: str
        :param status: The status of this ListAnimalDocuments200ResponseDocumentsInner.  # noqa: E501
        :type status: str
        :param uploaded_at: The uploaded_at of this ListAnimalDocuments200ResponseDocumentsInner.  # noqa: E501
        :type uploaded_at: datetime
        """
        self.openapi_types = {
            'document_id': str,
            'file_id': str,
            'file_name': str,
            'status': str,
            'uploaded_at': datetime
        }

        self.attribute_map = {
            'document_id': 'documentId',
            'file_id': 'fileId',
            'file_name': 'fileName',
            'status': 'status',
            'uploaded_at': 'uploadedAt'
        }

        self._document_id = document_id
        self._file_id = file_id
        self._file_name = file_name
        self._status = status
        self._uploaded_at = uploaded_at

    @classmethod
    def from_dict(cls, dikt) -> 'ListAnimalDocuments200ResponseDocumentsInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The listAnimalDocuments_200_response_documents_inner of this ListAnimalDocuments200ResponseDocumentsInner.  # noqa: E501
        :rtype: ListAnimalDocuments200ResponseDocumentsInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def document_id(self) -> str:
        """Gets the document_id of this ListAnimalDocuments200ResponseDocumentsInner.


        :return: The document_id of this ListAnimalDocuments200ResponseDocumentsInner.
        :rtype: str
        """
        return self._document_id

    @document_id.setter
    def document_id(self, document_id: str):
        """Sets the document_id of this ListAnimalDocuments200ResponseDocumentsInner.


        :param document_id: The document_id of this ListAnimalDocuments200ResponseDocumentsInner.
        :type document_id: str
        """

        self._document_id = document_id

    @property
    def file_id(self) -> str:
        """Gets the file_id of this ListAnimalDocuments200ResponseDocumentsInner.


        :return: The file_id of this ListAnimalDocuments200ResponseDocumentsInner.
        :rtype: str
        """
        return self._file_id

    @file_id.setter
    def file_id(self, file_id: str):
        """Sets the file_id of this ListAnimalDocuments200ResponseDocumentsInner.


        :param file_id: The file_id of this ListAnimalDocuments200ResponseDocumentsInner.
        :type file_id: str
        """

        self._file_id = file_id

    @property
    def file_name(self) -> str:
        """Gets the file_name of this ListAnimalDocuments200ResponseDocumentsInner.


        :return: The file_name of this ListAnimalDocuments200ResponseDocumentsInner.
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name: str):
        """Sets the file_name of this ListAnimalDocuments200ResponseDocumentsInner.


        :param file_name: The file_name of this ListAnimalDocuments200ResponseDocumentsInner.
        :type file_name: str
        """

        self._file_name = file_name

    @property
    def status(self) -> str:
        """Gets the status of this ListAnimalDocuments200ResponseDocumentsInner.


        :return: The status of this ListAnimalDocuments200ResponseDocumentsInner.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this ListAnimalDocuments200ResponseDocumentsInner.


        :param status: The status of this ListAnimalDocuments200ResponseDocumentsInner.
        :type status: str
        """

        self._status = status

    @property
    def uploaded_at(self) -> datetime:
        """Gets the uploaded_at of this ListAnimalDocuments200ResponseDocumentsInner.


        :return: The uploaded_at of this ListAnimalDocuments200ResponseDocumentsInner.
        :rtype: datetime
        """
        return self._uploaded_at

    @uploaded_at.setter
    def uploaded_at(self, uploaded_at: datetime):
        """Sets the uploaded_at of this ListAnimalDocuments200ResponseDocumentsInner.


        :param uploaded_at: The uploaded_at of this ListAnimalDocuments200ResponseDocumentsInner.
        :type uploaded_at: datetime
        """

        self._uploaded_at = uploaded_at
