from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.audit_stamp import AuditStamp
from openapi_server.models.media_all_of_dimensions import MediaAllOfDimensions
import re
from openapi_server import util

from openapi_server.models.audit_stamp import AuditStamp  # noqa: E501
from openapi_server.models.media_all_of_dimensions import MediaAllOfDimensions  # noqa: E501
import re  # noqa: E501

class Media(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, media_id=None, url=None, kind=None, created=None, modified=None, deleted=None, soft_delete=False, title=None, animal_id=None, description=None, tags=None, file_size=None, mime_type=None, duration=None, dimensions=None):  # noqa: E501
        """Media - a model defined in OpenAPI

        :param media_id: The media_id of this Media.  # noqa: E501
        :type media_id: str
        :param url: The url of this Media.  # noqa: E501
        :type url: str
        :param kind: The kind of this Media.  # noqa: E501
        :type kind: str
        :param created: The created of this Media.  # noqa: E501
        :type created: AuditStamp
        :param modified: The modified of this Media.  # noqa: E501
        :type modified: AuditStamp
        :param deleted: The deleted of this Media.  # noqa: E501
        :type deleted: AuditStamp
        :param soft_delete: The soft_delete of this Media.  # noqa: E501
        :type soft_delete: bool
        :param title: The title of this Media.  # noqa: E501
        :type title: str
        :param animal_id: The animal_id of this Media.  # noqa: E501
        :type animal_id: str
        :param description: The description of this Media.  # noqa: E501
        :type description: str
        :param tags: The tags of this Media.  # noqa: E501
        :type tags: List[str]
        :param file_size: The file_size of this Media.  # noqa: E501
        :type file_size: int
        :param mime_type: The mime_type of this Media.  # noqa: E501
        :type mime_type: str
        :param duration: The duration of this Media.  # noqa: E501
        :type duration: float
        :param dimensions: The dimensions of this Media.  # noqa: E501
        :type dimensions: MediaAllOfDimensions
        """
        self.openapi_types = {
            'media_id': str,
            'url': str,
            'kind': str,
            'created': AuditStamp,
            'modified': AuditStamp,
            'deleted': AuditStamp,
            'soft_delete': bool,
            'title': str,
            'animal_id': str,
            'description': str,
            'tags': List[str],
            'file_size': int,
            'mime_type': str,
            'duration': float,
            'dimensions': MediaAllOfDimensions
        }

        self.attribute_map = {
            'media_id': 'mediaId',
            'url': 'url',
            'kind': 'kind',
            'created': 'created',
            'modified': 'modified',
            'deleted': 'deleted',
            'soft_delete': 'softDelete',
            'title': 'title',
            'animal_id': 'animalId',
            'description': 'description',
            'tags': 'tags',
            'file_size': 'fileSize',
            'mime_type': 'mimeType',
            'duration': 'duration',
            'dimensions': 'dimensions'
        }

        self._media_id = media_id
        self._url = url
        self._kind = kind
        self._created = created
        self._modified = modified
        self._deleted = deleted
        self._soft_delete = soft_delete
        self._title = title
        self._animal_id = animal_id
        self._description = description
        self._tags = tags
        self._file_size = file_size
        self._mime_type = mime_type
        self._duration = duration
        self._dimensions = dimensions

    @classmethod
    def from_dict(cls, dikt) -> 'Media':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Media of this Media.  # noqa: E501
        :rtype: Media
        """
        return util.deserialize_model(dikt, cls)

    @property
    def media_id(self) -> str:
        """Gets the media_id of this Media.

        Unique identifier for the media item  # noqa: E501

        :return: The media_id of this Media.
        :rtype: str
        """
        return self._media_id

    @media_id.setter
    def media_id(self, media_id: str):
        """Sets the media_id of this Media.

        Unique identifier for the media item  # noqa: E501

        :param media_id: The media_id of this Media.
        :type media_id: str
        """
        if media_id is None:
            raise ValueError("Invalid value for `media_id`, must not be `None`")  # noqa: E501
        if media_id is not None and not re.search(r'^[a-zA-Z0-9_-]+$', media_id):  # noqa: E501
            raise ValueError(r"Invalid value for `media_id`, must be a follow pattern or equal to `/^[a-zA-Z0-9_-]+$/`")  # noqa: E501

        self._media_id = media_id

    @property
    def url(self) -> str:
        """Gets the url of this Media.

        CDN or storage URL for the media file  # noqa: E501

        :return: The url of this Media.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this Media.

        CDN or storage URL for the media file  # noqa: E501

        :param url: The url of this Media.
        :type url: str
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url

    @property
    def kind(self) -> str:
        """Gets the kind of this Media.

        Type of media content  # noqa: E501

        :return: The kind of this Media.
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind: str):
        """Sets the kind of this Media.

        Type of media content  # noqa: E501

        :param kind: The kind of this Media.
        :type kind: str
        """
        allowed_values = ["image", "audio", "video"]  # noqa: E501
        if kind not in allowed_values:
            raise ValueError(
                "Invalid value for `kind` ({0}), must be one of {1}"
                .format(kind, allowed_values)
            )

        self._kind = kind

    @property
    def created(self) -> AuditStamp:
        """Gets the created of this Media.


        :return: The created of this Media.
        :rtype: AuditStamp
        """
        return self._created

    @created.setter
    def created(self, created: AuditStamp):
        """Sets the created of this Media.


        :param created: The created of this Media.
        :type created: AuditStamp
        """

        self._created = created

    @property
    def modified(self) -> AuditStamp:
        """Gets the modified of this Media.


        :return: The modified of this Media.
        :rtype: AuditStamp
        """
        return self._modified

    @modified.setter
    def modified(self, modified: AuditStamp):
        """Sets the modified of this Media.


        :param modified: The modified of this Media.
        :type modified: AuditStamp
        """

        self._modified = modified

    @property
    def deleted(self) -> AuditStamp:
        """Gets the deleted of this Media.


        :return: The deleted of this Media.
        :rtype: AuditStamp
        """
        return self._deleted

    @deleted.setter
    def deleted(self, deleted: AuditStamp):
        """Sets the deleted of this Media.


        :param deleted: The deleted of this Media.
        :type deleted: AuditStamp
        """

        self._deleted = deleted

    @property
    def soft_delete(self) -> bool:
        """Gets the soft_delete of this Media.


        :return: The soft_delete of this Media.
        :rtype: bool
        """
        return self._soft_delete

    @soft_delete.setter
    def soft_delete(self, soft_delete: bool):
        """Sets the soft_delete of this Media.


        :param soft_delete: The soft_delete of this Media.
        :type soft_delete: bool
        """

        self._soft_delete = soft_delete

    @property
    def title(self) -> str:
        """Gets the title of this Media.

        Human-readable title for the media  # noqa: E501

        :return: The title of this Media.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Media.

        Human-readable title for the media  # noqa: E501

        :param title: The title of this Media.
        :type title: str
        """
        if title is not None and len(title) > 200:
            raise ValueError("Invalid value for `title`, length must be less than or equal to `200`")  # noqa: E501
        if title is not None and len(title) < 1:
            raise ValueError("Invalid value for `title`, length must be greater than or equal to `1`")  # noqa: E501

        self._title = title

    @property
    def animal_id(self) -> str:
        """Gets the animal_id of this Media.

        Associated animal identifier  # noqa: E501

        :return: The animal_id of this Media.
        :rtype: str
        """
        return self._animal_id

    @animal_id.setter
    def animal_id(self, animal_id: str):
        """Sets the animal_id of this Media.

        Associated animal identifier  # noqa: E501

        :param animal_id: The animal_id of this Media.
        :type animal_id: str
        """
        if animal_id is not None and not re.search(r'^[a-zA-Z0-9_-]+$', animal_id):  # noqa: E501
            raise ValueError(r"Invalid value for `animal_id`, must be a follow pattern or equal to `/^[a-zA-Z0-9_-]+$/`")  # noqa: E501

        self._animal_id = animal_id

    @property
    def description(self) -> str:
        """Gets the description of this Media.

        Optional description or context for the media  # noqa: E501

        :return: The description of this Media.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Media.

        Optional description or context for the media  # noqa: E501

        :param description: The description of this Media.
        :type description: str
        """
        if description is not None and len(description) > 1000:
            raise ValueError("Invalid value for `description`, length must be less than or equal to `1000`")  # noqa: E501

        self._description = description

    @property
    def tags(self) -> List[str]:
        """Gets the tags of this Media.

        Optional metadata tags for categorization  # noqa: E501

        :return: The tags of this Media.
        :rtype: List[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags: List[str]):
        """Sets the tags of this Media.

        Optional metadata tags for categorization  # noqa: E501

        :param tags: The tags of this Media.
        :type tags: List[str]
        """
        if tags is not None and len(tags) > 10:
            raise ValueError("Invalid value for `tags`, number of items must be less than or equal to `10`")  # noqa: E501

        self._tags = tags

    @property
    def file_size(self) -> int:
        """Gets the file_size of this Media.

        File size in bytes (max 100MB)  # noqa: E501

        :return: The file_size of this Media.
        :rtype: int
        """
        return self._file_size

    @file_size.setter
    def file_size(self, file_size: int):
        """Sets the file_size of this Media.

        File size in bytes (max 100MB)  # noqa: E501

        :param file_size: The file_size of this Media.
        :type file_size: int
        """
        if file_size is not None and file_size > 104857600:  # noqa: E501
            raise ValueError("Invalid value for `file_size`, must be a value less than or equal to `104857600`")  # noqa: E501
        if file_size is not None and file_size < 1:  # noqa: E501
            raise ValueError("Invalid value for `file_size`, must be a value greater than or equal to `1`")  # noqa: E501

        self._file_size = file_size

    @property
    def mime_type(self) -> str:
        """Gets the mime_type of this Media.

        MIME type of the media file (validated against supported types)  # noqa: E501

        :return: The mime_type of this Media.
        :rtype: str
        """
        return self._mime_type

    @mime_type.setter
    def mime_type(self, mime_type: str):
        """Sets the mime_type of this Media.

        MIME type of the media file (validated against supported types)  # noqa: E501

        :param mime_type: The mime_type of this Media.
        :type mime_type: str
        """
        allowed_values = [None,"image/jpeg", "image/png", "image/gif", "image/webp", "audio/mpeg", "audio/wav", "audio/ogg", "video/mp4", "video/webm", "video/quicktime"]  # noqa: E501
        if mime_type not in allowed_values:
            raise ValueError(
                "Invalid value for `mime_type` ({0}), must be one of {1}"
                .format(mime_type, allowed_values)
            )

        self._mime_type = mime_type

    @property
    def duration(self) -> float:
        """Gets the duration of this Media.

        Duration in seconds (for audio/video)  # noqa: E501

        :return: The duration of this Media.
        :rtype: float
        """
        return self._duration

    @duration.setter
    def duration(self, duration: float):
        """Sets the duration of this Media.

        Duration in seconds (for audio/video)  # noqa: E501

        :param duration: The duration of this Media.
        :type duration: float
        """
        if duration is not None and duration < 0:  # noqa: E501
            raise ValueError("Invalid value for `duration`, must be a value greater than or equal to `0`")  # noqa: E501

        self._duration = duration

    @property
    def dimensions(self) -> MediaAllOfDimensions:
        """Gets the dimensions of this Media.


        :return: The dimensions of this Media.
        :rtype: MediaAllOfDimensions
        """
        return self._dimensions

    @dimensions.setter
    def dimensions(self, dimensions: MediaAllOfDimensions):
        """Sets the dimensions of this Media.


        :param dimensions: The dimensions of this Media.
        :type dimensions: MediaAllOfDimensions
        """

        self._dimensions = dimensions
