from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class PerformanceMetricsTotals(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, requests=None, tokens_prompt=None, tokens_completion=None, cost_usd=None):  # noqa: E501
        """PerformanceMetricsTotals - a model defined in OpenAPI

        :param requests: The requests of this PerformanceMetricsTotals.  # noqa: E501
        :type requests: int
        :param tokens_prompt: The tokens_prompt of this PerformanceMetricsTotals.  # noqa: E501
        :type tokens_prompt: int
        :param tokens_completion: The tokens_completion of this PerformanceMetricsTotals.  # noqa: E501
        :type tokens_completion: int
        :param cost_usd: The cost_usd of this PerformanceMetricsTotals.  # noqa: E501
        :type cost_usd: float
        """
        self.openapi_types = {
            'requests': int,
            'tokens_prompt': int,
            'tokens_completion': int,
            'cost_usd': float
        }

        self.attribute_map = {
            'requests': 'requests',
            'tokens_prompt': 'tokensPrompt',
            'tokens_completion': 'tokensCompletion',
            'cost_usd': 'costUsd'
        }

        self._requests = requests
        self._tokens_prompt = tokens_prompt
        self._tokens_completion = tokens_completion
        self._cost_usd = cost_usd

    @classmethod
    def from_dict(cls, dikt) -> 'PerformanceMetricsTotals':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PerformanceMetrics_totals of this PerformanceMetricsTotals.  # noqa: E501
        :rtype: PerformanceMetricsTotals
        """
        return util.deserialize_model(dikt, cls)

    @property
    def requests(self) -> int:
        """Gets the requests of this PerformanceMetricsTotals.


        :return: The requests of this PerformanceMetricsTotals.
        :rtype: int
        """
        return self._requests

    @requests.setter
    def requests(self, requests: int):
        """Sets the requests of this PerformanceMetricsTotals.


        :param requests: The requests of this PerformanceMetricsTotals.
        :type requests: int
        """

        self._requests = requests

    @property
    def tokens_prompt(self) -> int:
        """Gets the tokens_prompt of this PerformanceMetricsTotals.


        :return: The tokens_prompt of this PerformanceMetricsTotals.
        :rtype: int
        """
        return self._tokens_prompt

    @tokens_prompt.setter
    def tokens_prompt(self, tokens_prompt: int):
        """Sets the tokens_prompt of this PerformanceMetricsTotals.


        :param tokens_prompt: The tokens_prompt of this PerformanceMetricsTotals.
        :type tokens_prompt: int
        """

        self._tokens_prompt = tokens_prompt

    @property
    def tokens_completion(self) -> int:
        """Gets the tokens_completion of this PerformanceMetricsTotals.


        :return: The tokens_completion of this PerformanceMetricsTotals.
        :rtype: int
        """
        return self._tokens_completion

    @tokens_completion.setter
    def tokens_completion(self, tokens_completion: int):
        """Sets the tokens_completion of this PerformanceMetricsTotals.


        :param tokens_completion: The tokens_completion of this PerformanceMetricsTotals.
        :type tokens_completion: int
        """

        self._tokens_completion = tokens_completion

    @property
    def cost_usd(self) -> float:
        """Gets the cost_usd of this PerformanceMetricsTotals.


        :return: The cost_usd of this PerformanceMetricsTotals.
        :rtype: float
        """
        return self._cost_usd

    @cost_usd.setter
    def cost_usd(self, cost_usd: float):
        """Sets the cost_usd of this PerformanceMetricsTotals.


        :param cost_usd: The cost_usd of this PerformanceMetricsTotals.
        :type cost_usd: float
        """

        self._cost_usd = cost_usd
