from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class PrivacyDeleteUser200ResponseItemsDeleted(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, conversations=None, context_entries=None, analytics_records=None):  # noqa: E501
        """PrivacyDeleteUser200ResponseItemsDeleted - a model defined in OpenAPI

        :param conversations: The conversations of this PrivacyDeleteUser200ResponseItemsDeleted.  # noqa: E501
        :type conversations: int
        :param context_entries: The context_entries of this PrivacyDeleteUser200ResponseItemsDeleted.  # noqa: E501
        :type context_entries: int
        :param analytics_records: The analytics_records of this PrivacyDeleteUser200ResponseItemsDeleted.  # noqa: E501
        :type analytics_records: int
        """
        self.openapi_types = {
            'conversations': int,
            'context_entries': int,
            'analytics_records': int
        }

        self.attribute_map = {
            'conversations': 'conversations',
            'context_entries': 'contextEntries',
            'analytics_records': 'analyticsRecords'
        }

        self._conversations = conversations
        self._context_entries = context_entries
        self._analytics_records = analytics_records

    @classmethod
    def from_dict(cls, dikt) -> 'PrivacyDeleteUser200ResponseItemsDeleted':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The privacy_delete_user_200_response_itemsDeleted of this PrivacyDeleteUser200ResponseItemsDeleted.  # noqa: E501
        :rtype: PrivacyDeleteUser200ResponseItemsDeleted
        """
        return util.deserialize_model(dikt, cls)

    @property
    def conversations(self) -> int:
        """Gets the conversations of this PrivacyDeleteUser200ResponseItemsDeleted.


        :return: The conversations of this PrivacyDeleteUser200ResponseItemsDeleted.
        :rtype: int
        """
        return self._conversations

    @conversations.setter
    def conversations(self, conversations: int):
        """Sets the conversations of this PrivacyDeleteUser200ResponseItemsDeleted.


        :param conversations: The conversations of this PrivacyDeleteUser200ResponseItemsDeleted.
        :type conversations: int
        """

        self._conversations = conversations

    @property
    def context_entries(self) -> int:
        """Gets the context_entries of this PrivacyDeleteUser200ResponseItemsDeleted.


        :return: The context_entries of this PrivacyDeleteUser200ResponseItemsDeleted.
        :rtype: int
        """
        return self._context_entries

    @context_entries.setter
    def context_entries(self, context_entries: int):
        """Sets the context_entries of this PrivacyDeleteUser200ResponseItemsDeleted.


        :param context_entries: The context_entries of this PrivacyDeleteUser200ResponseItemsDeleted.
        :type context_entries: int
        """

        self._context_entries = context_entries

    @property
    def analytics_records(self) -> int:
        """Gets the analytics_records of this PrivacyDeleteUser200ResponseItemsDeleted.


        :return: The analytics_records of this PrivacyDeleteUser200ResponseItemsDeleted.
        :rtype: int
        """
        return self._analytics_records

    @analytics_records.setter
    def analytics_records(self, analytics_records: int):
        """Sets the analytics_records of this PrivacyDeleteUser200ResponseItemsDeleted.


        :param analytics_records: The analytics_records of this PrivacyDeleteUser200ResponseItemsDeleted.
        :type analytics_records: int
        """

        self._analytics_records = analytics_records
