from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.privacy_audit_log import PrivacyAuditLog
from openapi_server import util

from openapi_server.models.privacy_audit_log import PrivacyAuditLog  # noqa: E501

class PrivacyAuditGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, audit_entries=None, total_count=None):  # noqa: E501
        """PrivacyAuditGet200Response - a model defined in OpenAPI

        :param audit_entries: The audit_entries of this PrivacyAuditGet200Response.  # noqa: E501
        :type audit_entries: List[PrivacyAuditLog]
        :param total_count: The total_count of this PrivacyAuditGet200Response.  # noqa: E501
        :type total_count: int
        """
        self.openapi_types = {
            'audit_entries': List[PrivacyAuditLog],
            'total_count': int
        }

        self.attribute_map = {
            'audit_entries': 'auditEntries',
            'total_count': 'totalCount'
        }

        self._audit_entries = audit_entries
        self._total_count = total_count

    @classmethod
    def from_dict(cls, dikt) -> 'PrivacyAuditGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The privacy_audit_get_200_response of this PrivacyAuditGet200Response.  # noqa: E501
        :rtype: PrivacyAuditGet200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def audit_entries(self) -> List[PrivacyAuditLog]:
        """Gets the audit_entries of this PrivacyAuditGet200Response.


        :return: The audit_entries of this PrivacyAuditGet200Response.
        :rtype: List[PrivacyAuditLog]
        """
        return self._audit_entries

    @audit_entries.setter
    def audit_entries(self, audit_entries: List[PrivacyAuditLog]):
        """Sets the audit_entries of this PrivacyAuditGet200Response.


        :param audit_entries: The audit_entries of this PrivacyAuditGet200Response.
        :type audit_entries: List[PrivacyAuditLog]
        """

        self._audit_entries = audit_entries

    @property
    def total_count(self) -> int:
        """Gets the total_count of this PrivacyAuditGet200Response.


        :return: The total_count of this PrivacyAuditGet200Response.
        :rtype: int
        """
        return self._total_count

    @total_count.setter
    def total_count(self, total_count: int):
        """Sets the total_count of this PrivacyAuditGet200Response.


        :param total_count: The total_count of this PrivacyAuditGet200Response.
        :type total_count: int
        """

        self._total_count = total_count
