from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class PromoteSandboxRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, animal_id=None):  # noqa: E501
        """PromoteSandboxRequest - a model defined in OpenAPI

        :param animal_id: The animal_id of this PromoteSandboxRequest.  # noqa: E501
        :type animal_id: str
        """
        self.openapi_types = {
            'animal_id': str
        }

        self.attribute_map = {
            'animal_id': 'animalId'
        }

        self._animal_id = animal_id

    @classmethod
    def from_dict(cls, dikt) -> 'PromoteSandboxRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PromoteSandboxRequest of this PromoteSandboxRequest.  # noqa: E501
        :rtype: PromoteSandboxRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def animal_id(self) -> str:
        """Gets the animal_id of this PromoteSandboxRequest.

        Animal ID to create/update assistant for  # noqa: E501

        :return: The animal_id of this PromoteSandboxRequest.
        :rtype: str
        """
        return self._animal_id

    @animal_id.setter
    def animal_id(self, animal_id: str):
        """Sets the animal_id of this PromoteSandboxRequest.

        Animal ID to create/update assistant for  # noqa: E501

        :param animal_id: The animal_id of this PromoteSandboxRequest.
        :type animal_id: str
        """
        if animal_id is None:
            raise ValueError("Invalid value for `animal_id`, must not be `None`")  # noqa: E501

        self._animal_id = animal_id
