from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.audit_info import AuditInfo
from openapi_server import util

from openapi_server.models.audit_info import AuditInfo  # noqa: E501

class SandboxResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sandbox_id=None, created_by=None, animal_id=None, personality_id=None, guardrail_id=None, merged_prompt=None, knowledge_base_file_ids=None, expires_at=None, conversation_count=None, last_conversation_at=None, is_promoted=None, promoted_at=None, created=None):  # noqa: E501
        """SandboxResponse - a model defined in OpenAPI

        :param sandbox_id: The sandbox_id of this SandboxResponse.  # noqa: E501
        :type sandbox_id: str
        :param created_by: The created_by of this SandboxResponse.  # noqa: E501
        :type created_by: str
        :param animal_id: The animal_id of this SandboxResponse.  # noqa: E501
        :type animal_id: str
        :param personality_id: The personality_id of this SandboxResponse.  # noqa: E501
        :type personality_id: str
        :param guardrail_id: The guardrail_id of this SandboxResponse.  # noqa: E501
        :type guardrail_id: str
        :param merged_prompt: The merged_prompt of this SandboxResponse.  # noqa: E501
        :type merged_prompt: str
        :param knowledge_base_file_ids: The knowledge_base_file_ids of this SandboxResponse.  # noqa: E501
        :type knowledge_base_file_ids: List[str]
        :param expires_at: The expires_at of this SandboxResponse.  # noqa: E501
        :type expires_at: datetime
        :param conversation_count: The conversation_count of this SandboxResponse.  # noqa: E501
        :type conversation_count: int
        :param last_conversation_at: The last_conversation_at of this SandboxResponse.  # noqa: E501
        :type last_conversation_at: datetime
        :param is_promoted: The is_promoted of this SandboxResponse.  # noqa: E501
        :type is_promoted: bool
        :param promoted_at: The promoted_at of this SandboxResponse.  # noqa: E501
        :type promoted_at: datetime
        :param created: The created of this SandboxResponse.  # noqa: E501
        :type created: AuditInfo
        """
        self.openapi_types = {
            'sandbox_id': str,
            'created_by': str,
            'animal_id': str,
            'personality_id': str,
            'guardrail_id': str,
            'merged_prompt': str,
            'knowledge_base_file_ids': List[str],
            'expires_at': datetime,
            'conversation_count': int,
            'last_conversation_at': datetime,
            'is_promoted': bool,
            'promoted_at': datetime,
            'created': AuditInfo
        }

        self.attribute_map = {
            'sandbox_id': 'sandboxId',
            'created_by': 'createdBy',
            'animal_id': 'animalId',
            'personality_id': 'personalityId',
            'guardrail_id': 'guardrailId',
            'merged_prompt': 'mergedPrompt',
            'knowledge_base_file_ids': 'knowledgeBaseFileIds',
            'expires_at': 'expiresAt',
            'conversation_count': 'conversationCount',
            'last_conversation_at': 'lastConversationAt',
            'is_promoted': 'isPromoted',
            'promoted_at': 'promotedAt',
            'created': 'created'
        }

        self._sandbox_id = sandbox_id
        self._created_by = created_by
        self._animal_id = animal_id
        self._personality_id = personality_id
        self._guardrail_id = guardrail_id
        self._merged_prompt = merged_prompt
        self._knowledge_base_file_ids = knowledge_base_file_ids
        self._expires_at = expires_at
        self._conversation_count = conversation_count
        self._last_conversation_at = last_conversation_at
        self._is_promoted = is_promoted
        self._promoted_at = promoted_at
        self._created = created

    @classmethod
    def from_dict(cls, dikt) -> 'SandboxResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SandboxResponse of this SandboxResponse.  # noqa: E501
        :rtype: SandboxResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sandbox_id(self) -> str:
        """Gets the sandbox_id of this SandboxResponse.


        :return: The sandbox_id of this SandboxResponse.
        :rtype: str
        """
        return self._sandbox_id

    @sandbox_id.setter
    def sandbox_id(self, sandbox_id: str):
        """Sets the sandbox_id of this SandboxResponse.


        :param sandbox_id: The sandbox_id of this SandboxResponse.
        :type sandbox_id: str
        """

        self._sandbox_id = sandbox_id

    @property
    def created_by(self) -> str:
        """Gets the created_by of this SandboxResponse.


        :return: The created_by of this SandboxResponse.
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by: str):
        """Sets the created_by of this SandboxResponse.


        :param created_by: The created_by of this SandboxResponse.
        :type created_by: str
        """

        self._created_by = created_by

    @property
    def animal_id(self) -> str:
        """Gets the animal_id of this SandboxResponse.


        :return: The animal_id of this SandboxResponse.
        :rtype: str
        """
        return self._animal_id

    @animal_id.setter
    def animal_id(self, animal_id: str):
        """Sets the animal_id of this SandboxResponse.


        :param animal_id: The animal_id of this SandboxResponse.
        :type animal_id: str
        """

        self._animal_id = animal_id

    @property
    def personality_id(self) -> str:
        """Gets the personality_id of this SandboxResponse.


        :return: The personality_id of this SandboxResponse.
        :rtype: str
        """
        return self._personality_id

    @personality_id.setter
    def personality_id(self, personality_id: str):
        """Sets the personality_id of this SandboxResponse.


        :param personality_id: The personality_id of this SandboxResponse.
        :type personality_id: str
        """

        self._personality_id = personality_id

    @property
    def guardrail_id(self) -> str:
        """Gets the guardrail_id of this SandboxResponse.


        :return: The guardrail_id of this SandboxResponse.
        :rtype: str
        """
        return self._guardrail_id

    @guardrail_id.setter
    def guardrail_id(self, guardrail_id: str):
        """Sets the guardrail_id of this SandboxResponse.


        :param guardrail_id: The guardrail_id of this SandboxResponse.
        :type guardrail_id: str
        """

        self._guardrail_id = guardrail_id

    @property
    def merged_prompt(self) -> str:
        """Gets the merged_prompt of this SandboxResponse.


        :return: The merged_prompt of this SandboxResponse.
        :rtype: str
        """
        return self._merged_prompt

    @merged_prompt.setter
    def merged_prompt(self, merged_prompt: str):
        """Sets the merged_prompt of this SandboxResponse.


        :param merged_prompt: The merged_prompt of this SandboxResponse.
        :type merged_prompt: str
        """

        self._merged_prompt = merged_prompt

    @property
    def knowledge_base_file_ids(self) -> List[str]:
        """Gets the knowledge_base_file_ids of this SandboxResponse.


        :return: The knowledge_base_file_ids of this SandboxResponse.
        :rtype: List[str]
        """
        return self._knowledge_base_file_ids

    @knowledge_base_file_ids.setter
    def knowledge_base_file_ids(self, knowledge_base_file_ids: List[str]):
        """Sets the knowledge_base_file_ids of this SandboxResponse.


        :param knowledge_base_file_ids: The knowledge_base_file_ids of this SandboxResponse.
        :type knowledge_base_file_ids: List[str]
        """

        self._knowledge_base_file_ids = knowledge_base_file_ids

    @property
    def expires_at(self) -> datetime:
        """Gets the expires_at of this SandboxResponse.

        Expiration time (30 minutes from creation)  # noqa: E501

        :return: The expires_at of this SandboxResponse.
        :rtype: datetime
        """
        return self._expires_at

    @expires_at.setter
    def expires_at(self, expires_at: datetime):
        """Sets the expires_at of this SandboxResponse.

        Expiration time (30 minutes from creation)  # noqa: E501

        :param expires_at: The expires_at of this SandboxResponse.
        :type expires_at: datetime
        """

        self._expires_at = expires_at

    @property
    def conversation_count(self) -> int:
        """Gets the conversation_count of this SandboxResponse.

        Number of test conversations  # noqa: E501

        :return: The conversation_count of this SandboxResponse.
        :rtype: int
        """
        return self._conversation_count

    @conversation_count.setter
    def conversation_count(self, conversation_count: int):
        """Sets the conversation_count of this SandboxResponse.

        Number of test conversations  # noqa: E501

        :param conversation_count: The conversation_count of this SandboxResponse.
        :type conversation_count: int
        """

        self._conversation_count = conversation_count

    @property
    def last_conversation_at(self) -> datetime:
        """Gets the last_conversation_at of this SandboxResponse.


        :return: The last_conversation_at of this SandboxResponse.
        :rtype: datetime
        """
        return self._last_conversation_at

    @last_conversation_at.setter
    def last_conversation_at(self, last_conversation_at: datetime):
        """Sets the last_conversation_at of this SandboxResponse.


        :param last_conversation_at: The last_conversation_at of this SandboxResponse.
        :type last_conversation_at: datetime
        """

        self._last_conversation_at = last_conversation_at

    @property
    def is_promoted(self) -> bool:
        """Gets the is_promoted of this SandboxResponse.


        :return: The is_promoted of this SandboxResponse.
        :rtype: bool
        """
        return self._is_promoted

    @is_promoted.setter
    def is_promoted(self, is_promoted: bool):
        """Sets the is_promoted of this SandboxResponse.


        :param is_promoted: The is_promoted of this SandboxResponse.
        :type is_promoted: bool
        """

        self._is_promoted = is_promoted

    @property
    def promoted_at(self) -> datetime:
        """Gets the promoted_at of this SandboxResponse.


        :return: The promoted_at of this SandboxResponse.
        :rtype: datetime
        """
        return self._promoted_at

    @promoted_at.setter
    def promoted_at(self, promoted_at: datetime):
        """Sets the promoted_at of this SandboxResponse.


        :param promoted_at: The promoted_at of this SandboxResponse.
        :type promoted_at: datetime
        """

        self._promoted_at = promoted_at

    @property
    def created(self) -> AuditInfo:
        """Gets the created of this SandboxResponse.


        :return: The created of this SandboxResponse.
        :rtype: AuditInfo
        """
        return self._created

    @created.setter
    def created(self, created: AuditInfo):
        """Sets the created of this SandboxResponse.


        :param created: The created of this SandboxResponse.
        :type created: AuditInfo
        """

        self._created = created
