from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class SummarizeConvoPost200ResponseSentiment(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, overall=None, confidence=None, progression=None):  # noqa: E501
        """SummarizeConvoPost200ResponseSentiment - a model defined in OpenAPI

        :param overall: The overall of this SummarizeConvoPost200ResponseSentiment.  # noqa: E501
        :type overall: str
        :param confidence: The confidence of this SummarizeConvoPost200ResponseSentiment.  # noqa: E501
        :type confidence: float
        :param progression: The progression of this SummarizeConvoPost200ResponseSentiment.  # noqa: E501
        :type progression: List[str]
        """
        self.openapi_types = {
            'overall': str,
            'confidence': float,
            'progression': List[str]
        }

        self.attribute_map = {
            'overall': 'overall',
            'confidence': 'confidence',
            'progression': 'progression'
        }

        self._overall = overall
        self._confidence = confidence
        self._progression = progression

    @classmethod
    def from_dict(cls, dikt) -> 'SummarizeConvoPost200ResponseSentiment':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _summarize_convo_post_200_response_sentiment of this SummarizeConvoPost200ResponseSentiment.  # noqa: E501
        :rtype: SummarizeConvoPost200ResponseSentiment
        """
        return util.deserialize_model(dikt, cls)

    @property
    def overall(self) -> str:
        """Gets the overall of this SummarizeConvoPost200ResponseSentiment.


        :return: The overall of this SummarizeConvoPost200ResponseSentiment.
        :rtype: str
        """
        return self._overall

    @overall.setter
    def overall(self, overall: str):
        """Sets the overall of this SummarizeConvoPost200ResponseSentiment.


        :param overall: The overall of this SummarizeConvoPost200ResponseSentiment.
        :type overall: str
        """
        allowed_values = ["positive", "neutral", "negative"]  # noqa: E501
        if overall not in allowed_values:
            raise ValueError(
                "Invalid value for `overall` ({0}), must be one of {1}"
                .format(overall, allowed_values)
            )

        self._overall = overall

    @property
    def confidence(self) -> float:
        """Gets the confidence of this SummarizeConvoPost200ResponseSentiment.


        :return: The confidence of this SummarizeConvoPost200ResponseSentiment.
        :rtype: float
        """
        return self._confidence

    @confidence.setter
    def confidence(self, confidence: float):
        """Sets the confidence of this SummarizeConvoPost200ResponseSentiment.


        :param confidence: The confidence of this SummarizeConvoPost200ResponseSentiment.
        :type confidence: float
        """
        if confidence is not None and confidence > 1:  # noqa: E501
            raise ValueError("Invalid value for `confidence`, must be a value less than or equal to `1`")  # noqa: E501
        if confidence is not None and confidence < 0:  # noqa: E501
            raise ValueError("Invalid value for `confidence`, must be a value greater than or equal to `0`")  # noqa: E501

        self._confidence = confidence

    @property
    def progression(self) -> List[str]:
        """Gets the progression of this SummarizeConvoPost200ResponseSentiment.


        :return: The progression of this SummarizeConvoPost200ResponseSentiment.
        :rtype: List[str]
        """
        return self._progression

    @progression.setter
    def progression(self, progression: List[str]):
        """Sets the progression of this SummarizeConvoPost200ResponseSentiment.


        :param progression: The progression of this SummarizeConvoPost200ResponseSentiment.
        :type progression: List[str]
        """

        self._progression = progression
