from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class SummarizeRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, session_id=None, max_chars=2000):  # noqa: E501
        """SummarizeRequest - a model defined in OpenAPI

        :param session_id: The session_id of this SummarizeRequest.  # noqa: E501
        :type session_id: str
        :param max_chars: The max_chars of this SummarizeRequest.  # noqa: E501
        :type max_chars: int
        """
        self.openapi_types = {
            'session_id': str,
            'max_chars': int
        }

        self.attribute_map = {
            'session_id': 'sessionId',
            'max_chars': 'maxChars'
        }

        self._session_id = session_id
        self._max_chars = max_chars

    @classmethod
    def from_dict(cls, dikt) -> 'SummarizeRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SummarizeRequest of this SummarizeRequest.  # noqa: E501
        :rtype: SummarizeRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def session_id(self) -> str:
        """Gets the session_id of this SummarizeRequest.


        :return: The session_id of this SummarizeRequest.
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id: str):
        """Sets the session_id of this SummarizeRequest.


        :param session_id: The session_id of this SummarizeRequest.
        :type session_id: str
        """
        if session_id is None:
            raise ValueError("Invalid value for `session_id`, must not be `None`")  # noqa: E501

        self._session_id = session_id

    @property
    def max_chars(self) -> int:
        """Gets the max_chars of this SummarizeRequest.


        :return: The max_chars of this SummarizeRequest.
        :rtype: int
        """
        return self._max_chars

    @max_chars.setter
    def max_chars(self, max_chars: int):
        """Sets the max_chars of this SummarizeRequest.


        :param max_chars: The max_chars of this SummarizeRequest.
        :type max_chars: int
        """

        self._max_chars = max_chars
