from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.summarize_convo_post200_response_metrics import SummarizeConvoPost200ResponseMetrics
from openapi_server.models.summarize_convo_post200_response_sentiment import SummarizeConvoPost200ResponseSentiment
from openapi_server import util

from openapi_server.models.summarize_convo_post200_response_metrics import SummarizeConvoPost200ResponseMetrics  # noqa: E501
from openapi_server.models.summarize_convo_post200_response_sentiment import SummarizeConvoPost200ResponseSentiment  # noqa: E501

class SummarizeConvoPost200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, session_id=None, summary_type=None, summary=None, topics=None, metrics=None, sentiment=None, personalization_insights=None, generated_at=None):  # noqa: E501
        """SummarizeConvoPost200Response - a model defined in OpenAPI

        :param session_id: The session_id of this SummarizeConvoPost200Response.  # noqa: E501
        :type session_id: str
        :param summary_type: The summary_type of this SummarizeConvoPost200Response.  # noqa: E501
        :type summary_type: str
        :param summary: The summary of this SummarizeConvoPost200Response.  # noqa: E501
        :type summary: str
        :param topics: The topics of this SummarizeConvoPost200Response.  # noqa: E501
        :type topics: List[str]
        :param metrics: The metrics of this SummarizeConvoPost200Response.  # noqa: E501
        :type metrics: SummarizeConvoPost200ResponseMetrics
        :param sentiment: The sentiment of this SummarizeConvoPost200Response.  # noqa: E501
        :type sentiment: SummarizeConvoPost200ResponseSentiment
        :param personalization_insights: The personalization_insights of this SummarizeConvoPost200Response.  # noqa: E501
        :type personalization_insights: Dict[str, str]
        :param generated_at: The generated_at of this SummarizeConvoPost200Response.  # noqa: E501
        :type generated_at: datetime
        """
        self.openapi_types = {
            'session_id': str,
            'summary_type': str,
            'summary': str,
            'topics': List[str],
            'metrics': SummarizeConvoPost200ResponseMetrics,
            'sentiment': SummarizeConvoPost200ResponseSentiment,
            'personalization_insights': Dict[str, str],
            'generated_at': datetime
        }

        self.attribute_map = {
            'session_id': 'sessionId',
            'summary_type': 'summaryType',
            'summary': 'summary',
            'topics': 'topics',
            'metrics': 'metrics',
            'sentiment': 'sentiment',
            'personalization_insights': 'personalizationInsights',
            'generated_at': 'generatedAt'
        }

        self._session_id = session_id
        self._summary_type = summary_type
        self._summary = summary
        self._topics = topics
        self._metrics = metrics
        self._sentiment = sentiment
        self._personalization_insights = personalization_insights
        self._generated_at = generated_at

    @classmethod
    def from_dict(cls, dikt) -> 'SummarizeConvoPost200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _summarize_convo_post_200_response of this SummarizeConvoPost200Response.  # noqa: E501
        :rtype: SummarizeConvoPost200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def session_id(self) -> str:
        """Gets the session_id of this SummarizeConvoPost200Response.

        Original session identifier  # noqa: E501

        :return: The session_id of this SummarizeConvoPost200Response.
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id: str):
        """Sets the session_id of this SummarizeConvoPost200Response.

        Original session identifier  # noqa: E501

        :param session_id: The session_id of this SummarizeConvoPost200Response.
        :type session_id: str
        """

        self._session_id = session_id

    @property
    def summary_type(self) -> str:
        """Gets the summary_type of this SummarizeConvoPost200Response.

        Type of summary generated  # noqa: E501

        :return: The summary_type of this SummarizeConvoPost200Response.
        :rtype: str
        """
        return self._summary_type

    @summary_type.setter
    def summary_type(self, summary_type: str):
        """Sets the summary_type of this SummarizeConvoPost200Response.

        Type of summary generated  # noqa: E501

        :param summary_type: The summary_type of this SummarizeConvoPost200Response.
        :type summary_type: str
        """

        self._summary_type = summary_type

    @property
    def summary(self) -> str:
        """Gets the summary of this SummarizeConvoPost200Response.

        Generated conversation summary  # noqa: E501

        :return: The summary of this SummarizeConvoPost200Response.
        :rtype: str
        """
        return self._summary

    @summary.setter
    def summary(self, summary: str):
        """Sets the summary of this SummarizeConvoPost200Response.

        Generated conversation summary  # noqa: E501

        :param summary: The summary of this SummarizeConvoPost200Response.
        :type summary: str
        """

        self._summary = summary

    @property
    def topics(self) -> List[str]:
        """Gets the topics of this SummarizeConvoPost200Response.

        Main topics discussed  # noqa: E501

        :return: The topics of this SummarizeConvoPost200Response.
        :rtype: List[str]
        """
        return self._topics

    @topics.setter
    def topics(self, topics: List[str]):
        """Sets the topics of this SummarizeConvoPost200Response.

        Main topics discussed  # noqa: E501

        :param topics: The topics of this SummarizeConvoPost200Response.
        :type topics: List[str]
        """

        self._topics = topics

    @property
    def metrics(self) -> SummarizeConvoPost200ResponseMetrics:
        """Gets the metrics of this SummarizeConvoPost200Response.


        :return: The metrics of this SummarizeConvoPost200Response.
        :rtype: SummarizeConvoPost200ResponseMetrics
        """
        return self._metrics

    @metrics.setter
    def metrics(self, metrics: SummarizeConvoPost200ResponseMetrics):
        """Sets the metrics of this SummarizeConvoPost200Response.


        :param metrics: The metrics of this SummarizeConvoPost200Response.
        :type metrics: SummarizeConvoPost200ResponseMetrics
        """

        self._metrics = metrics

    @property
    def sentiment(self) -> SummarizeConvoPost200ResponseSentiment:
        """Gets the sentiment of this SummarizeConvoPost200Response.


        :return: The sentiment of this SummarizeConvoPost200Response.
        :rtype: SummarizeConvoPost200ResponseSentiment
        """
        return self._sentiment

    @sentiment.setter
    def sentiment(self, sentiment: SummarizeConvoPost200ResponseSentiment):
        """Sets the sentiment of this SummarizeConvoPost200Response.


        :param sentiment: The sentiment of this SummarizeConvoPost200Response.
        :type sentiment: SummarizeConvoPost200ResponseSentiment
        """

        self._sentiment = sentiment

    @property
    def personalization_insights(self) -> Dict[str, str]:
        """Gets the personalization_insights of this SummarizeConvoPost200Response.

        Extracted personalization insights  # noqa: E501

        :return: The personalization_insights of this SummarizeConvoPost200Response.
        :rtype: Dict[str, str]
        """
        return self._personalization_insights

    @personalization_insights.setter
    def personalization_insights(self, personalization_insights: Dict[str, str]):
        """Sets the personalization_insights of this SummarizeConvoPost200Response.

        Extracted personalization insights  # noqa: E501

        :param personalization_insights: The personalization_insights of this SummarizeConvoPost200Response.
        :type personalization_insights: Dict[str, str]
        """

        self._personalization_insights = personalization_insights

    @property
    def generated_at(self) -> datetime:
        """Gets the generated_at of this SummarizeConvoPost200Response.

        When summary was generated  # noqa: E501

        :return: The generated_at of this SummarizeConvoPost200Response.
        :rtype: datetime
        """
        return self._generated_at

    @generated_at.setter
    def generated_at(self, generated_at: datetime):
        """Sets the generated_at of this SummarizeConvoPost200Response.

        When summary was generated  # noqa: E501

        :param generated_at: The generated_at of this SummarizeConvoPost200Response.
        :type generated_at: datetime
        """

        self._generated_at = generated_at
