from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class SystemHealthChecksInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, status=None, detail=None):  # noqa: E501
        """SystemHealthChecksInner - a model defined in OpenAPI

        :param name: The name of this SystemHealthChecksInner.  # noqa: E501
        :type name: str
        :param status: The status of this SystemHealthChecksInner.  # noqa: E501
        :type status: str
        :param detail: The detail of this SystemHealthChecksInner.  # noqa: E501
        :type detail: str
        """
        self.openapi_types = {
            'name': str,
            'status': str,
            'detail': str
        }

        self.attribute_map = {
            'name': 'name',
            'status': 'status',
            'detail': 'detail'
        }

        self._name = name
        self._status = status
        self._detail = detail

    @classmethod
    def from_dict(cls, dikt) -> 'SystemHealthChecksInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SystemHealth_checks_inner of this SystemHealthChecksInner.  # noqa: E501
        :rtype: SystemHealthChecksInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this SystemHealthChecksInner.


        :return: The name of this SystemHealthChecksInner.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this SystemHealthChecksInner.


        :param name: The name of this SystemHealthChecksInner.
        :type name: str
        """

        self._name = name

    @property
    def status(self) -> str:
        """Gets the status of this SystemHealthChecksInner.


        :return: The status of this SystemHealthChecksInner.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this SystemHealthChecksInner.


        :param status: The status of this SystemHealthChecksInner.
        :type status: str
        """
        allowed_values = ["ok", "warn", "fail"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def detail(self) -> str:
        """Gets the detail of this SystemHealthChecksInner.


        :return: The detail of this SystemHealthChecksInner.
        :rtype: str
        """
        return self._detail

    @detail.setter
    def detail(self, detail: str):
        """Sets the detail of this SystemHealthChecksInner.


        :param detail: The detail of this SystemHealthChecksInner.
        :type detail: str
        """

        self._detail = detail
