from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class TestStressBody201Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, data=None):  # noqa: E501
        """TestStressBody201Response - a model defined in OpenAPI

        :param id: The id of this TestStressBody201Response.  # noqa: E501
        :type id: str
        :param data: The data of this TestStressBody201Response.  # noqa: E501
        :type data: str
        """
        self.openapi_types = {
            'id': str,
            'data': str
        }

        self.attribute_map = {
            'id': 'id',
            'data': 'data'
        }

        self._id = id
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'TestStressBody201Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The testStressBody_201_response of this TestStressBody201Response.  # noqa: E501
        :rtype: TestStressBody201Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this TestStressBody201Response.


        :return: The id of this TestStressBody201Response.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this TestStressBody201Response.


        :param id: The id of this TestStressBody201Response.
        :type id: str
        """

        self._id = id

    @property
    def data(self) -> str:
        """Gets the data of this TestStressBody201Response.


        :return: The data of this TestStressBody201Response.
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data: str):
        """Sets the data of this TestStressBody201Response.


        :param data: The data of this TestStressBody201Response.
        :type data: str
        """

        self._data = data
