from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
import re
from openapi_server import util

import re  # noqa: E501

class TriggeredRule(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, rule_id=None, rule_text=None, rule_type=None, category=None, severity=None, confidence_score=None, trigger_context=None, user_message=None, detected_at=None, priority=50):  # noqa: E501
        """TriggeredRule - a model defined in OpenAPI

        :param rule_id: The rule_id of this TriggeredRule.  # noqa: E501
        :type rule_id: str
        :param rule_text: The rule_text of this TriggeredRule.  # noqa: E501
        :type rule_text: str
        :param rule_type: The rule_type of this TriggeredRule.  # noqa: E501
        :type rule_type: str
        :param category: The category of this TriggeredRule.  # noqa: E501
        :type category: str
        :param severity: The severity of this TriggeredRule.  # noqa: E501
        :type severity: str
        :param confidence_score: The confidence_score of this TriggeredRule.  # noqa: E501
        :type confidence_score: float
        :param trigger_context: The trigger_context of this TriggeredRule.  # noqa: E501
        :type trigger_context: str
        :param user_message: The user_message of this TriggeredRule.  # noqa: E501
        :type user_message: str
        :param detected_at: The detected_at of this TriggeredRule.  # noqa: E501
        :type detected_at: datetime
        :param priority: The priority of this TriggeredRule.  # noqa: E501
        :type priority: int
        """
        self.openapi_types = {
            'rule_id': str,
            'rule_text': str,
            'rule_type': str,
            'category': str,
            'severity': str,
            'confidence_score': float,
            'trigger_context': str,
            'user_message': str,
            'detected_at': datetime,
            'priority': int
        }

        self.attribute_map = {
            'rule_id': 'ruleId',
            'rule_text': 'ruleText',
            'rule_type': 'ruleType',
            'category': 'category',
            'severity': 'severity',
            'confidence_score': 'confidenceScore',
            'trigger_context': 'triggerContext',
            'user_message': 'userMessage',
            'detected_at': 'detectedAt',
            'priority': 'priority'
        }

        self._rule_id = rule_id
        self._rule_text = rule_text
        self._rule_type = rule_type
        self._category = category
        self._severity = severity
        self._confidence_score = confidence_score
        self._trigger_context = trigger_context
        self._user_message = user_message
        self._detected_at = detected_at
        self._priority = priority

    @classmethod
    def from_dict(cls, dikt) -> 'TriggeredRule':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TriggeredRule of this TriggeredRule.  # noqa: E501
        :rtype: TriggeredRule
        """
        return util.deserialize_model(dikt, cls)

    @property
    def rule_id(self) -> str:
        """Gets the rule_id of this TriggeredRule.

        Unique identifier for the guardrail rule  # noqa: E501

        :return: The rule_id of this TriggeredRule.
        :rtype: str
        """
        return self._rule_id

    @rule_id.setter
    def rule_id(self, rule_id: str):
        """Sets the rule_id of this TriggeredRule.

        Unique identifier for the guardrail rule  # noqa: E501

        :param rule_id: The rule_id of this TriggeredRule.
        :type rule_id: str
        """
        if rule_id is None:
            raise ValueError("Invalid value for `rule_id`, must not be `None`")  # noqa: E501
        if rule_id is not None and len(rule_id) > 50:
            raise ValueError("Invalid value for `rule_id`, length must be less than or equal to `50`")  # noqa: E501
        if rule_id is not None and not re.search(r'^rule_[a-z_]+_[0-9]+$', rule_id):  # noqa: E501
            raise ValueError(r"Invalid value for `rule_id`, must be a follow pattern or equal to `/^rule_[a-z_]+_[0-9]+$/`")  # noqa: E501

        self._rule_id = rule_id

    @property
    def rule_text(self) -> str:
        """Gets the rule_text of this TriggeredRule.

        Full text of the guardrail rule  # noqa: E501

        :return: The rule_text of this TriggeredRule.
        :rtype: str
        """
        return self._rule_text

    @rule_text.setter
    def rule_text(self, rule_text: str):
        """Sets the rule_text of this TriggeredRule.

        Full text of the guardrail rule  # noqa: E501

        :param rule_text: The rule_text of this TriggeredRule.
        :type rule_text: str
        """
        if rule_text is None:
            raise ValueError("Invalid value for `rule_text`, must not be `None`")  # noqa: E501
        if rule_text is not None and len(rule_text) > 500:
            raise ValueError("Invalid value for `rule_text`, length must be less than or equal to `500`")  # noqa: E501

        self._rule_text = rule_text

    @property
    def rule_type(self) -> str:
        """Gets the rule_type of this TriggeredRule.

        Type of guardrail rule  # noqa: E501

        :return: The rule_type of this TriggeredRule.
        :rtype: str
        """
        return self._rule_type

    @rule_type.setter
    def rule_type(self, rule_type: str):
        """Sets the rule_type of this TriggeredRule.

        Type of guardrail rule  # noqa: E501

        :param rule_type: The rule_type of this TriggeredRule.
        :type rule_type: str
        """
        allowed_values = ["ALWAYS", "NEVER", "ENCOURAGE", "DISCOURAGE"]  # noqa: E501
        if rule_type not in allowed_values:
            raise ValueError(
                "Invalid value for `rule_type` ({0}), must be one of {1}"
                .format(rule_type, allowed_values)
            )

        self._rule_type = rule_type

    @property
    def category(self) -> str:
        """Gets the category of this TriggeredRule.

        Category classification for the rule  # noqa: E501

        :return: The category of this TriggeredRule.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category: str):
        """Sets the category of this TriggeredRule.

        Category classification for the rule  # noqa: E501

        :param category: The category of this TriggeredRule.
        :type category: str
        """
        allowed_values = ["safety", "educational", "age-appropriate", "behavioral", "content-quality", "privacy"]  # noqa: E501
        if category not in allowed_values:
            raise ValueError(
                "Invalid value for `category` ({0}), must be one of {1}"
                .format(category, allowed_values)
            )

        self._category = category

    @property
    def severity(self) -> str:
        """Gets the severity of this TriggeredRule.

        Severity level of rule violation  # noqa: E501

        :return: The severity of this TriggeredRule.
        :rtype: str
        """
        return self._severity

    @severity.setter
    def severity(self, severity: str):
        """Sets the severity of this TriggeredRule.

        Severity level of rule violation  # noqa: E501

        :param severity: The severity of this TriggeredRule.
        :type severity: str
        """
        allowed_values = ["low", "medium", "high", "critical"]  # noqa: E501
        if severity not in allowed_values:
            raise ValueError(
                "Invalid value for `severity` ({0}), must be one of {1}"
                .format(severity, allowed_values)
            )

        self._severity = severity

    @property
    def confidence_score(self) -> float:
        """Gets the confidence_score of this TriggeredRule.

        Confidence score (0-100) that rule was violated  # noqa: E501

        :return: The confidence_score of this TriggeredRule.
        :rtype: float
        """
        return self._confidence_score

    @confidence_score.setter
    def confidence_score(self, confidence_score: float):
        """Sets the confidence_score of this TriggeredRule.

        Confidence score (0-100) that rule was violated  # noqa: E501

        :param confidence_score: The confidence_score of this TriggeredRule.
        :type confidence_score: float
        """
        if confidence_score is None:
            raise ValueError("Invalid value for `confidence_score`, must not be `None`")  # noqa: E501
        if confidence_score is not None and confidence_score > 100.0:  # noqa: E501
            raise ValueError("Invalid value for `confidence_score`, must be a value less than or equal to `100.0`")  # noqa: E501
        if confidence_score is not None and confidence_score < 50.0:  # noqa: E501
            raise ValueError("Invalid value for `confidence_score`, must be a value greater than or equal to `50.0`")  # noqa: E501

        self._confidence_score = confidence_score

    @property
    def trigger_context(self) -> str:
        """Gets the trigger_context of this TriggeredRule.

        Specific content excerpt that triggered the rule  # noqa: E501

        :return: The trigger_context of this TriggeredRule.
        :rtype: str
        """
        return self._trigger_context

    @trigger_context.setter
    def trigger_context(self, trigger_context: str):
        """Sets the trigger_context of this TriggeredRule.

        Specific content excerpt that triggered the rule  # noqa: E501

        :param trigger_context: The trigger_context of this TriggeredRule.
        :type trigger_context: str
        """
        if trigger_context is not None and len(trigger_context) > 500:
            raise ValueError("Invalid value for `trigger_context`, length must be less than or equal to `500`")  # noqa: E501

        self._trigger_context = trigger_context

    @property
    def user_message(self) -> str:
        """Gets the user_message of this TriggeredRule.

        User-friendly message explaining why content was flagged  # noqa: E501

        :return: The user_message of this TriggeredRule.
        :rtype: str
        """
        return self._user_message

    @user_message.setter
    def user_message(self, user_message: str):
        """Sets the user_message of this TriggeredRule.

        User-friendly message explaining why content was flagged  # noqa: E501

        :param user_message: The user_message of this TriggeredRule.
        :type user_message: str
        """
        if user_message is not None and len(user_message) > 200:
            raise ValueError("Invalid value for `user_message`, length must be less than or equal to `200`")  # noqa: E501

        self._user_message = user_message

    @property
    def detected_at(self) -> datetime:
        """Gets the detected_at of this TriggeredRule.

        ISO8601 timestamp when rule was triggered  # noqa: E501

        :return: The detected_at of this TriggeredRule.
        :rtype: datetime
        """
        return self._detected_at

    @detected_at.setter
    def detected_at(self, detected_at: datetime):
        """Sets the detected_at of this TriggeredRule.

        ISO8601 timestamp when rule was triggered  # noqa: E501

        :param detected_at: The detected_at of this TriggeredRule.
        :type detected_at: datetime
        """
        if detected_at is None:
            raise ValueError("Invalid value for `detected_at`, must not be `None`")  # noqa: E501

        self._detected_at = detected_at

    @property
    def priority(self) -> int:
        """Gets the priority of this TriggeredRule.

        Rule priority (0-100, higher = more important)  # noqa: E501

        :return: The priority of this TriggeredRule.
        :rtype: int
        """
        return self._priority

    @priority.setter
    def priority(self, priority: int):
        """Sets the priority of this TriggeredRule.

        Rule priority (0-100, higher = more important)  # noqa: E501

        :param priority: The priority of this TriggeredRule.
        :type priority: int
        """
        if priority is not None and priority > 100:  # noqa: E501
            raise ValueError("Invalid value for `priority`, must be a value less than or equal to `100`")  # noqa: E501
        if priority is not None and priority < 0:  # noqa: E501
            raise ValueError("Invalid value for `priority`, must be a value greater than or equal to `0`")  # noqa: E501

        self._priority = priority
