from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class UpdatePersonalityRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, description=None, personality_text=None, animal_type=None, tone=None, age_target=None):  # noqa: E501
        """UpdatePersonalityRequest - a model defined in OpenAPI

        :param name: The name of this UpdatePersonalityRequest.  # noqa: E501
        :type name: str
        :param description: The description of this UpdatePersonalityRequest.  # noqa: E501
        :type description: str
        :param personality_text: The personality_text of this UpdatePersonalityRequest.  # noqa: E501
        :type personality_text: str
        :param animal_type: The animal_type of this UpdatePersonalityRequest.  # noqa: E501
        :type animal_type: str
        :param tone: The tone of this UpdatePersonalityRequest.  # noqa: E501
        :type tone: str
        :param age_target: The age_target of this UpdatePersonalityRequest.  # noqa: E501
        :type age_target: str
        """
        self.openapi_types = {
            'name': str,
            'description': str,
            'personality_text': str,
            'animal_type': str,
            'tone': str,
            'age_target': str
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description',
            'personality_text': 'personalityText',
            'animal_type': 'animalType',
            'tone': 'tone',
            'age_target': 'ageTarget'
        }

        self._name = name
        self._description = description
        self._personality_text = personality_text
        self._animal_type = animal_type
        self._tone = tone
        self._age_target = age_target

    @classmethod
    def from_dict(cls, dikt) -> 'UpdatePersonalityRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdatePersonalityRequest of this UpdatePersonalityRequest.  # noqa: E501
        :rtype: UpdatePersonalityRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this UpdatePersonalityRequest.


        :return: The name of this UpdatePersonalityRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this UpdatePersonalityRequest.


        :param name: The name of this UpdatePersonalityRequest.
        :type name: str
        """
        if name is not None and len(name) > 100:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `100`")  # noqa: E501
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this UpdatePersonalityRequest.


        :return: The description of this UpdatePersonalityRequest.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this UpdatePersonalityRequest.


        :param description: The description of this UpdatePersonalityRequest.
        :type description: str
        """
        if description is not None and len(description) > 500:
            raise ValueError("Invalid value for `description`, length must be less than or equal to `500`")  # noqa: E501

        self._description = description

    @property
    def personality_text(self) -> str:
        """Gets the personality_text of this UpdatePersonalityRequest.


        :return: The personality_text of this UpdatePersonalityRequest.
        :rtype: str
        """
        return self._personality_text

    @personality_text.setter
    def personality_text(self, personality_text: str):
        """Sets the personality_text of this UpdatePersonalityRequest.


        :param personality_text: The personality_text of this UpdatePersonalityRequest.
        :type personality_text: str
        """
        if personality_text is not None and len(personality_text) > 5000:
            raise ValueError("Invalid value for `personality_text`, length must be less than or equal to `5000`")  # noqa: E501
        if personality_text is not None and len(personality_text) < 100:
            raise ValueError("Invalid value for `personality_text`, length must be greater than or equal to `100`")  # noqa: E501

        self._personality_text = personality_text

    @property
    def animal_type(self) -> str:
        """Gets the animal_type of this UpdatePersonalityRequest.


        :return: The animal_type of this UpdatePersonalityRequest.
        :rtype: str
        """
        return self._animal_type

    @animal_type.setter
    def animal_type(self, animal_type: str):
        """Sets the animal_type of this UpdatePersonalityRequest.


        :param animal_type: The animal_type of this UpdatePersonalityRequest.
        :type animal_type: str
        """
        allowed_values = ["MAMMAL", "BIRD", "REPTILE", "AMPHIBIAN", "FISH", "INVERTEBRATE"]  # noqa: E501
        if animal_type not in allowed_values:
            raise ValueError(
                "Invalid value for `animal_type` ({0}), must be one of {1}"
                .format(animal_type, allowed_values)
            )

        self._animal_type = animal_type

    @property
    def tone(self) -> str:
        """Gets the tone of this UpdatePersonalityRequest.


        :return: The tone of this UpdatePersonalityRequest.
        :rtype: str
        """
        return self._tone

    @tone.setter
    def tone(self, tone: str):
        """Sets the tone of this UpdatePersonalityRequest.


        :param tone: The tone of this UpdatePersonalityRequest.
        :type tone: str
        """
        allowed_values = ["PLAYFUL", "EDUCATIONAL", "CALM", "ENERGETIC", "WISE", "FUNNY"]  # noqa: E501
        if tone not in allowed_values:
            raise ValueError(
                "Invalid value for `tone` ({0}), must be one of {1}"
                .format(tone, allowed_values)
            )

        self._tone = tone

    @property
    def age_target(self) -> str:
        """Gets the age_target of this UpdatePersonalityRequest.


        :return: The age_target of this UpdatePersonalityRequest.
        :rtype: str
        """
        return self._age_target

    @age_target.setter
    def age_target(self, age_target: str):
        """Sets the age_target of this UpdatePersonalityRequest.


        :param age_target: The age_target of this UpdatePersonalityRequest.
        :type age_target: str
        """
        allowed_values = ["PRESCHOOL", "ELEMENTARY", "FAMILY", "ALL_AGES"]  # noqa: E501
        if age_target not in allowed_values:
            raise ValueError(
                "Invalid value for `age_target` ({0}), must be one of {1}"
                .format(age_target, allowed_values)
            )

        self._age_target = age_target
