from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.update_user_context_request_conversation_data import UpdateUserContextRequestConversationData
from openapi_server.models.update_user_context_request_extracted_preferences import UpdateUserContextRequestExtractedPreferences
from openapi_server import util

from openapi_server.models.update_user_context_request_conversation_data import UpdateUserContextRequestConversationData  # noqa: E501
from openapi_server.models.update_user_context_request_extracted_preferences import UpdateUserContextRequestExtractedPreferences  # noqa: E501

class UpdateUserContextRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, conversation_data=None, extracted_preferences=None):  # noqa: E501
        """UpdateUserContextRequest - a model defined in OpenAPI

        :param conversation_data: The conversation_data of this UpdateUserContextRequest.  # noqa: E501
        :type conversation_data: UpdateUserContextRequestConversationData
        :param extracted_preferences: The extracted_preferences of this UpdateUserContextRequest.  # noqa: E501
        :type extracted_preferences: UpdateUserContextRequestExtractedPreferences
        """
        self.openapi_types = {
            'conversation_data': UpdateUserContextRequestConversationData,
            'extracted_preferences': UpdateUserContextRequestExtractedPreferences
        }

        self.attribute_map = {
            'conversation_data': 'conversationData',
            'extracted_preferences': 'extractedPreferences'
        }

        self._conversation_data = conversation_data
        self._extracted_preferences = extracted_preferences

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateUserContextRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The updateUserContext_request of this UpdateUserContextRequest.  # noqa: E501
        :rtype: UpdateUserContextRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def conversation_data(self) -> UpdateUserContextRequestConversationData:
        """Gets the conversation_data of this UpdateUserContextRequest.


        :return: The conversation_data of this UpdateUserContextRequest.
        :rtype: UpdateUserContextRequestConversationData
        """
        return self._conversation_data

    @conversation_data.setter
    def conversation_data(self, conversation_data: UpdateUserContextRequestConversationData):
        """Sets the conversation_data of this UpdateUserContextRequest.


        :param conversation_data: The conversation_data of this UpdateUserContextRequest.
        :type conversation_data: UpdateUserContextRequestConversationData
        """

        self._conversation_data = conversation_data

    @property
    def extracted_preferences(self) -> UpdateUserContextRequestExtractedPreferences:
        """Gets the extracted_preferences of this UpdateUserContextRequest.


        :return: The extracted_preferences of this UpdateUserContextRequest.
        :rtype: UpdateUserContextRequestExtractedPreferences
        """
        return self._extracted_preferences

    @extracted_preferences.setter
    def extracted_preferences(self, extracted_preferences: UpdateUserContextRequestExtractedPreferences):
        """Sets the extracted_preferences of this UpdateUserContextRequest.


        :param extracted_preferences: The extracted_preferences of this UpdateUserContextRequest.
        :type extracted_preferences: UpdateUserContextRequestExtractedPreferences
        """

        self._extracted_preferences = extracted_preferences
