from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class UsageSummary(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, userid=None, total_sessions=None, total_turns=None, last_active=None):  # noqa: E501
        """UsageSummary - a model defined in OpenAPI

        :param userid: The userid of this UsageSummary.  # noqa: E501
        :type userid: str
        :param total_sessions: The total_sessions of this UsageSummary.  # noqa: E501
        :type total_sessions: int
        :param total_turns: The total_turns of this UsageSummary.  # noqa: E501
        :type total_turns: int
        :param last_active: The last_active of this UsageSummary.  # noqa: E501
        :type last_active: datetime
        """
        self.openapi_types = {
            'userid': str,
            'total_sessions': int,
            'total_turns': int,
            'last_active': datetime
        }

        self.attribute_map = {
            'userid': 'userid',
            'total_sessions': 'totalSessions',
            'total_turns': 'totalTurns',
            'last_active': 'lastActive'
        }

        self._userid = userid
        self._total_sessions = total_sessions
        self._total_turns = total_turns
        self._last_active = last_active

    @classmethod
    def from_dict(cls, dikt) -> 'UsageSummary':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UsageSummary of this UsageSummary.  # noqa: E501
        :rtype: UsageSummary
        """
        return util.deserialize_model(dikt, cls)

    @property
    def userid(self) -> str:
        """Gets the userid of this UsageSummary.


        :return: The userid of this UsageSummary.
        :rtype: str
        """
        return self._userid

    @userid.setter
    def userid(self, userid: str):
        """Sets the userid of this UsageSummary.


        :param userid: The userid of this UsageSummary.
        :type userid: str
        """

        self._userid = userid

    @property
    def total_sessions(self) -> int:
        """Gets the total_sessions of this UsageSummary.


        :return: The total_sessions of this UsageSummary.
        :rtype: int
        """
        return self._total_sessions

    @total_sessions.setter
    def total_sessions(self, total_sessions: int):
        """Sets the total_sessions of this UsageSummary.


        :param total_sessions: The total_sessions of this UsageSummary.
        :type total_sessions: int
        """

        self._total_sessions = total_sessions

    @property
    def total_turns(self) -> int:
        """Gets the total_turns of this UsageSummary.


        :return: The total_turns of this UsageSummary.
        :rtype: int
        """
        return self._total_turns

    @total_turns.setter
    def total_turns(self, total_turns: int):
        """Sets the total_turns of this UsageSummary.


        :param total_turns: The total_turns of this UsageSummary.
        :type total_turns: int
        """

        self._total_turns = total_turns

    @property
    def last_active(self) -> datetime:
        """Gets the last_active of this UsageSummary.


        :return: The last_active of this UsageSummary.
        :rtype: datetime
        """
        return self._last_active

    @last_active.setter
    def last_active(self, last_active: datetime):
        """Sets the last_active of this UsageSummary.


        :param last_active: The last_active of this UsageSummary.
        :type last_active: datetime
        """

        self._last_active = last_active
