from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.audit_stamp import AuditStamp
import re
from openapi_server import util

from openapi_server.models.audit_stamp import AuditStamp  # noqa: E501
import re  # noqa: E501

class UserInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_id=None, email=None, display_name=None, phone_number=None, age=None, role=None, user_type='none', family_id=None, created=None, modified=None, deleted=None, soft_delete=False):  # noqa: E501
        """UserInput - a model defined in OpenAPI

        :param user_id: The user_id of this UserInput.  # noqa: E501
        :type user_id: str
        :param email: The email of this UserInput.  # noqa: E501
        :type email: str
        :param display_name: The display_name of this UserInput.  # noqa: E501
        :type display_name: str
        :param phone_number: The phone_number of this UserInput.  # noqa: E501
        :type phone_number: str
        :param age: The age of this UserInput.  # noqa: E501
        :type age: int
        :param role: The role of this UserInput.  # noqa: E501
        :type role: str
        :param user_type: The user_type of this UserInput.  # noqa: E501
        :type user_type: str
        :param family_id: The family_id of this UserInput.  # noqa: E501
        :type family_id: str
        :param created: The created of this UserInput.  # noqa: E501
        :type created: AuditStamp
        :param modified: The modified of this UserInput.  # noqa: E501
        :type modified: AuditStamp
        :param deleted: The deleted of this UserInput.  # noqa: E501
        :type deleted: AuditStamp
        :param soft_delete: The soft_delete of this UserInput.  # noqa: E501
        :type soft_delete: bool
        """
        self.openapi_types = {
            'user_id': str,
            'email': str,
            'display_name': str,
            'phone_number': str,
            'age': int,
            'role': str,
            'user_type': str,
            'family_id': str,
            'created': AuditStamp,
            'modified': AuditStamp,
            'deleted': AuditStamp,
            'soft_delete': bool
        }

        self.attribute_map = {
            'user_id': 'userId',
            'email': 'email',
            'display_name': 'displayName',
            'phone_number': 'phoneNumber',
            'age': 'age',
            'role': 'role',
            'user_type': 'userType',
            'family_id': 'familyId',
            'created': 'created',
            'modified': 'modified',
            'deleted': 'deleted',
            'soft_delete': 'softDelete'
        }

        self._user_id = user_id
        self._email = email
        self._display_name = display_name
        self._phone_number = phone_number
        self._age = age
        self._role = role
        self._user_type = user_type
        self._family_id = family_id
        self._created = created
        self._modified = modified
        self._deleted = deleted
        self._soft_delete = soft_delete

    @classmethod
    def from_dict(cls, dikt) -> 'UserInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserInput of this UserInput.  # noqa: E501
        :rtype: UserInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> str:
        """Gets the user_id of this UserInput.


        :return: The user_id of this UserInput.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this UserInput.


        :param user_id: The user_id of this UserInput.
        :type user_id: str
        """

        self._user_id = user_id

    @property
    def email(self) -> str:
        """Gets the email of this UserInput.


        :return: The email of this UserInput.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this UserInput.


        :param email: The email of this UserInput.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def display_name(self) -> str:
        """Gets the display_name of this UserInput.

        Display name with basic character validation  # noqa: E501

        :return: The display_name of this UserInput.
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name: str):
        """Sets the display_name of this UserInput.

        Display name with basic character validation  # noqa: E501

        :param display_name: The display_name of this UserInput.
        :type display_name: str
        """
        if display_name is not None and len(display_name) > 100:
            raise ValueError("Invalid value for `display_name`, length must be less than or equal to `100`")  # noqa: E501
        if display_name is not None and len(display_name) < 1:
            raise ValueError("Invalid value for `display_name`, length must be greater than or equal to `1`")  # noqa: E501
        if display_name is not None and not re.search(r'^[a-zA-Z0-9\s\-\.\']+$', display_name):  # noqa: E501
            raise ValueError(r"Invalid value for `display_name`, must be a follow pattern or equal to `/^[a-zA-Z0-9\s\-\.']+$/`")  # noqa: E501

        self._display_name = display_name

    @property
    def phone_number(self) -> str:
        """Gets the phone_number of this UserInput.

        E.164 international phone number format  # noqa: E501

        :return: The phone_number of this UserInput.
        :rtype: str
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number: str):
        """Sets the phone_number of this UserInput.

        E.164 international phone number format  # noqa: E501

        :param phone_number: The phone_number of this UserInput.
        :type phone_number: str
        """
        if phone_number is not None and not re.search(r'^\+[1-9]\d{1,14}$', phone_number):  # noqa: E501
            raise ValueError(r"Invalid value for `phone_number`, must be a follow pattern or equal to `/^\+[1-9]\d{1,14}$/`")  # noqa: E501

        self._phone_number = phone_number

    @property
    def age(self) -> int:
        """Gets the age of this UserInput.

        Age validation for reasonable ranges  # noqa: E501

        :return: The age of this UserInput.
        :rtype: int
        """
        return self._age

    @age.setter
    def age(self, age: int):
        """Sets the age of this UserInput.

        Age validation for reasonable ranges  # noqa: E501

        :param age: The age of this UserInput.
        :type age: int
        """
        if age is not None and age > 120:  # noqa: E501
            raise ValueError("Invalid value for `age`, must be a value less than or equal to `120`")  # noqa: E501
        if age is not None and age < 3:  # noqa: E501
            raise ValueError("Invalid value for `age`, must be a value greater than or equal to `3`")  # noqa: E501

        self._age = age

    @property
    def role(self) -> str:
        """Gets the role of this UserInput.


        :return: The role of this UserInput.
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role: str):
        """Sets the role of this UserInput.


        :param role: The role of this UserInput.
        :type role: str
        """
        allowed_values = ["visitor", "user", "member", "editor", "admin"]  # noqa: E501
        if role not in allowed_values:
            raise ValueError(
                "Invalid value for `role` ({0}), must be one of {1}"
                .format(role, allowed_values)
            )

        self._role = role

    @property
    def user_type(self) -> str:
        """Gets the user_type of this UserInput.


        :return: The user_type of this UserInput.
        :rtype: str
        """
        return self._user_type

    @user_type.setter
    def user_type(self, user_type: str):
        """Sets the user_type of this UserInput.


        :param user_type: The user_type of this UserInput.
        :type user_type: str
        """
        allowed_values = ["none", "parent", "student"]  # noqa: E501
        if user_type not in allowed_values:
            raise ValueError(
                "Invalid value for `user_type` ({0}), must be one of {1}"
                .format(user_type, allowed_values)
            )

        self._user_type = user_type

    @property
    def family_id(self) -> str:
        """Gets the family_id of this UserInput.


        :return: The family_id of this UserInput.
        :rtype: str
        """
        return self._family_id

    @family_id.setter
    def family_id(self, family_id: str):
        """Sets the family_id of this UserInput.


        :param family_id: The family_id of this UserInput.
        :type family_id: str
        """

        self._family_id = family_id

    @property
    def created(self) -> AuditStamp:
        """Gets the created of this UserInput.


        :return: The created of this UserInput.
        :rtype: AuditStamp
        """
        return self._created

    @created.setter
    def created(self, created: AuditStamp):
        """Sets the created of this UserInput.


        :param created: The created of this UserInput.
        :type created: AuditStamp
        """

        self._created = created

    @property
    def modified(self) -> AuditStamp:
        """Gets the modified of this UserInput.


        :return: The modified of this UserInput.
        :rtype: AuditStamp
        """
        return self._modified

    @modified.setter
    def modified(self, modified: AuditStamp):
        """Sets the modified of this UserInput.


        :param modified: The modified of this UserInput.
        :type modified: AuditStamp
        """

        self._modified = modified

    @property
    def deleted(self) -> AuditStamp:
        """Gets the deleted of this UserInput.


        :return: The deleted of this UserInput.
        :rtype: AuditStamp
        """
        return self._deleted

    @deleted.setter
    def deleted(self, deleted: AuditStamp):
        """Sets the deleted of this UserInput.


        :param deleted: The deleted of this UserInput.
        :type deleted: AuditStamp
        """

        self._deleted = deleted

    @property
    def soft_delete(self) -> bool:
        """Gets the soft_delete of this UserInput.


        :return: The soft_delete of this UserInput.
        :rtype: bool
        """
        return self._soft_delete

    @soft_delete.setter
    def soft_delete(self, soft_delete: bool):
        """Sets the soft_delete of this UserInput.


        :param soft_delete: The soft_delete of this UserInput.
        :type soft_delete: bool
        """

        self._soft_delete = soft_delete
