from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.audit_stamp import AuditStamp
from openapi_server import util

from openapi_server.models.audit_stamp import AuditStamp  # noqa: E501

class UserInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_id=None, email=None, display_name=None, role=None, user_type='none', family_id=None, created=None, modified=None, deleted=None, soft_delete=False):  # noqa: E501
        """UserInput - a model defined in OpenAPI

        :param user_id: The user_id of this UserInput.  # noqa: E501
        :type user_id: str
        :param email: The email of this UserInput.  # noqa: E501
        :type email: str
        :param display_name: The display_name of this UserInput.  # noqa: E501
        :type display_name: str
        :param role: The role of this UserInput.  # noqa: E501
        :type role: str
        :param user_type: The user_type of this UserInput.  # noqa: E501
        :type user_type: str
        :param family_id: The family_id of this UserInput.  # noqa: E501
        :type family_id: str
        :param created: The created of this UserInput.  # noqa: E501
        :type created: AuditStamp
        :param modified: The modified of this UserInput.  # noqa: E501
        :type modified: AuditStamp
        :param deleted: The deleted of this UserInput.  # noqa: E501
        :type deleted: AuditStamp
        :param soft_delete: The soft_delete of this UserInput.  # noqa: E501
        :type soft_delete: bool
        """
        self.openapi_types = {
            'user_id': str,
            'email': str,
            'display_name': str,
            'role': str,
            'user_type': str,
            'family_id': str,
            'created': AuditStamp,
            'modified': AuditStamp,
            'deleted': AuditStamp,
            'soft_delete': bool
        }

        self.attribute_map = {
            'user_id': 'userId',
            'email': 'email',
            'display_name': 'displayName',
            'role': 'role',
            'user_type': 'userType',
            'family_id': 'familyId',
            'created': 'created',
            'modified': 'modified',
            'deleted': 'deleted',
            'soft_delete': 'softDelete'
        }

        self._user_id = user_id
        self._email = email
        self._display_name = display_name
        self._role = role
        self._user_type = user_type
        self._family_id = family_id
        self._created = created
        self._modified = modified
        self._deleted = deleted
        self._soft_delete = soft_delete

    @classmethod
    def from_dict(cls, dikt) -> 'UserInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserInput of this UserInput.  # noqa: E501
        :rtype: UserInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> str:
        """Gets the user_id of this UserInput.


        :return: The user_id of this UserInput.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this UserInput.


        :param user_id: The user_id of this UserInput.
        :type user_id: str
        """

        self._user_id = user_id

    @property
    def email(self) -> str:
        """Gets the email of this UserInput.


        :return: The email of this UserInput.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this UserInput.


        :param email: The email of this UserInput.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def display_name(self) -> str:
        """Gets the display_name of this UserInput.


        :return: The display_name of this UserInput.
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name: str):
        """Sets the display_name of this UserInput.


        :param display_name: The display_name of this UserInput.
        :type display_name: str
        """

        self._display_name = display_name

    @property
    def role(self) -> str:
        """Gets the role of this UserInput.


        :return: The role of this UserInput.
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role: str):
        """Sets the role of this UserInput.


        :param role: The role of this UserInput.
        :type role: str
        """
        allowed_values = ["visitor", "user", "editor", "admin"]  # noqa: E501
        if role not in allowed_values:
            raise ValueError(
                "Invalid value for `role` ({0}), must be one of {1}"
                .format(role, allowed_values)
            )

        self._role = role

    @property
    def user_type(self) -> str:
        """Gets the user_type of this UserInput.


        :return: The user_type of this UserInput.
        :rtype: str
        """
        return self._user_type

    @user_type.setter
    def user_type(self, user_type: str):
        """Sets the user_type of this UserInput.


        :param user_type: The user_type of this UserInput.
        :type user_type: str
        """
        allowed_values = ["none", "parent", "student"]  # noqa: E501
        if user_type not in allowed_values:
            raise ValueError(
                "Invalid value for `user_type` ({0}), must be one of {1}"
                .format(user_type, allowed_values)
            )

        self._user_type = user_type

    @property
    def family_id(self) -> str:
        """Gets the family_id of this UserInput.


        :return: The family_id of this UserInput.
        :rtype: str
        """
        return self._family_id

    @family_id.setter
    def family_id(self, family_id: str):
        """Sets the family_id of this UserInput.


        :param family_id: The family_id of this UserInput.
        :type family_id: str
        """

        self._family_id = family_id

    @property
    def created(self) -> AuditStamp:
        """Gets the created of this UserInput.


        :return: The created of this UserInput.
        :rtype: AuditStamp
        """
        return self._created

    @created.setter
    def created(self, created: AuditStamp):
        """Sets the created of this UserInput.


        :param created: The created of this UserInput.
        :type created: AuditStamp
        """

        self._created = created

    @property
    def modified(self) -> AuditStamp:
        """Gets the modified of this UserInput.


        :return: The modified of this UserInput.
        :rtype: AuditStamp
        """
        return self._modified

    @modified.setter
    def modified(self, modified: AuditStamp):
        """Sets the modified of this UserInput.


        :param modified: The modified of this UserInput.
        :type modified: AuditStamp
        """

        self._modified = modified

    @property
    def deleted(self) -> AuditStamp:
        """Gets the deleted of this UserInput.


        :return: The deleted of this UserInput.
        :rtype: AuditStamp
        """
        return self._deleted

    @deleted.setter
    def deleted(self, deleted: AuditStamp):
        """Sets the deleted of this UserInput.


        :param deleted: The deleted of this UserInput.
        :type deleted: AuditStamp
        """

        self._deleted = deleted

    @property
    def soft_delete(self) -> bool:
        """Gets the soft_delete of this UserInput.


        :return: The soft_delete of this UserInput.
        :rtype: bool
        """
        return self._soft_delete

    @soft_delete.setter
    def soft_delete(self, soft_delete: bool):
        """Sets the soft_delete of this UserInput.


        :param soft_delete: The soft_delete of this UserInput.
        :type soft_delete: bool
        """

        self._soft_delete = soft_delete
