# coding: utf-8

"""
    CMZ API

    API for the Cougar Mountain Zoo digital ambassador platform

    The version of the OpenAPI document: 1.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.audit_stamp import AuditStamp
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AuditFields(BaseModel):
    """
    AuditFields
    """ # noqa: E501
    created: Optional[AuditStamp] = None
    modified: Optional[AuditStamp] = None
    deleted: Optional[AuditStamp] = None
    soft_delete: Optional[StrictBool] = Field(default=False, alias="softDelete")
    __properties: ClassVar[List[str]] = ["created", "modified", "deleted", "softDelete"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AuditFields from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of created
        if self.created:
            _dict['created'] = self.created.to_dict()
        # override the default output from pydantic by calling `to_dict()` of modified
        if self.modified:
            _dict['modified'] = self.modified.to_dict()
        # override the default output from pydantic by calling `to_dict()` of deleted
        if self.deleted:
            _dict['deleted'] = self.deleted.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AuditFields from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created": AuditStamp.from_dict(obj.get("created")) if obj.get("created") is not None else None,
            "modified": AuditStamp.from_dict(obj.get("modified")) if obj.get("modified") is not None else None,
            "deleted": AuditStamp.from_dict(obj.get("deleted")) if obj.get("deleted") is not None else None,
            "softDelete": obj.get("softDelete") if obj.get("softDelete") is not None else False
        })
        return _obj


