#!/bin/bash

# Deploy AWS Cognito infrastructure using CloudFormation
# This script deploys the Cognito User Pool and Identity Pool resources

set -e

# Configuration
STACK_NAME="cmz-chatbot-cognito"
TEMPLATE_FILE="../templates/cognito.yaml"
REGION="${AWS_REGION:-us-west-2}"
ENVIRONMENT="${ENVIRONMENT:-dev}"
PROJECT_NAME="${PROJECT_NAME:-cmz-chatbot}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}🚀 Deploying Cognito infrastructure...${NC}"
echo "📋 Configuration:"
echo "  Stack Name: $STACK_NAME"
echo "  Environment: $ENVIRONMENT" 
echo "  Project: $PROJECT_NAME"
echo "  Region: $REGION"
echo ""

# Check if AWS CLI is configured
if ! aws sts get-caller-identity > /dev/null 2>&1; then
    echo -e "${RED}❌ AWS CLI not configured or no valid credentials${NC}"
    echo "Please run: aws configure --profile cmz"
    exit 1
fi

ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
echo -e "${GREEN}✅ AWS CLI configured for account: $ACCOUNT_ID${NC}"
echo ""

# Change to script directory
cd "$(dirname "$0")"

# Check if template file exists
if [ ! -f "$TEMPLATE_FILE" ]; then
    echo -e "${RED}❌ Template file not found: $TEMPLATE_FILE${NC}"
    exit 1
fi

echo -e "${YELLOW}🔍 Validating CloudFormation template...${NC}"
aws cloudformation validate-template --template-body file://$TEMPLATE_FILE --region $REGION

echo -e "${GREEN}✅ Template validation successful${NC}"
echo ""

# Check if stack exists
if aws cloudformation describe-stacks --stack-name $STACK_NAME --region $REGION > /dev/null 2>&1; then
    echo -e "${YELLOW}📦 Updating existing stack: $STACK_NAME${NC}"
    OPERATION="update-stack"
else
    echo -e "${YELLOW}🏗️ Creating new stack: $STACK_NAME${NC}"
    OPERATION="create-stack"
fi

# Deploy the stack
aws cloudformation $OPERATION \
    --stack-name $STACK_NAME \
    --template-body file://$TEMPLATE_FILE \
    --parameters \
        ParameterKey=Environment,ParameterValue=$ENVIRONMENT \
        ParameterKey=ProjectName,ParameterValue=$PROJECT_NAME \
    --capabilities CAPABILITY_NAMED_IAM \
    --region $REGION

echo ""
echo -e "${YELLOW}⏳ Waiting for stack operation to complete...${NC}"
if [ "$OPERATION" = "create-stack" ]; then
    aws cloudformation wait stack-create-complete --stack-name $STACK_NAME --region $REGION
else
    aws cloudformation wait stack-update-complete --stack-name $STACK_NAME --region $REGION
fi

# Get stack outputs
echo -e "${GREEN}✅ Stack operation completed successfully!${NC}"
echo ""
echo -e "${GREEN}📋 Stack Outputs:${NC}"
aws cloudformation describe-stacks \
    --stack-name $STACK_NAME \
    --query 'Stacks[0].Outputs[*].[OutputKey,OutputValue]' \
    --output table \
    --region $REGION

echo ""
echo -e "${YELLOW}🔐 Retrieving Cognito Client Secret...${NC}"

# Get User Pool Client ID from stack outputs
CLIENT_ID=$(aws cloudformation describe-stacks \
    --stack-name $STACK_NAME \
    --query 'Stacks[0].Outputs[?OutputKey==`UserPoolClientId`].OutputValue' \
    --output text \
    --region $REGION)

# Get User Pool ID from stack outputs  
USER_POOL_ID=$(aws cloudformation describe-stacks \
    --stack-name $STACK_NAME \
    --query 'Stacks[0].Outputs[?OutputKey==`UserPoolId`].OutputValue' \
    --output text \
    --region $REGION)

# Get Identity Pool ID from stack outputs
IDENTITY_POOL_ID=$(aws cloudformation describe-stacks \
    --stack-name $STACK_NAME \
    --query 'Stacks[0].Outputs[?OutputKey==`IdentityPoolId`].OutputValue' \
    --output text \
    --region $REGION)

# Retrieve client secret (not available in CloudFormation outputs)
CLIENT_SECRET=$(aws cognito-idp describe-user-pool-client \
    --user-pool-id $USER_POOL_ID \
    --client-id $CLIENT_ID \
    --query 'UserPoolClient.ClientSecret' \
    --output text \
    --region $REGION)

echo -e "${GREEN}✅ Client secret retrieved${NC}"
echo ""

# Generate environment configuration
ENV_FILE="../../.env.cognito"
echo -e "${GREEN}💾 Generating environment configuration: $ENV_FILE${NC}"

cat > "$ENV_FILE" << EOF
# AWS Cognito Configuration for CMZ Chatbot
# Generated by deploy-cognito.sh on $(date)

COGNITO_USER_POOL_ID=$USER_POOL_ID
COGNITO_CLIENT_ID=$CLIENT_ID
COGNITO_CLIENT_SECRET=$CLIENT_SECRET
COGNITO_IDENTITY_POOL_ID=$IDENTITY_POOL_ID
AWS_REGION=$REGION
EOF

echo -e "${GREEN}✅ Environment configuration saved to $ENV_FILE${NC}"
echo ""

echo -e "${GREEN}🎉 Cognito infrastructure deployment complete!${NC}"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "1. Source the environment file: source .env.cognito"
echo "2. Create test users (see create-test-user.sh)"
echo "3. Test authentication integration"
echo ""
echo -e "${YELLOW}Resources created:${NC}"
echo "  - User Pool: $USER_POOL_ID"
echo "  - Client: $CLIENT_ID"
echo "  - Identity Pool: $IDENTITY_POOL_ID"
echo "  - Groups: admin, educator, parent, student"