AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Cognito User Pool and Identity Pool for CMZ Chatbot Authentication'

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name (dev, staging, prod)
    AllowedValues:
      - dev
      - staging
      - prod
  
  ProjectName:
    Type: String
    Default: cmz-chatbot
    Description: Project name for resource naming

Resources:
  # Cognito User Pool
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${ProjectName}-${Environment}-userpool"
      # Simplified password policy for development
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: false
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
      # Use email for username
      UsernameAttributes:
        - email
      # Auto-verify email addresses
      AutoVerifiedAttributes:
        - email
      # Admin user creation settings
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
        UnusedAccountValidityDays: 7
      # Email verification template
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
        DefaultEmailSubject: !Sub "${ProjectName} - Verify your account"
        DefaultEmailMessage: "Your verification code is {####}"
      # Require email verification before updates
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate:
          - email
      # Standard attributes
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: true
        - Name: name
          AttributeDataType: String
          Required: false
          Mutable: true

  # Cognito User Pool Client
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: !Sub "${ProjectName}-${Environment}-client"
      GenerateSecret: true
      # Authentication flows
      ExplicitAuthFlows:
        - USER_PASSWORD_AUTH
        - ADMIN_NO_SRP_AUTH
      # Identity providers
      SupportedIdentityProviders:
        - COGNITO
      # Token validity settings (minutes for access/id, days for refresh)
      AccessTokenValidity: 60
      IdTokenValidity: 60
      RefreshTokenValidity: 30
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: days
      # Attribute permissions
      ReadAttributes:
        - email
        - name
        - email_verified
      WriteAttributes:
        - email
        - name

  # Cognito Identity Pool
  CognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Sub "${ProjectName}-${Environment}-identitypool"
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref CognitoUserPoolClient
          ProviderName: !GetAtt CognitoUserPool.ProviderName
          ServerSideTokenCheck: false

  # IAM Role for authenticated users
  CognitoAuthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-${Environment}-authenticated-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud: !Ref CognitoIdentityPool
              ForAnyValue:StringLike:
                cognito-identity.amazonaws.com:amr: authenticated
      Policies:
        - PolicyName: CognitoAuthenticatedPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Allow basic AWS service access for authenticated users
              - Effect: Allow
                Action:
                  - mobileanalytics:PutEvents
                  - cognito-sync:*
                  - cognito-identity:*
                Resource: "*"

  # Attach roles to identity pool
  CognitoIdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref CognitoIdentityPool
      Roles:
        authenticated: !GetAtt CognitoAuthenticatedRole.Arn

  # Cognito Groups for RBAC
  AdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      UserPoolId: !Ref CognitoUserPool
      GroupName: admin
      Description: Administrators with full access
      Precedence: 1

  EducatorGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      UserPoolId: !Ref CognitoUserPool
      GroupName: educator
      Description: Educators with animal and family management access
      Precedence: 2

  ParentGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      UserPoolId: !Ref CognitoUserPool
      GroupName: parent
      Description: Parents with family access
      Precedence: 3

  StudentGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      UserPoolId: !Ref CognitoUserPool
      GroupName: student
      Description: Students with read-only access
      Precedence: 4

Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref CognitoUserPool
    Export:
      Name: !Sub "${AWS::StackName}-UserPoolId"

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref CognitoUserPoolClient
    Export:
      Name: !Sub "${AWS::StackName}-UserPoolClientId"

  IdentityPoolId:
    Description: Cognito Identity Pool ID
    Value: !Ref CognitoIdentityPool
    Export:
      Name: !Sub "${AWS::StackName}-IdentityPoolId"

  UserPoolProviderName:
    Description: Cognito User Pool Provider Name
    Value: !GetAtt CognitoUserPool.ProviderName
    Export:
      Name: !Sub "${AWS::StackName}-UserPoolProviderName"

  Region:
    Description: AWS Region
    Value: !Ref AWS::Region
    Export:
      Name: !Sub "${AWS::StackName}-Region"

  # Note: Client secret cannot be exported directly from CloudFormation
  # It must be retrieved using AWS CLI or SDK after stack creation